### ISSUE TITLE
Flags doesn't work, config overnight stops working right

### ISSUE THREAD

**Issue by BakyCz123456** [Zrips/Residence#1000]
A player claims some land, but other players are free to build, destroy, open chests, use lever.
I set size 200 x 200 blocks, the first day it worked right, but the next day it didn't work and the size somehow was only 20 x 20. This is third time it did.
What should I do?

Version (5.1.1.0)

**Comment by Zrips** [comment]
All this depends on players access to permissions and groups. We have permissions to bypass some more command actions like build and break with something like residence.bypass.build residence.bypass.destroy or being res admin. Residence size gets determined by your access to groups, you can always double check your access with /res limits and just make sure that residence group is the one you should be having.
