### ISSUE TITLE
Residence Titles not showing up

### ISSUE THREAD

**Issue by OnlyMatty** [Zrips/Residence#1007]
Hi, it is quite a long time since then, but there was a version of the plugin that made it unable for residences to show their welcome/leave titles. I have paid it no mind, because I hoped that it's gonna get fixed in next update, but no. It did not, so I am asking here for support.

**Comment by kamil445** [comment]
Had this same issue, don't know why but plugin removed all enter/leave message and looks like UTF-8 doesn't working anymore .

**Comment by Zrips** [comment]
Next version will introduce some fixes which might fix this issue, if issue will still be there please let me know with file example and some information about your server, mainly which type of language its running on as it looks to be some issue with encoding.
