### ISSUE TITLE
Entry/Leave Messages revert to those of other residences

### ISSUE THREAD

**Issue by Spagz** [Zrips/Residence#1010]
Some of the subzones within residences are noticing that the entry/leave messages keep getting reset to those of another subzone somewhere else in the world. The subzones have very different names.

Also, entry/leave messages cannot be removed. When running that command it just does not seem to do anything.

**Comment by Craigdb** [comment]
I have a similar issue where messages will save during the current session but revert to the default after a server resart - I look at the yml files and no extra enter and leave messages are being saved

**Comment by kamil445** [comment]
On my server all enter/leave messages disappeared from yml file, and now UTF-8 characters cannot be saved, plugin crashing "org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1"

**Comment by pjindras** [comment]
Hello, i have the same problem.

**Comment by Zrips** [comment]
If issue persists with next update please let me know with included file for testing and some general information of used languages and possible examples of enter/leave messages
Closing this ticket, if there is still an issue please make new one.
93515a5c472392ba8e3f04c3ca2f4139b18ef64a
