### ISSUE TITLE
DisabledWorlds does not work.

### ISSUE THREAD

**Issue by KarlPro123** [Zrips/Residence#1011]
The config section:  (Yes the world names are correct)
    
    DefaultWorld: Survival
    DisabledWorlds:
      # List Of Worlds where this plugin is disabled
      List:
      - Survival_the_end
      - Survival_the_nether
      # Disables all listeners in included worlds
      DisableListeners: true
      # Disabled any command usage in included worlds
      DisableCommands: true
      
Players can still create residences in these disabled worlds and commands also work. Disabled all residence permissions in these worlds with LuckPerms too, but they still can create new ones.

**Residence version:** 5.1.1.1
**Paper:** 424

**Comment by Zrips** [comment]
I know that you are already said that world names are correct, but there is only one check done which in general could fail and that is if world name is incorrect, this includes world names capitalization. If issue persists with exact names let me know, but this is the only thing which could cause it to not work properly.
