### ISSUE TITLE
Server crash by Could not pass event BlockPhysicsEvent to Residence

### ISSUE THREAD

**Issue by qaz13570111** [Zrips/Residence#1014]
Server version:
PaperSpigot 1.12.2

Plugin Version:
Residence : v5.1.1.1
CMILib : 1.2.4.5
how can i fix it

Crash report:
https://pastebin.pl/view/7c713a8a

**Comment by Zrips** [comment]
Looks to be issue with 1.12.2 server and dryup flag, you can globally disable this flag to avoid this issue. Alternatively if its an option you can go with newer minecraft versions which dont have this issue. 
Will make some changes with next update, let me know if issue persists after it. 
4f986cd3a662fa592249bd865ed0bfc1f5db02d3
