### ISSUE TITLE
delete money

### ISSUE THREAD

**Issue by CRGBS** [Zrips/Residence#102]
The amount returned when you delete residence is incorrect
BuyCost: 0.7
SellCost: 0.6
Will not return the correct number 
i return random amount
Pleasae help me and my english no good I use google translate!

**Comment by Zrips** [comment]
Can you elaborate on actual values? check balance, select 10x10x10 area, create residence, check balance, remove residence, check balance again.
Currently all works as it should do.

**Comment by Sakanas** [comment]
Economy:
          CanBuy: true
          CanSell: false
          IgnoreLimits: true
          BuyCost: 0.01
          SellCost: 0.01
          RenewCost: 0.01
[https://imgur.com/AVfRDIm](url)
