### ISSUE TITLE
Build flag not working

### ISSUE THREAD

**Issue by Makmefer** [Zrips/Residence#1020]
I set both world guard and Residence plugin flags to allow players to build in their homes but they still cant. How do I fix this?

**Comment by Zrips** [comment]
Avoid having two area protection plugins at one time. This will cause some issues. Aside of this, without any information to even know what type of error you got while trying to build in area we can't really help you out here. By default players will have access to their own residence and to residences where they have build flat enabled in entire residence or for this specific player. This can be done with /res set or /res pset commands.
