### ISSUE TITLE
Folia Support

### ISSUE THREAD

**Issue by TenkyuChimata** [Zrips/Residence#1021]
Hi,
Folia is a new project of PaperMC ( https://github.com/PaperMC/Folia/ ), which supports regionised multithreading.
Can u consider adding support for it?

**Comment by cgw2023** [comment]
> 

is unstable
res tp may cause region problem and players cannot move, server need to restart

**Comment by Zrips** [comment]
a10564badcad3c61633f9aee8db84ba97fd790f3
