### ISSUE TITLE
ResidenceFlagCheckEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#1023]
Hi, today the console started spamming me with this https://pastebin.com/TQn6VcX9. I don't know if this is something you can influence, or if I have to send it to slimefun. Purpur 1.19.3, cmilib 1.2.5.2, res 5.1.1.1, slimefun 1050, networks 46

**Comment by Zrips** [comment]
Should be addressed with next version
