### ISSUE TITLE
[Enhancement] Disable bad effects flag

### ISSUE THREAD

**Issue by menkisa** [Zrips/Residence#1024]
Hello,

We and a lot of server owners are facing a problem with Residences and Slimefun all together. The Problem is that there are some vanilla items in the main Slimefun mod, which give the player a lot of bad effects like: wither, blindness, poison, nausea and etc.  while holding them in the inventory and the only way to remove those effects is to wear special suit (Hazmat Suit) so that he won't be affected.
The problem here is that exactly in the place, where the players should be safe from any damage/effects is the **residence**, but there is currently no way to remove/disable all these effects while in residence. This causes many players to abuse in a way to throw this radiation items in players who are for example AFK in the residence and causing them to die. Currently, you could only set 'damage' flag to false by default in residence to prevent players dying from other entities, but the bad effects are still affecting you..

Hopefully there is a proper solution for that, if possible to have new flag specially for 'badeffects' would be a great implementation.
Thanks in advance!

Kind Regards!

**Comment by Zrips** [comment]
Will add SafeZone flag which will remove negative potion effects on defined interval
