### ISSUE TITLE
Shopboard Creation

### ISSUE THREAD

**Issue by bananababoo** [Zrips/Residence#1027]
When creating a shopboard with the command /resadmin shop createboard 1 
I get the error message "left click with selection tool top left sign and then right click bottom right"
I have already selected the region (my selection tool is a golden shovel)
![image](https://user-images.githubusercontent.com/48812049/236956410-86824384-b930-408c-8f3a-ba817b5f3ca7.png)

**Comment by Zrips** [comment]
a29ab1533911b9aa9d6ffdd4794813e69dc42bf4
