### ISSUE TITLE
Compile error: missing com.bekvon.bukkit.residence.towns.Town

### ISSUE THREAD

**Issue by shikendon** [Zrips/Residence#103]
Hi, I'm trying to compile the Residence plugin from source code.

**Here's my steps**:

1. `git clone https://github.com/Zrips/Residence.git`

2. Modify `build.xml`

    change
    ```
    <get src="http://dl.bukkit.org/latest-dev/bukkit.jar" dest="lib/Bukkit.jar" />
    ```
    to
    ```
    <get src="https://cdn.getbukkit.org/spigot/spigot-1.12.2.jar" dest="lib/Bukkit.jar" />
    ```
3. Download `dynmap-2.5.jar`, `Kingdoms-13.0.9.jar`, `LWC-4.4.0.jar` and `worldguard-6.2.1.jar` to `lib` folder

4. Execute `ant`

But I still got `error: package com.bekvon.bukkit.residence.towns does not exist`

```
compile:
     [echo] Compiling
    [javac] Compiling 205 source files to /usr/share/minecraft/Residence/build
    [javac] /usr/share/minecraft/Residence/src/com/bekvon/bukkit/residence/protection/ClaimedResidence.java:29: error: package com.bekvon.bukkit.residence.towns does not exist
    [javac] import com.bekvon.bukkit.residence.towns.Town;
```

Full error messages: https://pastebin.com/raw/ET316n1w

Is there should be have a `Town.java` exists in `src/com/bekvon/bukkit/residence/towns` folder?

or I missed something?

**Environment**:
* Linux 3.10.0-693.2.2.el7.x86_64
* CentOS Linux release 7.4.1708 (Core)
* Apache Ant(TM) version 1.9.2 compiled on June 10 2014

**Associated issues**: #10 #100

**Comment by Zrips** [comment]
Just perform simple Export action as Ant and Maven are not fixed currently and they will not work.
