### ISSUE TITLE
Residence enter/leave messages disappeared from file.

### ISSUE THREAD

**Issue by kamil445** [Zrips/Residence#1030]
Hi,

This is duplicate of these issues https://github.com/Zrips/Residence/issues/1007 and https://github.com/Zrips/Residence/issues/1010

I'm using version 5.0.3.0 which doesn't have this issue, saved residence file is in attachment:
[res_survival.zip](https://github.com/Zrips/Residence/files/11485708/res_survival.zip)

When i upgraded to latest version 5.1.1.2, enter and leave messages disappeared from file. When i manually re-added missing enter/leave messages, i got this error at server startup:

"org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1"

Looks like UTF-8 characters (Polish special characters like ąćśćłóżźę) aren't allowed anymore ?

**Comment by Zrips** [comment]
11789366886172ffe0dfc8badcd056f3806cf7be
UTF-8 supports more or less all characters and should supports Polish ones without any issues. 
This should fix your issue with enter/leave messages, for your error message, could you provide entire error log? And maybe, if possible give some idea of what it tried to save as this should not be happening in normal situations. 
Make a new ticket with this information.
