### ISSUE TITLE
[Feature request] Permissions to use bone meal and snuff out a candle

### ISSUE THREAD

**Issue by MagmaBlock** [Zrips/Residence#1035]
small / big dripleaf always grow when player using bone meal
Any player can use bone meal to ripen small / big dripleaf and cannot be controlled by permissions
Extinguishing the candle cannot be controlled too

Tested in the latest version 5.1.1.3

**Comment by welove69** [comment]
Agree

**Comment by Zrips** [comment]
b735a42d1d556c54c7bcd320507ce106625a7825
