### ISSUE TITLE
serious issue about res expand

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#1039]
The players does not need to pay any money when using the command /res expand if the size of the residence is very large(the total worth of the residence is shown as 2.147483647E7).
After the residence is expanded, no moeny is charged.
Issue happens.

Before the total worth of the residence is shown as 2.147483647E7, the money is charged when the players use the command /res expand.
No any issue happens.

The issue happens only when the total worth of the residence is shown as 2.147483647E7.
I think the command /res contract should have the same issue if the selling worth is 2.147483647E7.

Residence 5.1.1.3
CMILib 1.2.5.5
CMI 9.5.1.3

**Comment by siulung201314** [comment]
![image](https://github.com/Zrips/Residence/assets/83176041/5b066e7a-0796-4b6c-b33a-5ba92185547a)
Using /res expand if the total worth of the residence is not shown as 2.147483647E7. Money is charged.

![image](https://github.com/Zrips/Residence/assets/83176041/5dadf7e2-8efd-449f-b901-29d399b40393)
Using /res expand if the total worth of the residence is shown as 2.147483647E7. No money is charged. The balance is the same.

**Comment by Zrips** [comment]
1e40dc86115ba403806b1c9d798094037143a047
This will resolve your issue.
