### ISSUE TITLE
Deleted residence - bug

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#104]
Hello, the player has deleted his "Mudla2" residence and is still in the "/res list Mudla"
http://prntscr.com/gr3sek (red text in translation: Invalid residence...) lasted version http://prntscr.com/gr3t2f

**Comment by aaa8881** [comment]
I have this bug. For more information for developer, 
Residence actually get removed in save file, however, it is still seem to be remained in-game; hence, it can be shown by /res list (username) . However, ofc it actually doesn't exist, so there is no protection remained, nor anyone can tp to that residence. It gets fixed when server restarts.

**Comment by aaa8881** [comment]
Also, it counts as actual residence count. Hence, if player is restricted to make 1 residence - if someone makes residence - delete - and try to remake - it won't work. Idk if it can help you(dev) but still a thing

**Comment by 100petr** [comment]
Fixed in update, thanks.
