### ISSUE TITLE
Some commands does not work

### ISSUE THREAD

**Issue by Sk0ky** [Zrips/Residence#1044]
/res ? does not show any help, res check, res auto does not select whole structure ( it doesnt matter that much, its always better to select it manually ), actually almost every command doesnt work except cost, create and remove.

**Comment by Sk0ky** [comment]
> Without any information hard to say whats going on here. Server version? Do you have latest CMILib plugin? Any errors in console?

Im playing on 1.19.4 and tried to make new server with just resudence and CMILib plugins and its still same

**Comment by Zrips** [comment]
Any errors during startup?

**Comment by Sk0ky** [comment]
[latest.log](https://github.com/Zrips/Residence/files/11759661/latest.log)
[2023-06-15-18.log](https://github.com/Zrips/Residence/files/11759663/2023-06-15-18.log)
 The latest log is from 1.19.4 server without any other plugins and second one is from 1.20 server with eco plugins

**Comment by Zrips** [comment]
This is more than weird. Are you using clean client or some modified one?

**Comment by Sk0ky** [comment]
Im running it through crafty controller but all it does is that it starts server file on my pc/server and I can control it with web gui

**Comment by Zrips** [comment]
Your second log doesn't even report Residence plugin in startup logs besides 3rd party plugin SimpleClansResidence

**Comment by Sk0ky** [comment]
Wait Im gonna try remove the plugins, restart the server, add them again and start it

**Comment by Sk0ky** [comment]
Ok it actually started working as it should for some reason, I dont know what I did. I was removing the plugin and restarting the server few times and adding it again

**Comment by Sk0ky** [comment]
Now I have different problem tho
I cant access the purchased plugin on spigot forum, it shows I need to purchase it again.
![image](https://github.com/Zrips/Residence/assets/66485239/5001cda0-ec22-4c50-9900-f3e4ef095094)
