### ISSUE TITLE
1.20.1 Signage cannot be protected Other players can right-click to edit the sign

### ISSUE THREAD

**Issue by welove69** [Zrips/Residence#1046]
1.20.1
Signage cannot be protected
Other players can right-click to edit the sign

**Comment by mxco** [comment]
There is probably a mismatch between versions. The version was changed to 5.1.1.3 not until commit 264667b632ad90762c34d691e7db8281b5991b17, but on the spigot page it was apparently released on 5/25/2023. Weird.

**Comment by Zrips** [comment]
264667b632ad90762c34d691e7db8281b5991b17
This will be fixed with next official release, quite likely today.
