### ISSUE TITLE
When remove land, bank money will not go back owner bal

### ISSUE THREAD

**Issue by TimmyYue** [Zrips/Residence#1048]
just like title

**Comment by Zrips** [comment]
c98483b9166a0822c76787cf2dd4ab28f6e5450f

**Comment by TimmyYue** [comment]
Where can I get file after your change code?
And I have another problem, land owners set build false,
But why let land owner can’t build too?

**Comment by Zrips** [comment]
Updated version will be posted later today, most likely. Land owners should be able to build in their own land, worse case scenario they can add build flag for themselves only with **/res pset Zrips build true** while standing inside residence

**Comment by TimmyYue** [comment]
Can’t default land owner allow all permission in his lands
