### ISSUE TITLE
Residence 5.1.2.0 Disallows Other Plugin Sign Interaction

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#1051]
This whole sign business seems to be a bit of a mess, and I feel for you there.

Players are no longer able to use (specifically in our case, although I'm guessing it would affect most 3rd-party sign interactions) ChestShop signs to purchase items from other players in a residence in which the "customer" does not have build permissions -- they only get the typical Residence "You don't have build permissions here" error when attempting to purchase, nothing in console.

CMI IC signs are a mixed bag - the actions are performed, both for IC and the [Elevator] signs but Residence still sends the "no build perms" error.

Using Residence 5.1.2.0
CMI 9.6.0.4
CMILib 1.3.0.3
ChestShop b386 
on git-Paper-43 (MC: 1.20.1)

Thanks!

**Comment by mercurialmusic** [comment]
I know this is an ongoing thing but still having the issue with Residence 5.1.2.0 and CMILib1.3.1.2 on git-Paper-65 (MC: 1.20.1).

**Comment by Zrips** [comment]
New version is out, should be resolved now. Sorry for inconvenience. This native sign handling by servers causing me headaches... Still waiting for appropriate event from Spigot side so that we can handle it more properly. But it should be better now, sign use will be under use flag and not under place/build.

**Comment by welove69** [comment]
> 新版本已经出来了，现在应该解决。很抱歉给您带来不便。服务器处理的这种本机标志让我头疼......仍在等待 Spigot 方面的适当事件，以便我们可以更正确地处理它。但现在应该更好，标志使用将在使用标志下，而不是在放置/建造下。

Maybe you can try to refer to WorldGuard's protection method for signs, and only detect permissions when saving text?
