### ISSUE TITLE
[Critical] New residence teleport error

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [Zrips/Residence#1058]
After updating to the latest version, if player created a new residence using /res create and issued /res tp XXX, he will be teleported to world's spawn point.

No error log

Version: 5.1.2.0
Server: Paper 1.20.1

**Comment by Aira-Sakuranomiya** [comment]
![QQ截图20230715152058](https://github.com/Zrips/Residence/assets/45261195/8521140f-934e-41f9-927c-8db51d083764)

It seems that new residences are created with
`TPLoc: 0.0:64.0:0.0:0.0:0.0`

**Comment by Aira-Sakuranomiya** [comment]
This issue occurs when the second residence is created after restarting the server

**Comment by Zrips** [comment]
This in general could happen if we can't determine valid residence outside location which then defaults to one of the main world spawn points.
Can you give more information about those residences? Like their location, size and what's inside of them? As we are picking center point of residence to check for valid location if res tp isint set for it. And if that fails we are checking for free outside location by checking residence borders and if that fails then we are defaulting to world spawn location. Will change last behavior to use residence world spawn point as it was using wrong world for this task.

**Comment by Aira-Sakuranomiya** [comment]
I recorded the following video showing how I created the residence.
https://youtu.be/LbDTlXMUZn8

Is there something like debug mode? No errors reported in the console.

**Comment by Aira-Sakuranomiya** [comment]
Here's config.yml:
https://gist.github.com/Aira-Sakuranomiya/92d60fce8d74ad43de5bf5ec0e698527

**Comment by Zrips** [comment]
Yea, residence like this would teleport you to back to spawn in case we can't determine valid point. Will change tp behavior and will avoid teleporting players to spawn location when that happens and instead will inform about invalid location.
bfb2032d9a845f3b039e9bce25bfb0d4bc017602

**Comment by Aira-Sakuranomiya** [comment]
but I want to know why it is invalid

**Comment by Aira-Sakuranomiya** [comment]
Now I create a new residence and teleport to it and the plugin will say Invalid Location

**Comment by Aira-Sakuranomiya** [comment]
Can we let Residence log why the location cannot be determined?
