### ISSUE TITLE
OP cannot break or edit sign in players residence

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#1068]
OP cannot break or edit sign in players residences if the build flag is false.
OP should have the permission to ignore the build flag to break or edit sign in players' residences.
Residence 5.1.2.0
CMILib 1.3.1.2
Purpur-2011 (MC 1.20.1)

**Comment by welove69** [comment]
Residence 5.1.2.1,Some changes were made, but there was still chaos
OP cannot break or edit sign in players residences if the use flag is false.

**Comment by Zrips** [comment]
fe3d5d335a2040471bc68e1ff9bbce4461759e01
