### ISSUE TITLE
Residence plugin cause lag

### ISSUE THREAD

**Issue by chichungchen95** [Zrips/Residence#1072]
This plugin is causing my server to be lagging for a long time and I want to know how to fix it Here is what

Here is the screenshot data from Spark below.
![Screenshot_20230720_043128_Chrome](https://github.com/Zrips/Residence/assets/86265505/57939a2d-99bf-47e0-94b7-8e4ad0a172a4)

Sometimes this plugin suddenly works fine, but other times it starts lagging. I have tried increasing the border size and disabling the select feature, but it seems to be the same situation.

**Comment by Zrips** [comment]
Disable Global.AutoMobRemoval.Use or increase its update rate. As it was mentioned in config file this is relatively heavy task to be performed especially on bigger servers with more players running around. Will do some optimizations but you should generally avoid this feature if you have high online numbers which on itself will increase amount of residences plugin checks with each cycle.
3f59d199713a396f475b9532d1c97a09811c28c7
