### ISSUE TITLE
Can BungeCore support be added to Residence?

### ISSUE THREAD

**Issue by lipind** [Zrips/Residence#1074]
I am trying to run a large proxy server and have installed Residence on multiple servers. 
I hope players can tp to the territory on another server.
Block domains with the same name on the network when creating servers

So can you add MySQL support and cross server transfer of residences？
Believe me, this is a great feature.

**Comment by Zrips** [comment]
Feature might be great, but its implementation would be pain in a** to add and manage all cases and all possible abuse instances. This is hardly will be added any time soon due to its complexity and quite narrow use case.
