### ISSUE TITLE
Create a separate flag for signs

### ISSUE THREAD

**Issue by welove69** [Zrips/Residence#1075]
Residence, the implementation of signs in 1.20 worked terribly
Perhaps a separate flag could be created for signs,Only enabled in versions above 1.20
Signs should not be fully integrated into the use flag
https://github.com/Zrips/Residence/issues/1071
https://github.com/Zrips/Residence/issues/1064
https://github.com/Zrips/Residence/issues/1062
https://github.com/Zrips/Residence/issues/1068
Maybe try to refer to WorldGuard's protection method for signs, and only detect permissions when saving text?

**Comment by addpromax** [comment]
Yes I think this is terrable

**Comment by Zrips** [comment]
fe3d5d335a2040471bc68e1ff9bbce4461759e01
