### ISSUE TITLE
Couldn't stop players place boat in residence

### ISSUE THREAD

**Issue by xyfwdy** [Zrips/Residence#1081]

**Comment by Zrips** [comment]
Boat placement is based on build flag access, if player can build inside residence then he should be able to spawn in boats. This could be different story if some other plugin overrides spawning in boat and forces it in, but this should not happen with vanilla boat spawning.

**Comment by xyfwdy** [comment]
> Boat placement is based on build flag access, if player can build inside residence then he should be able to spawn in boats. This could be different story if some other plugin overrides spawning in boat and forces it in, but this should not happen with vanilla boat spawning.

I create a test server 
This server is running Paper version git-Paper-111 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 408a905)
You are running the latest version
![8d09dd60aeaddaecdf5f4ba199ae06bb](https://github.com/Zrips/Residence/assets/69817107/e1f4188d-bef8-4409-9091-b0a2b145ead9)

run command : /res pset xxx2 RanRan build false
but player RanRan still can place boat in residence
![image](https://github.com/Zrips/Residence/assets/69817107/f99c7fe8-f8a4-4693-be39-d4d5193c4307)
