### ISSUE TITLE
Residence enter/leave TitleBar message placeholder %subtitle% or \n does not work.

### ISSUE THREAD

**Issue by Angelo753** [Zrips/Residence#1082]
Residence version: 5.1.2.1
Server version: git-Purpur-2015 (MC: 1.20.1)
![image](https://github.com/Zrips/Residence/assets/44684210/59c7cddc-6cff-48bd-b224-5989fc497752)
![image](https://github.com/Zrips/Residence/assets/44684210/cd9b1c65-3b7f-4b86-a695-74cf1090002b)

**Comment by Angelo753** [comment]
Well, it works with \\n
#2cfdf9a

**Comment by Zrips** [comment]
36a8f245b19c310000b099da1e8bb4806e337b4d
