### ISSUE TITLE
Residence -> enter / leave message remove isnt working on czech localization

### ISSUE THREAD

**Issue by pjindras** [Zrips/Residence#1085]
Hello,
I am using lastest version of residence, minecraft 1.20.1.

When I set in some residence /res message name enter remove than it removes messages, but after some time / after server restart the messages are back again.

Could you please check it, this is issue a longer time, I posted some topic about it some time ago.

Thank you :)

**Comment by Zrips** [comment]
0ed8d606dfd54836761c5378df9e463ae4428762
