### ISSUE TITLE
Residence 5.1.2.2 Startup Error/Plugin Can't Enable

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#1086]
Getting this error on all servers I attempted to update to Residence 5.1.2.2:
https://gist.github.com/mercurialmusic/d38162ff0e418db4b0febebcb8c0088f
https://gist.github.com/mercurialmusic/d401eefba5c533b4e86d87a68c8a0bb2
Plugin disables and server goes into a restart loop. 

Using Residence 5.1.2.2 with CMILib 1.4.0.5 on git-Paper-116 (MC: 1.20.1)
Downgraded to Residence 5.1.2.1 (still on CMILib 1.4.0.5) without issue.

**Comment by sekaom** [comment]
I have same problem。https://gist.github.com/sekaom/c83d34dde5ff42243de5f69ca2db1cb9
Using CMILib 1.4.0.4 with Residence 5.1.2.2 on git-Paper-100(1.20.1)
Residence 5.1.2.1 haven't this problem

**Comment by sekaom** [comment]
I have same problem,but I'm using CMILib 1.4.0.4
https://gist.github.com/sekaom/1d995323834ddb620e3d868f801a61a2
After I upgrade CMILib to 1.4.0.5,this problem disappear.
But log still have an Error: https://gist.github.com/sekaom/4662d9ab4331741a4a21970dca865e54
Now ,I'm using Residence 5.1.2.2 with CMILib 1.4.0.5
My server version: git-paper-100(1.20.1)

**Comment by Zrips** [comment]
@mercurialmusic 
70ba899949c2007e626950c2c5f9039241e5457f Will resolve your issue. Will post new version today with a fix. Sorry for inconvenience.

**Comment by Zrips** [comment]
@sekaom 
As update patch notes stated (Who reads those?) you will need to update CMILib and your server file to the latest versions for this to work properly as it should. Updating paper to the latest build should resolve your error message.
