### ISSUE TITLE
Liquid got removed when removing residence

### ISSUE THREAD

**Issue by WongIong** [Zrips/Residence#1091]
As title.
Lava and water will get removed when player remove their region, this would somehow breaks their machines.

**Comment by Zrips** [comment]
Check config file for lava water removal on residence removal, you might have enabled this option and now each time residence gets removes all those blocks will be too. You can set specific laval/water level after which this should be removed, its by default above 63 level. Mainly to prevents from players placing bunch of those blocks and then removing residence, in your case might not be needed and you can safely disable it.

**Comment by WongIong** [comment]
Is this a new feature?
