### ISSUE TITLE
cant create Residence

### ISSUE THREAD

**Issue by jeff910906** [Zrips/Residence#1094]
i cant create 
its always show select two points first before using this command
and no erroe in consol

**Comment by Zrips** [comment]
To create residence you will need to select 2 points before hand. This can be done over multiple methods. Original is to select selection tool which by default should be wooden hoe, you can check which tool you need to use by using **/res tool** command. Then left and right click blocks of lowest and highest corners. Alternatively you can use **/res select auto** which start automatic selection and you can just run around your base and expand selection to exact one you want without selecting anything manually. 
Simplest way would be to use **/res auto 10** or any range you want, which will expand selection area around you and create residence by using your players name as residence name, you can always rename residence later on, but this is the simplest way.
