### ISSUE TITLE
How does ResidenceCreationEvent determine whether it is successful?

### ISSUE THREAD

**Issue by SheerYin** [Zrips/Residence#1097]
If the player does not have enough money, or the Residence creation fails due to other reasons, this event will still return ClaimedResidence
Is there a better way?

Currently my method is:
Bukkit.getScheduler().runTaskLaterAsynchronously(Main.getInstance(), () -> {
             if (!Residence.getInstance().getResidenceManager().getResidences().containsKey(residenceName)) {
                 return;
             }
         }, 3L);

**Comment by Zrips** [comment]
ResidenceCreationEvent gets fired before actual residence creation, aka recording it inside plugin and after all prechecks, like a check of balance or size limitations will be done before this event is fired.
All this is done in sync, so calling async and checking for residence record should return recorded new residence if it was actually recorded and not canceled.
And you can use **Residence.getInstance().getResidenceManager().getByName(residenceName)** which is more correct way in getting residence by its name. And just FYI residences are recorded in lowercase format in residences map, so you are most likely trying to get residence by using its capitalized name which will not be recognized. Just use provided method which will return most accurate results with less work from your side.
