### ISSUE TITLE
BUG Flag nomobs is not working

### ISSUE THREAD

**Issue by pjindras** [Zrips/Residence#1098]
Hello, if I use flag nomobs, monsters still can walk into the residence.
I am using Purpur 1.20.1

Residence version: Residence5.1.2.2

**Comment by Zrips** [comment]
Mobs gets removed from residences players are currently in and in specific intervals to lower this check's load on server much as possible. If mobs remain inside residence after few seconds (check config file for auto removal interval) then let me know. Just need to know if you wanted to say that mobs can still enter or those are not removed in general. Closing ticket for now.
