### ISSUE TITLE
glow item frame is not checked for hangingbreakevent in residence

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#1099]
Only normal item frame has been checked for HangingBreakEvent event.
 However, the glow item frame has not been checked yet.
 
    @EventHandler(priority=EventPriority.LOWEST, ignoreCancelled=true)
    public void onHangingBreakEvent(HangingBreakEvent hangingBreakEvent) {
        Hanging hanging = hangingBreakEvent.getEntity();
        if (hanging == null) {
            return;
        }
        if (this.plugin.isDisabledWorldListener(hanging.getWorld())) {
            return;
        }
        if (!hangingBreakEvent.getEntity().getType().equals(EntityType.ITEM_FRAME)) {
            return;
        }
        if (!hangingBreakEvent.getCause().equals(HangingBreakEvent.RemoveCause.PHYSICS)) {
            return;
        }
        FlagPermissions flagPermissions = this.plugin.getPermsByLoc(hanging.getLocation());
        if (!flagPermissions.has(Flags.destroy, flagPermissions.has(Flags.build, true))) {
            hangingBreakEvent.setCancelled(true);

**Comment by Zrips** [comment]
bd826bc7a9326e1ce320abbf03627509e32f1bcd
