### ISSUE TITLE
Prevent residence creation inside worldguard region

### ISSUE THREAD

**Issue by prozhong** [Zrips/Residence#110]
https://github.com/Zrips/Residence/blob/master/src/com/bekvon/bukkit/residence/protection/ClaimedResidence.java#L430

https://github.com/Zrips/Residence/blob/master/src/com/bekvon/bukkit/residence/protection/ClaimedResidence.java#L571

It seems that return true doesn't prevent creation

**Comment by Zrips** [comment]
We feel so silly when you make mistakes like this...
Thanks for reporting, will be fixed with next build
