### ISSUE TITLE
Latest Residence cannot use Random Teleport

### ISSUE THREAD

**Issue by charassss** [Zrips/Residence#1104]
How to reproduce:
1. Use Residence 5.1.3.0 and CMILib 1.4.4.1
2. Use default config,yml
3. /res rt and Sorry & wait

**Comment by charassss** [comment]
paper-1.20.1 build196

**Comment by Zrips** [comment]
Double check your config file at RandomTeleportation section to be sure that set boundaries are inside your world border and is actually enabled. If it is then I would need more information on what's going on when performing /res rt, does it output any message?

**Comment by charassss** [comment]
> Double check your config file at RandomTeleportation section to be sure that set boundaries are inside your world border and is actually enabled. If it is then I would need more information on what's going on when performing /res rt, does it output any message?

```config
RandomTeleportation:
    Worlds:
      # World name to use this feature. Add annother one with appropriate name to enable random teleportation
      world:
        Enabled: true
        # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
        MaxCoord: 1000
        # If maxcoord set to 1000 and mincoord to 500, then player can be teleported between -1000 to -500 and 500 to 1000 coordinates
        MinCoord: 500
        CenterX: 0
        CenterZ: 0
```

```log
[20:55:58 INFO]: Chara_SS issued server command: /res rt
```

```properties
max-world-size=29999984
```

Paper 1.20.2 - 240 now

**Comment by charassss** [comment]
![图片](https://github.com/Zrips/Residence/assets/85441099/d11c82fc-f685-40cc-8c41-93c378182543)

Always like this...

**Comment by Zrips** [comment]
78fba06462390c6c428fe41cd98f20378668859b
