### ISSUE TITLE
Flag nomobs is not working

### ISSUE THREAD

**Issue by pjindras** [Zrips/Residence#1105]
Hello, flag nomobs is not working, mobs can still enter my residence.
I have Purpur 1.20.

Plugin Version 5.1.3.0

**Comment by Zrips** [comment]
Mobs will be able to enter your residence, we are not checking on every mob movement action to avoid heavy loads on servers, we are only checking residences players are in at the moment and checking for nomobs flag, if that one exists then we are checking residence for any mobs inside of it in case we need to remove it and this is done at specific interval.
You might want to check Global.AutoMobRemoval.Interval option in config file, this will define how often we will rescan residences.
