### ISSUE TITLE
Disable commands outside residences

### ISSUE THREAD

**Issue by Floodo** [Zrips/Residence#1114]
Hello there :) Because I couldn't find any link to Discord, I'm writing here a question. Is it possible to disable specific command outside the residences but also when you are on some specific residence, you could use that command? For example around specific world you can't use command "/shop" but like in some specific residence you could use it? I know there already is  "/res command <allow/block/list> – Manages allowed or blocked commands in residence " for configurate command INSIDE the residence, but could it also be like configurable OUTSIDE of the residence ? Like maybe only owner (admin) could change it (since it is setting per world), but I don't want to use WorldGuard plugin. Thanks for help. :)

**Comment by Zrips** [comment]
f551af94dc92eec1cfe3fb5f569f517e07382525
With next update you will be able to set global flag as `command: false` in flags.yml file which will disable all command usage outside residence with additional option to set which commands you want to allow/block at the end of flags.yml file. You can make it as inherited flags so it will block inside residences by default unless residence contains command: false flag set and that command being enabled for usage which should give you exactly what you wanted.

**Comment by Floodo** [comment]
Aawesome! :)) .. But still I need little help :( .... I added "command: false" into Global flags (in file flags.yml), also in CommandLimits I set true for Inherit and in BlackList I put "- shop". In game I type in Shop residence "/resadmin command allow shop" and still I can't use "/shop" in that residence (also it is disabled for other residences and rest of world - but this is intended) but when I type "/resadmin command list" it says that "/shop" is allowed here. Do you know what I'm doing wrong or the issue is in plugin ? Thank you :)
