### ISSUE TITLE
/res auto - Not creating a residence up to the player group's limit

### ISSUE THREAD

**Issue by OnlyMatty** [Zrips/Residence#1117]
Hello, I have encountered an issue where players with group "Sponzor" which has max. residence size 150x150 cannot create residence up to their max size via /res auto.
This also happens with other residence groups. It creates residence half their maximum size.

Groups.yml: https://paste.techscode.com/utuquravehiyepu.yaml

Flags.yml: https://paste.techscode.com/ivurinevozumoxi.yaml

Config.yml: https://paste.techscode.com/abuwukecupeyowu.yaml

Server version: 1.20.1
Plugin version: 5.1.4.0
Server type: Paper

**Comment by Zrips** [comment]
@OnlyMatty 
Small bug, you can either increase Max at line 86 or wait until next update which will properly ignore that set limit when you have Size.Enabled at false state
90ca8e138db5aecc855519095e228461a5778e84
