### ISSUE TITLE
autocleanup action ownership transfer does not work

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#1119]
The newly implemented function https://github.com/Zrips/Residence/commit/0fee7784492e74e68e53e18f2787f241def1f7ad does not work. Residences are still deleted and not transferred.

![image](https://github.com/Zrips/Residence/assets/29830635/e51fc59f-e6b0-489d-a092-faa64c7ea57d)

**Comment by Zrips** [comment]
f55ee51085c352d8f62abfbf8b8ad7d1ee52d88d
