### ISSUE TITLE
Critical GUI Duplication Glitch

### ISSUE THREAD

**Issue by Blackdigits** [Zrips/Residence#112]
Residence Version:
[10/16/2017 18:13:58] Residence 4.7.2.4 1386

Spigot Version:
1.12.2

Steps of Recreating the problem:
Have a residence with fly flag
Turn fly flag on
fly up
turn fly flag off
fall down
open inventory
close inventory
and you'll get a pig egg for the animal flag inside your inventory

**Comment by Zrips** [comment]
Thanks for reporting, will be fixed today.
