### ISSUE TITLE
Regenerate

### ISSUE THREAD

**Issue by ttc111** [Zrips/Residence#1122]
AutoCleanUp:
    # HIGHLY EXPERIMENTAL residence cleaning on server startup if player is offline for x days.
    # Players can bypass this with residence.cleanbypass permission node
    Use: true
    # For how long player should be offline to delete hes residence
    Days: 1
    # Do you want to regenerate old residence area
    # This requires world edit to be present
    Regenerate: true
    # Worlds to be included in check list
    Worlds:
    - world
    - world_nether
    - world_the_end
    # When enabled we will transfer residence to defined user instead of removing it
    # Defined user will be excluded from cleanup operation

I have enabled Regenerate: true, but plugin only deletes the claims and does not restore the terrain.

**Comment by Sh3r1ffCZ** [comment]
Same problem

**Comment by Sh3r1ffCZ** [comment]
> [e6ef198](https://github.com/Zrips/Residence/commit/e6ef19843196c848c65db416f69fc0e3d12e3fab)

I tried it with the latest version of "Residence5.1.4.1.jar" and still the same problem. Resks not regenerated and server crashed on power up. On my server 1.20.2, still not resolved.
