### ISSUE TITLE
1.20.3/1.20.4+  The Residence is unable to protect the Decorated Pot

### ISSUE THREAD

**Issue by BangXi** [Zrips/Residence#1128]
[Decorated Pot](https://minecraft.wiki/w/Decorated_Pot)
Now can store up to a single stack of items.
[Hoppers], [minecart with hoppers] and [droppers] can now insert and/or extract items from them.
[Comparators] can now read the number of items in them.
[Players] can interact with them and insert items into them.
Player interactions with them cause them to wobble and trigger a vibration frequency of 11.
They have no GUI, and need to be broken to retrieve their content by players.
Now can be smashed by projectiles, which cause them to shatter and drop their contents.
Now has new sounds for breaking, shattering and being stepped on.
Now can stack up to 64.
Now appears in the Redstone tab of the Creative inventory.
Now, when blockstate set to , decorated pots will always shatter when broken.crackedtrue
Now can utilize loot tables and will read from the tag key.LootTable

**Comment by BangXi** [comment]
Decorated Pot calls EntityChangeBlockEvent, which feels good.
Residence should prevent others from right-clicking on Decorated to put in items.
Can related events be added?Wait for your free time.
@Zrips

**Comment by Zrips** [comment]
124e135edfd43cd1e999ba54ca3415c3cbb6fd1f

**Comment by BangXi** [comment]
> [124e135](https://github.com/Zrips/Residence/commit/124e135edfd43cd1e999ba54ca3415c3cbb6fd1f)

Decorated Pot Now can be smashed by projectiles.
Can Residence check the corresponding permissions?
now projectiles smashed Decorated Pot calls EntityChangeBlockEvent

**Comment by Zrips** [comment]
75e58548489884ffbee09e5353d25fe0153e8d8b
