### ISSUE TITLE
/res select x y z Is not working for me

### ISSUE THREAD

**Issue by A1yshia** [Zrips/Residence#1129]
Hello.
I have tried giving players multiple commands and this issue never seems to resolve. I as admin can do /res select, but ordinary players in my server cannot and its getting exhausting trying to figure out why it isn't working. Any help would be much appreciated.

The following commands are set to true:
residence.select
residence.select.auto
residence.select.size
residence.select.xyz
residence.selectxyz
residence.command.allow
residence.command.select
residence.command.select.size
residence.command.selectxyz

**Comment by Zrips** [comment]
Check if groups.yml has SelectCommandAccess set to true
Other than this, not having residence.create permission node would prevent its usage too
