### ISSUE TITLE
Residence save file gets deleted

### ISSUE THREAD

**Issue by ZeaLBG** [Zrips/Residence#113]
https://www.spigotmc.org/threads/residence-1-7-10-up-to-1-12-paid.88667/page-132#post-2757867

**Comment by Zrips** [comment]
Can i get your save file for testing? as this can be related with some strange data being saved into file and failing without reporting it. Need environment where i could reproduce issue.

**Comment by ZeaLBG** [comment]
Here is the last backup that I have. Long story short we updated and restarted our server and we updated the residence to the latest version. After the problem happened 3-4 times we decided to downgrade to the residence version we used before the update (4.7.0.5) and for now (2 days) everything seems fine. Here is a download link to the file https://mega.nz/#!Y2QBTJZT!Rrl7rTI0Y_LykJg5y8eETEh3I1unKkjq6KWZMwx5vWQ

**Comment by Zrips** [comment]
Is this issue happens after some time of usage or this can be reproduced straight after starting server and restarting it?

**Comment by ZeaLBG** [comment]
It happens randomly I guess... It doesnt happen after every restart. We have 2 restarts every day - at 05:00 and at 19:00. It happened 4-5 times for 1 week only at the restart at 05:00.

**Comment by ZeaLBG** [comment]
Happened with the 4.7.0.5 version too.. Still have no idea how its happening..

**Comment by Zrips** [comment]
Is this still a problem?

**Comment by ZeaLBG** [comment]
Changed to residence reloaded a while ago, because Im on 1.8. The problem kept occurring till I changed.
