### ISSUE TITLE
Residence [purpur 1.20.4] 5.1.4.1 (huge bug)

### ISSUE THREAD

**Issue by LostMVP1** [Zrips/Residence#1131]
residence does not protect itemframes
you can rotate them, take items from them and even destroy them.
Pvp is active all the time in residence, even if you turn it off trough flags or config.
Thats all, hope you fix that

**Comment by BangXi** [comment]
Cannot be reproduced.

**Comment by LostMVP1** [comment]
yes, container is false, because its not my residence, it even says: you dont have container permission in chat, but you still can move the item around...

**Comment by LostMVP1** [comment]
i found out, that residence does not protect any entity (itemframes,paintings,players,mobs,armorstands)

**Comment by Zrips** [comment]
@LostMVP1 
You will need to look into possible issue with 3rd party plugin, or you can try resetting Residence config files to default setup in case there are some issues with misconfiguration. But in general entities are protected across the board and no one else seamingly reports same issue, so its isolated issue with your particular setup.
