### ISSUE TITLE
Problem with "nofly" flag

### ISSUE THREAD

**Issue by sakulmore** [Zrips/Residence#1132]
Hello, the "nofly" flag is not working properly. At least for me. When I have nofly allowed in my residence and I'm player without OP permissions, I can't still fly even when I have nofly allowed or disallowed. When I trying to fly, it will automatically teleport me down and in the chat I can see the message that "nofly" flag I have not allowed. I even tried set permission `residence.nofly.bypass` but it's still same.

So I can fly only when I'm OP.

I have setten all flags to disallowed except fly, nofalldamage and nofly (these I have on "allowed" state).

I tried older versions of the plugin and newer (of course latest too) and it's same on all versions.

**Comment by LostMVP1** [comment]
yea, it doesnt even protect itemframes
you can take items from them or even destroy them in other residences

**Comment by Zrips** [comment]
87b2a9363519937ba26b06869931d6fcb04be33a
