### ISSUE TITLE
Residence subzone

### ISSUE THREAD

**Issue by Fildaa0** [Zrips/Residence#1133]
Hello,

i would like to ask why the subzone i set move f to, either on nickname or using group (/resadmin gset ...), kicks me to world spawn instead of kicking me / moving me back to the front of the subzone.

This problem only affects subzones, residences work correctly.
I went through the config from top to bottom and couldn't find any mention of this.
Thanks in advance for your reply and advice.
Fildaa
![Screenshot_2](https://github.com/Zrips/Residence/assets/156532845/44960eab-1556-495f-a635-023f6d9bfb04)

**Comment by Zrips** [comment]
Thi can happen in case plugin can't find valid kick location as it checks at the edges of area which doesn't allow movement, and in case there is none player will be "kicked" to spawn point as a fail safe. Could you elaborate more on exact setup you have for that area? Might help out to improve this entire system
