### ISSUE TITLE
Residence after restart deletes

### ISSUE THREAD

**Issue by HadrCZSK12** [Zrips/Residence#1136]
Hello, when I restart server residences deletes after it. I create it in iris world gen, but I think theres no the problem.

**Comment by HadrCZSK12** [comment]
LMAO stupidest support I have ever met. I bought the plugin and dont get any support. LMAO SHITTY SUPPORT AF. Jestli chcete muzu to napsat i cesky

**Comment by yoder303** [comment]
Your problem statement is incomplete. Please provide complete steps to reproduce, including all details of the server

**Comment by HadrCZSK12** [comment]
Hello, my server is on 1.20. I have world generated with world Generator
named IRIS. When I create residence in VANILLA WORLD GEN the residence
after restart is still there. BUT when I create the residence in WORLD
GENERATED BY IRIS PLUGIN the residence is after restart deleted. Plugin of
Residence is 5.1.4.0. I dont know what to do. I use MyWorlds as multiworld
plugin.

st 24. 1. 2024 v 17:52 odesílatel Chris Yoder ***@***.***>
napsal:

**Comment by Zrips** [comment]
@HadrCZSK12 
Without providing any information about your issue its not really possible to provide any solution. You would need to test it out with generic worlds, in case there is issue with custom ones loading way after the fact which could possibly get ignored. 
Need server type and version, plugin version, and general information about your setup.

**Comment by HadrCZSK12** [comment]
Its Okay I found it. I think it was by old version of Residence plugin.
Because I had loadeveryworld: true and it doesnt work. But after I put new
jar it works fine now.

út 20. 2. 2024 v 13:32 odesílatel Zrips ***@***.***> napsal:
