### ISSUE TITLE
Command in residence won't work

### ISSUE THREAD

**Issue by Floodo** [Zrips/Residence#1138]
Aawesome! :)) .. But still I need little help :( .... I added "command: false" into Global flags (in file flags.yml), also in CommandLimits I set true for Inherit and in BlackList I put "- shop". In game I type in Shop residence "/resadmin command allow shop" and still I can't use "/shop" in that residence (also it is disabled for other residences and rest of world - but this is intended) but when I type "/resadmin command list" it says that "/shop" is allowed here. Do you know what I'm doing wrong or the issue is in plugin ? Thank you :)

EDIT: It works only if you change flag in GUI "/res set"   flag "command" to blocked. If you change it to allowed or not selected it won't work.....Maybe it should work on allowed option?

_Originally posted by @Floodo in https://github.com/Zrips/Residence/issues/1114#issuecomment-1918605345_

**Comment by Zrips** [comment]
297022034307b6dc3a046495e8748122bad39355
true that, there was incorrect flag check, not its properly asks for True state for command flag to allow blacklisted commands
