### ISSUE TITLE
fly sometimes not turning off

### ISSUE THREAD

**Issue by Blackdigits** [Zrips/Residence#114]
There's a single res (at least for now) in my world where if the owner set the fly flag to true, and fly out of the residence, he would still be flying, i've tried to set a worldguard fly flag to false but it still works

**Comment by arturek1666** [comment]
Same here for my players it happens when you have permission to set fly and on your are you will use /rtp somehow it allow that player to fly everywhere in my case.

**Comment by Zrips** [comment]
@arturek1666 
What flags does residence have set? And where exactly do they teleport to? Random location outside residence or into some another one?
