### ISSUE TITLE
Better permission check for /res create command or DisableCreating option for DisabledWorlds

### ISSUE THREAD

**Issue by Delanooootje** [Zrips/Residence#1141]
Residence version: 5.1.4.0
Luckperms version: 5.4.104

I set permissions "residence.command.create" and "residence.command.auto" for my default group in Luckperms to **false** in worlds "world_nether" and "world_the_end" because I want residences to be created only in normal world. I am **not** using DisabledWorlds option in config file because I still want to use /res tp command in those worlds. The problem is when player selects residence area in those "disabled" worlds and then teleports to normal world, he can run /res create command and it will create residence for him in "disabled" world because I think residence plugin is checking permissions just for player and not for area coords. Even better solution might be to add "DisableCreating" as another option in DisabledWorlds OR permission for selection tool (I thought "residence.select" is permission for selection tool but it did nothing when I set it to false)

**Comment by Zrips** [comment]
020b7e4d2eb159f39e61257803c331709fe45196
