### ISSUE TITLE
Inexplicable automatically creation of rensidence with difference suffixes

### ISSUE THREAD

**Issue by 1309896340** [Zrips/Residence#1145]
There's something wrong with the plugin. I use Residence 4.7.0.5 on minecraft 1.12.2, CatServer, a mixed server of mods and plugins. I created a residence named 'wind' with command `/res create wind`. Then it automatically generate several residence with the same name and different suffix, such as 'wind1' 'wind2' 'wind11' 'wind12' 'wind21' 'wind3'. I don't konw what's wrong with it.
![QVOYT9J10ZNACYS](https://github.com/Zrips/Residence/assets/17214930/163dd8c8-51e9-4e16-84aa-3c2e1b195231)

**Comment by Zrips** [comment]
Latest version of Residence is 5.1.4.1, you have extremely outdated one, more accurately one from 2017/07/07. Please update your plugin and try again.
