### ISSUE TITLE
residence flags not allowing clicking signs for tp

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Residence#115]
Hi @Zrips I've recently switched over to LuckPerms from PermissionsEx because of an issue where players who are not OP'd cannot click on a sign that teleports them to another world in the bungee network.  I'm using Bungee Server Signs and it is working, but putting a sign in a residence isn't allowing the players to click on it.  I've even added the player flags to have container, door, lever, build, use and anything else that would otherwise grant them permissions to click the sign.  Nothing appears to be working even in LuckPerms so that brought me back to Residence being the problem.

I walked outside of the residence and in fact I had to go further than 20 blocks for some reason and was only then allowed to place/break blocks.  I placed a server sign, added the commands to it and was able to teleport to another world when the sign is not in the residence.  

Is there something obvious that I'm missing from the permissions or flags?  The residence in question is at Spawn point and is a "Mansion" if that makes any difference.

I'm using: 
Waterfall build 62 (akin to BungeeCord Server) v1.12.2
Spigot 1.12.2 latest build
Residence 4.7.3.0
Java 1.8.0_152
LuckPerms 4.0.18

**Comment by smmmadden** [comment]
@Zrips any ideas?

**Comment by smmmadden** [comment]
@Zrips making a player an OP 1,2,3 or 4 grants them permission to click on the sign and get teleported.  Unfortunately, it gives them more than what I want them to have. 

- I updated the residence plugin to 4.7.3.1, Waterfall to build 63 and latest builds of Spigot.
- I checked with Benny for his plugin "BungeeSigns" and he says there is nothing in his plugin that requires the player to be an op.
- I've tried adding "trusted" to the player on the spawn residence but still nothing happens.  
- I turned on verbose for LuckPerms and every action I did is written to the console with the exception of 
right-clicking the sign.  It's like it is disabled completely.  Here is the permissions for the player in question.  https://pastebin.com/egPrP6t5

**Comment by Zrips** [comment]
Residence should not prevent right clicking if its not container even when residence has container false. Cant really reproduce issue you are having. Player successfully teleported to another server from residence by right clicking sign. 
Did you tested this with default config files and only residence bungeeSigns plugin installed?
What flags does residence have or this is for all of them? Is that residence on market for rent or sell? Any extra information would help out to find issue.
