### ISSUE TITLE
Suggestion: Support BigDoors

### ISSUE THREAD

**Issue by czHeso** [Zrips/Residence#1150]
Would it be possible to connect the Residence to support [BigDoors ](https://www.spigotmc.org/resources/big-doors.58669/)please?

![image](https://github.com/Zrips/Residence/assets/151180665/0257323c-3c37-472e-8bbd-b86dc6e74d4a)

**Comment by Zrips** [comment]
Not that familiar with this plugin. Can you elaborate more on actual issue with this plugin? What isint being support and what should be?

**Comment by czHeso** [comment]
In the plugin, each player has their own menu and environment for creating different doors, drawbridges, etc.

The problem is that a foreign player can also make this door in a foreign residence and thus damage it.

**Comment by Zrips** [comment]
6e42071da93179193b144d518c8eeb59be05739e
