### ISSUE TITLE
can't create residences with command /res auto

### ISSUE THREAD

**Issue by smscentras** [Zrips/Residence#1152]
in version 5.1.4.2 can't create residences with command /res auto: 
    You don't have enough money(but player have)
    Area size is not within your allowed limits.

**Comment by danieliustt** [comment]
But problem on ver: 5.1.4.2

**Comment by Zrips** [comment]
ef96fa1ce2d0a2d929d5faa05b16a85995b67cca

**Comment by Bambicek** [comment]
Same for me on ver: 5.1.4.2
