### ISSUE TITLE
Remove res_xxxx.yml file

### ISSUE THREAD

**Issue by iTzMatiasHD** [Zrips/Residence#116]
Hello,

I had problems with the last update, version 4.7.3.0, residences are deleted from the file res_xxxxx.yml

I don't know if this happens to other people, I ask for the quick solution. And Not, i don't have error in log.

Regards.

[Post on SpigotMC](https://www.spigotmc.org/threads/residence-1-7-10-up-to-1-12-paid.88667/page-133#post-2777350)

**Comment by AnonymousDr** [comment]
That problem occurs when the plugin starts or the command /resload its runned.

**Comment by Zrips** [comment]
is this still a problem?
