### ISSUE TITLE
使用带NBT数据的生成蛋生成实体可以绕过领地限制！Using spawn_egg(with NBT-DATA)  to generate entities can bypass territorial restrictions!

### ISSUE THREAD

**Issue by Leoparking** [Zrips/Residence#1161]
For example, if you use command 
`/give @p minecraft:ocelot_spawn_egg{EntityTag:{Time:1,BlockState:{Name:"minecraft:carved_pumpkin"},id:"minecraft:falling_block"}} 1`
Get a SpawnEgg and give it to an ordinary player. Stand in a territory with many restrictions, right-click on the ground, and generate a "falling block"! Even if any objects are prohibited from being placed in this area, the use of egg generating animals is also prohibited. But he did it
<img width="982" alt="image" src="https://github.com/Zrips/Residence/assets/141799770/7de39a49-6e8a-4f9c-95af-9744d1e6ed9e">
<img width="342" alt="image" src="https://github.com/Zrips/Residence/assets/141799770/ca6924c9-d08f-498c-a13b-d6309d9c7bf6">

Using [NBT EDIT]（ https://www.mcmod.cn/class/11890.html ）You can modify the items in your hand, regardless of whether the player is an OP or not!
Suggest adding a permission setting that directly allows（or not） the use of egg generated entities to prevent all events generated by egg generation

**Comment by Zrips** [comment]
2cae67d94532f04b2ac1f69d22f4fb0cb39d131c
