### ISSUE TITLE
[Bug] Residens is unable to prevent the player from right-clicking"redstone_wire"

### ISSUE THREAD

**Issue by BangXi** [Zrips/Residence#1162]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=607335763198014923 skey=@crypt_9bab60fb_f4a4ca94275567e9653ca9b5f8fdb1ea mmweb_appid=wx_webfilehelper (1)](https://github.com/Zrips/Residence/assets/135555687/88ad6f28-cbcb-4d35-bb57-1b52daea2fb1)
redstone_wire have two states: + and *
Residens should protect redstone_wire from being right-clicked

Residens5.1.4.3
1.20.4

**Comment by Zrips** [comment]
fbe116862f9fd9cedda4ed7b6b8150750b13521a
