### ISSUE TITLE
Res tp not working

### ISSUE THREAD

**Issue by Inf1n1ty2O2** [Zrips/Residence#1163]
I have the server on version 1.20.1, Residence version 5.1.4.3 and CMILib version 1.4.6.2. For some reason /res tp is not working for some players. It works with op, but not without op. Without op /res tp does nothing and it doesn't write any error either in chat or console.

**Comment by lipind** [comment]
Does your server have permission plugins? like LP

**Comment by Inf1n1ty2O2** [comment]
Yes, it does. But from what I've seen, there is no permisse on /res tp and it's a base enabled command.
