### ISSUE TITLE
config-CustomContainers is not work! please!

### ISSUE THREAD

**Issue by ATCatBoss** [Zrips/Residence#1164]
![image](https://github.com/Zrips/Residence/assets/102211069/79dc55ee-5052-4de6-b5ad-5015217b785f)
![image](https://github.com/Zrips/Residence/assets/102211069/e350de94-840a-4b48-ace4-75f211a3b48d)

**Comment by ATCatBoss** [comment]
Added: I use mohist core, game version 1.12.2, use 5.1.4.3 plugin version

**Comment by Zrips** [comment]
1b47b4e2799dd5f1ce537bf251259f1a1b810d61
