### ISSUE TITLE
MaxUpDown bug

### ISSUE THREAD

**Issue by cloudwww** [Zrips/Residence#1166]
I set the MaxUpDown of the plug-in to 40, then restarted the server and selected areas with heights of 38, 39, and 40. The plug-in will prompt that it is too high, but if it is less than or equal to 37, it can be created.
我将插件的MaxUpDown设置为40，然后重启了服务器，选择了高度为38、39、40的区域，插件会提示过高，但是小于等于37的话，就能够创建

**Plugin**: The selection height (38) is too large, the value must be 40 or less
插件表示：38 > 40

![image](https://github.com/Zrips/Residence/assets/48478399/165c9363-2518-4623-8cbe-8dce86963042)

**version:**
paper-1.20.4-493
Residence5.1.4.3
CMILib1.4.6.3

**This is my groups.yml:**

>        Residence:
>            # Determins if this group can create residences or not.  This option can be overriden with the permissions node 'residence.create'
>            CanCreate: true
>            # The maximum number of Residences a player can have.
>            MaxResidences: 4
>            # The maximum number of physical areas a residence can have.
>            MaxAreasPerResidence: 2
>            # The maximum number of blocks a Residence can be, East to West (X).
>            MaxEastWest: 50
>            # (Optional) The minimum number of blocks a Residence can be, East to West (X).
>            MinEastWest: 3
>            # The maximum number of blocks a Residence can be, North to South (Z).
>            MaxNorthSouth: 50
>            # (Optional) The minimum number of blocks a Residence can be, North to South (Z).
>            MinNorthSouth: 3
>            # The maximum number of blocks a Residence can be, High to Low (Y).
>            MaxUpDown: 40
>            # (Optional) The minimum number of blocks a Residence can be, High to Low (Y).
>            MinUpDown: 3
>            # The lowest altitude this group is allowed to protect.
>            MinHeight: -64
>            # The highest altitude this group is allowed to protect.
>            MaxHeight: 320
>             # The maximum amount of subzones can current area have.
>            MaxSubzonesInArea: 3
>             # The maximum recursive depth that subzones can go.
>             # A subzone within a subzone within the Residence zone would be a depth of 2.
>             # Set to 0 to disable subzones.
>            SubzoneDepth: 3
>            # (Optional) The maximum number of blocks a Residence Subzone can be, East to West (X).
>            SubzoneMaxEastWest: 16
>            # (Optional) The minimum number of blocks a Residence Subzone can be, East to West (X).
>            SubzoneMinEastWest: 3
>            # (Optional) The maximum number of blocks a Residence Subzone can be, North to South (Z).
>            SubzoneMaxNorthSouth: 16
>            # (Optional) The minimum number of blocks a Residence Subzone can be, North to South (Z).
>            SubzoneMinNorthSouth: 3
>            # (Optional) The maximum number of blocks a Residence Subzone can be, High to Low (Y).
>            SubzoneMaxUpDown: 320
>            # (Optional) The minimum number of blocks a Residence Subzone can be, High to Low (Y).
>            SubzoneMinUpDown: 3
>            # Whether or not to allow teleporting to Residences.
>            CanTeleport: true
>            # Allow or Disallow the use of /res unstuck, to get yourself out of a residence if stuck in one somehow
>            Unstuck: true
>            # Allow or Disallow the use of /res kick, to kick player from residence.
>            Kick: False
>            # Allow or Disallow the use of the /res select command, if disabled they can only use the selection tool.
>            SelectCommandAccess: false
>            # Allow or Disallow the group to access the Blacklist/Ignorelist for residences they own.
>            ItemListAccess: true

**Comment by Zrips** [comment]
812b6e598abb1da97aba5e78c1fca373d262b502
