### ISSUE TITLE
After /mv regen the residence plugin caused a huge server crash

### ISSUE THREAD

**Issue by pjindras** [Zrips/Residence#1167]
Hello, I had world survival_nether, with residences, I removed the residences using /resadmin removeworld survival_nether and than made /mv regen.

Then, after a couple of hours, the player tried /res tp command, and - it caused a huge server crash.

https://mclo.gs/upJKcY5

This must be a known issue because this is not the first time that it happened; maybe a year ago, I reported the same problem.

**Comment by Zrips** [comment]
9a451d2a97979664a7697c4209c5f9be1688882a
