### ISSUE TITLE
[API] Questions regarding the ResidenceCreationEvent event

### ISSUE THREAD

**Issue by lipind** [Zrips/Residence#1169]
Hello, when I am using the ResidenceCreationEvent, I have noticed that the event is triggered even if the player's vault does not have sufficient funds to pay for the Residence. Is there a method to determine whether the creation of the Residence was successful?

and Is there a detailed documentation for the Residence API?

**Comment by Zrips** [comment]
Looks to be a bug, will be resolved with next update
08cdb27189695f514190b1a61f03e9bcbf9a734c
