### ISSUE TITLE
/res shop list

### ISSUE THREAD

**Issue by Blackdigits** [Zrips/Residence#117]
Shop list numbering are either having a typo or is actually missing shop number 11-20

Steps to recreate problem: create 30-ish shops, and /res shop list, if you click on next page, there's no shop number 11-20

![2017-12-05_11 10 01](https://user-images.githubusercontent.com/6441341/33611418-e4cd229e-da00-11e7-9686-8804ebff2c3f.png)

**Comment by Zrips** [comment]
c9cdfbc8991a8592644fe94ed00b766517463034
