### ISSUE TITLE
[API] Questions regarding the ResidenceRenameEvent event

### ISSUE THREAD

**Issue by lipind** [Zrips/Residence#1171]
ResidenceRenameEvent have setCancelled？
I would like to check a certain permission of my plugin to determine if renaming residence is allowed
PS: When I say permission, it refers to the judgment logic of my plugin

**Comment by Zrips** [comment]
37be0a22f176daf2995d4600a1f01dc538bf6a7c
With next version you should be able to use event, cancel it or modify new residence name
