### ISSUE TITLE
[Bug] Slabs, glass_panes, walls, etc. unprotected from water bucket

### ISSUE THREAD

**Issue by Learting** [Zrips/Residence#1174]
When standing outside a residence area, one can place a water bucket on the waterloggable blocks inside the residence area. So the 'waterlogged' state of such blocks is unprotected. 

**!! From my observation, this only happens when the player is outside the target residence.**

**Comment by Zrips** [comment]
dc2add90991203e2c9f5ecb839adeffed11e7ad4
