### ISSUE TITLE
Major Console Spam in Residence 5.1.5.0

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#1177]
Getting pretty major console spam with Residence 5.1.5.0: https://gist.github.com/mercurialmusic/34b042d3c1ab6c32f681aff79333fceb
It's so constant I'm not able to tell what may be causing it.

Using git-Paper-496 (MC: 1.20.4) with CMILib: 1.4.7.15 on Java 21.

**Comment by Zrips** [comment]
60390337529938870d5ae0aec427737a2e56eb6e
