### ISSUE TITLE
无法使用/res set 或/resadmin set打开GUI菜单，并且所有限制项目都失灵了！

### ISSUE THREAD

**Issue by Leoparking** [Zrips/Residence#1179]
<img width="649" alt="image" src="https://github.com/Zrips/Residence/assets/141799770/afcb6cda-f870-438b-8823-318b6c2c4134">
<img width="332" alt="image" src="https://github.com/Zrips/Residence/assets/141799770/46e62a14-6372-48bc-aa0f-a6d216858b4d">
使用最新版5.1.5.0。更新前使用5.1.4.0没有此问题。
除了PVP保护外，其余的防护全部失灵

**Comment by cloudwww** [comment]
我也遇到这个问题了
I have the same problem

**Comment by Zrips** [comment]
Without server version or any error messages its hard to fix things, especially when it works on the latest versions of minecraft. Would need server version and possibly that error message which should have been shown as of first image, as that one would only appear if there is error message in console with detailed explanation what actually happen and where.

**Comment by Leoparking** [comment]
> 如果没有服务器版本或任何错误消息，则很难修复问题，尤其是当它适用于最新版本的 Minecraft 时。需要服务器版本，并且可能需要应该在第一张图像中显示的错误消息，因为只有当控制台中有错误消息时才会出现该错误消息，并详细说明实际发生的情况和位置。

CMILIB needs to be updated
