### ISSUE TITLE
Can't Build Nether Portal

### ISSUE THREAD

**Issue by 510208** [Zrips/Residence#1181]
## Version

**Residence**: 5.1.5.0
**Minecraft Server**: git-Purpur-2158 (MC: 1.20.4)*

## Description

I installed the Residence plugin, but when I tried to enter a portal to hell, I found that it kept sending the message "Portal destination is in restricted zone. Portal creation canceled. &7Find new location", but I created the territory where no one else (including me) established any territory first.

## Screenshot

![image](https://github.com/Zrips/Residence/assets/107909497/72b422c0-32bd-40f0-959a-16c950ca4c51)
(My server uses Chinese Traditional (Taiwan))

> Oh right, This plugin is good, I like it but I want fix this problem quickly~~

**Comment by Zrips** [comment]
This message appears when your destination location is inside someone else residence, so there is residence area in nether which prevents you from creating portal at that end. This is general protection to prevent automatic portal creations inside someone's residence when you travel to and from nether.
