### ISSUE TITLE
When residence changes owner, new owner cannot use /res kick

### ISSUE THREAD

**Issue by pjindras** [Zrips/Residence#1184]
In Residence5.1.4.3, when the res owner is changed, for example, via /resadmin setowner, then the new owner cannot use /res kick; when he types the command, nothing happens.
I don't use 5.1.5.0 because it was very bugged and broken on my server, unfortunately, for example /res auto and residence creation in case of Y height is very broken in the 5.1.5.0 version.

**Comment by Zrips** [comment]
a26dbf08def3bba576b9a72dc28f901757556a21
If issue persists with next version, let me know, just provide your server version and type (online/offline) mode indication you have set in config file
