### ISSUE TITLE
Movement permission

### ISSUE THREAD

**Issue by fortunatas1** [Zrips/Residence#1187]
There is way change location (now teleporting to last position) when players trying to access residence, when he's didn't have movement permission?

**Comment by Zrips** [comment]
Trying to access residence area by moving or teleporting into one should be blocked as long as residence has appropriate flags set for it. Teleportation would be blocked if residence has move false or tp false, while movement into it would be blocked by move false flag. Returning back to residence you didn't had permission for could only be bypassed if teleportation was forced or/and there was no player teleport event being fired which could used to stop players teleportation into residence.
