### ISSUE TITLE
sandThe sand disappeared.

### ISSUE THREAD

**Issue by Fogrine** [Zrips/Residence#1189]
cmilib 1.4.7.16
Residence 5.1.5.0

ResidenceDefault:
  fallinprotection: false

If sand falls from inside the residence to outside the residence, it will disappear.
If sand falls from outside the residence, passes through the residence, and then falls outside the residence again, it will not be an issue.

https://github.com/Zrips/Residence/assets/175352136/3c1f4545-3b9c-4b80-abcd-87000d70774c

**Comment by Fogrine** [comment]
paper 1.20.1

**Comment by Zrips** [comment]
fd1326fa9181cdb757eae33e037fce44e65b693e
