### ISSUE TITLE
[High priority]cannot prevent other players' weaving effects from placing cobweb

### ISSUE THREAD

**Issue by CatBang** [Zrips/Residence#1192]
[weaving](https://minecraft.wiki/w/Weaving)

Now, when the weaving effect places a cobweb, the EntityChangeBlockEvent is triggered.
https://github.com/PaperMC/Paper/pull/11087/files

paper 1.21#78
Residence 5.1.5.1
CMILib 1.5.0.7

**Comment by CatBang** [comment]
Using the 'weaving' effect, other players can now place 'cobwe' freely within the protected area of Residence.

**Comment by Zrips** [comment]
fee751fd1dd734437ef38ffc17587682c1ba52e0

**Comment by CatBang** [comment]
> [fee751f](https://github.com/Zrips/Residence/commit/fee751fd1dd734437ef38ffc17587682c1ba52e0)

Hello, can you release the fixed build version of [Residence](https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-20.11480/)? I need it ❤️

**Comment by Zrips** [comment]
New version is out.

**Comment by CatBang** [comment]
> New version is out.

Thank you
