### ISSUE TITLE
[bug] players got kicked by `/res kick` cause folia server region crash/freeze

### ISSUE THREAD

**Issue by cgw2023** [Zrips/Residence#1199]
folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf-ec6b172
CMILib1.5.1.0
Residence5.1.5.3

# explanation
when a player is in a super big residence claim, and the player is being kicked by /res kick, the player's current folia region will crash

# step to reproduce
1. create a big residence claim, like 500x500
2. step in the middle of residence claim, make sure the player that will be kicked will be outside of active folia region
3. kick the player
4. folia region is freezed, nothing can be do

# video demonstration 
https://youtu.be/KrWQg8nJ_80

**Comment by Zrips** [comment]
6910c245ececfcc9d9629eb9d912e0656f6a6088
