### ISSUE TITLE
URGENT: Players can destroy ItemFrames with boats

### ISSUE THREAD

**Issue by Tarka-Dhal** [Zrips/Residence#120]
Players can destroy ItemFrames in residence with boats.

**Server:** Paper version git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
You are 173 version(s) behind
**Residence:** 4.7.2.4
**Evidence:** https://www.youtube.com/watch?v=z0it_dYmxMU&feature=youtu.be

**Comment by Zrips** [comment]
Confirmed, will be fixed
