### ISSUE TITLE
Very lag

### ISSUE THREAD

**Issue by 3328429240** [Zrips/Residence#1203]
![image](https://github.com/user-attachments/assets/3b8e9520-5756-457e-b29b-e83e8e81115e)
Ver 5.1.5.3
I have to mention this issue, which has caused significant latency and lag on my server. I hope there is a way to temporarily alleviate this problem!

**Comment by Zrips** [comment]
Could you provide link to timings?

**Comment by Zrips** [comment]
76661a55e517e2deb1a3ff18bab636692464a586
