### ISSUE TITLE
All residences will delete after restart

### ISSUE THREAD

**Issue by NexonPlayed** [Zrips/Residence#1206]
**Describe the bug**
After server restart, crash or anything about stoping and starting server, will remove all residences i dont know why, no other plugin is doing it (i think)..

**Screenshots**
Just.. after restart all residences are gone

**Server version:**
 - Residence version 5.1.6.0

**Additional context**
Using world-gen IRIS, might be it? I don't think so but might help.

**Comment by Zrips** [comment]
This should be fixed with todays Residence update
29690a5b57fb0a911013db5ba87ba925840f074e
