### ISSUE TITLE
Pl3xMap - Residence markers

### ISSUE THREAD

**Issue by daniel-skopek** [Zrips/Residence#1209]
Residence markers are not showing on Pl3xMap like the feature would be disabled. It works on my second server but not for the first one.

Log from the broken server: https://pastebin.com/raw/HXarBnH8

Residence config: https://pastebin.com/raw/HAK2HcwF

Residence version: 5.1.6.2
Pl3xMap version: 1.21.1-508
Server version: 1.21.1

**Comment by Zrips** [comment]
255a5b3167366d8b18f84b3c2b8ec390e802fc7d
