### ISSUE TITLE
Issue about command `res pset [playername]`

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#1211]
Some plugins works with residence such as quickshop.
I take the quickshop plugin as an example.
The plugin quickshop can provide additional flags quickshop-create and quickshop-trade for the residence.
I can use the command res set quickshop-create flag on the residence.
However, I cannot use the command res pset quickshop-create flag on specific player.

This function works in previous version 5.1.6.0
Not sure if this update in 5.1.6.1 cause the issues.
"Updated pset command handling which is now less picky in what variables you provide and in what order, tho for best consistency you should still do it in provided order."

Purpur version: 1.20.1
Residence version: 5.1.6.2
CMILib version: 1.5.1.4

**Comment by CatBang** [comment]
This is not an issue with Residence; it is a problem with the compatibility module of quickshop-hikari. You should contact the author of quickshop for feedback.

**Comment by siulung201314** [comment]
> This is not an issue with Residence; it is a problem with the compatibility module of quickshop-hikari. You should contact the author of quickshop for feedback.

However, not only the plugin quickshop has the issue.
I have other plugins which provide additional flags have the same issue.
Everything work well in 5.1.6.0.
I update to the latest version and additional flags of all other plugin cannot be set by using the command res pset.
But additional flags can be set by using command res set.
Therefore, I think the command res pset causes the issue.

**Comment by siulung201314** [comment]
I would like to upload some photo to provide more information about the issue.
The flag can be set by using the command /res set quickshop-create true.
![image](https://github.com/user-attachments/assets/14e0bcd1-581a-4d75-a09c-44782d6b023e)
If I use /res pset [player] quickshop-create true
![image](https://github.com/user-attachments/assets/31735142-f380-4c11-bf71-671113f3f8c1)
It only shows the GUI.
![image](https://github.com/user-attachments/assets/148446c9-4e08-439e-9f04-7db99c99f9cb)

I have tested the latest version 5.1.6.3,
However, the issue is still here.
In version 5.1.6.0,
everything works well.
I hope the issue can be fixed as players usually need to pset the additional flags in their residence.

**Comment by CatBang** [comment]
> I would like to upload some photo to provide more information about the issue. The flag can be set by using the command /res set quickshop-create true. ![image](https://private-user-images.githubusercontent.com/83176041/377929563-14e0bcd1-581a-4d75-a09c-44782d6b023e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5Mjk1NjMtMTRlMGJjZDEtNTgxYS00ZDc1LWEwOWMtNDQ3ODJkNmIwMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzdkOTVkODI5ZDI3MzliYTFjYTQ2YTAyOGJlZDcxMzQxMzNlODU0YjJlZmFmZjY4NjRhMWYzOTQyZGNiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EEoxsqzEfP8MjHPZYieGtQcMNkltBFbicJkhxF3_yrI) If I use /res pset [player] quickshop-create true ![image](https://private-user-images.githubusercontent.com/83176041/377931861-31735142-f380-4c11-bf71-671113f3f8c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5MzE4NjEtMzE3MzUxNDItZjM4MC00YzExLWJmNzEtNjcxMTEzZjNmOGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMDc5YTk0OWU1YmFlNzI4YzVlMTExOTE3ZGI5NjRkZjQ4NmM2ZThiYTNmMGE3YTE3MTNmMDcxMzMzZDViZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I5vmgu-Qbqh_pBPiilvr7qzepP0OB0jqGfJd8IjHLEU) It only shows the GUI. ![image](https://private-user-images.githubusercontent.com/83176041/377932009-148446c9-4e08-439e-9f04-7db99c99f9cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5MzIwMDktMTQ4NDQ2YzktNGUwOC00MzllLTlmMDQtN2RiOTljOTlmOWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YjBmMGZmZDc5YmU4YWQxYzgyNDEyMDU5NmFlNTMzOGYwOTJkMjU5ODdhYmVkNjk4NmIxZWJkYTljZDJlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fr567tgJCFct2ud018VnINiPjshL7RHZQBI9iZu-p6k)
> 
> I have tested the latest version 5.1.6.3, However, the issue is still here. In version 5.1.6.0, everything works well. I hope the issue can be fixed as players usually need to pset the additional flags in their residence.

You may need to provide feedback to the author of the quickshop plugin, as the compatibility itself is provided by quickshop.

**Comment by siulung201314** [comment]
> > I would like to upload some photo to provide more information about the issue. The flag can be set by using the command /res set quickshop-create true. ![image](https://private-user-images.githubusercontent.com/83176041/377929563-14e0bcd1-581a-4d75-a09c-44782d6b023e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5Mjk1NjMtMTRlMGJjZDEtNTgxYS00ZDc1LWEwOWMtNDQ3ODJkNmIwMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzdkOTVkODI5ZDI3MzliYTFjYTQ2YTAyOGJlZDcxMzQxMzNlODU0YjJlZmFmZjY4NjRhMWYzOTQyZGNiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EEoxsqzEfP8MjHPZYieGtQcMNkltBFbicJkhxF3_yrI) If I use /res pset [player] quickshop-create true ![image](https://private-user-images.githubusercontent.com/83176041/377931861-31735142-f380-4c11-bf71-671113f3f8c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5MzE4NjEtMzE3MzUxNDItZjM4MC00YzExLWJmNzEtNjcxMTEzZjNmOGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMDc5YTk0OWU1YmFlNzI4YzVlMTExOTE3ZGI5NjRkZjQ4NmM2ZThiYTNmMGE3YTE3MTNmMDcxMzMzZDViZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I5vmgu-Qbqh_pBPiilvr7qzepP0OB0jqGfJd8IjHLEU) It only shows the GUI. ![image](https://private-user-images.githubusercontent.com/83176041/377932009-148446c9-4e08-439e-9f04-7db99c99f9cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5MzIwMDktMTQ4NDQ2YzktNGUwOC00MzllLTlmMDQtN2RiOTljOTlmOWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YjBmMGZmZDc5YmU4YWQxYzgyNDEyMDU5NmFlNTMzOGYwOTJkMjU5ODdhYmVkNjk4NmIxZWJkYTljZDJlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fr567tgJCFct2ud018VnINiPjshL7RHZQBI9iZu-p6k)
> > I have tested the latest version 5.1.6.3, However, the issue is still here. In version 5.1.6.0, everything works well. I hope the issue can be fixed as players usually need to pset the additional flags in their residence.
> 
> You may need to provide feedback to the author of the quickshop plugin, as the compatibility itself is provided by quickshop.

OK!
I will provide feedback to the author of the quickshop plugin too.

**Comment by GoodestEnglish** [comment]
> > I would like to upload some photo to provide more information about the issue. The flag can be set by using the command /res set quickshop-create true. ![image](https://private-user-images.githubusercontent.com/83176041/377929563-14e0bcd1-581a-4d75-a09c-44782d6b023e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5Mjk1NjMtMTRlMGJjZDEtNTgxYS00ZDc1LWEwOWMtNDQ3ODJkNmIwMjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzdkOTVkODI5ZDI3MzliYTFjYTQ2YTAyOGJlZDcxMzQxMzNlODU0YjJlZmFmZjY4NjRhMWYzOTQyZGNiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EEoxsqzEfP8MjHPZYieGtQcMNkltBFbicJkhxF3_yrI) If I use /res pset [player] quickshop-create true ![image](https://private-user-images.githubusercontent.com/83176041/377931861-31735142-f380-4c11-bf71-671113f3f8c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5MzE4NjEtMzE3MzUxNDItZjM4MC00YzExLWJmNzEtNjcxMTEzZjNmOGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMDc5YTk0OWU1YmFlNzI4YzVlMTExOTE3ZGI5NjRkZjQ4NmM2ZThiYTNmMGE3YTE3MTNmMDcxMzMzZDViZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I5vmgu-Qbqh_pBPiilvr7qzepP0OB0jqGfJd8IjHLEU) It only shows the GUI. ![image](https://private-user-images.githubusercontent.com/83176041/377932009-148446c9-4e08-439e-9f04-7db99c99f9cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg0MDMsIm5iZiI6MTcyOTI2ODEwMywicGF0aCI6Ii84MzE3NjA0MS8zNzc5MzIwMDktMTQ4NDQ2YzktNGUwOC00MzllLTlmMDQtN2RiOTljOTlmOWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YjBmMGZmZDc5YmU4YWQxYzgyNDEyMDU5NmFlNTMzOGYwOTJkMjU5ODdhYmVkNjk4NmIxZWJkYTljZDJlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fr567tgJCFct2ud018VnINiPjshL7RHZQBI9iZu-p6k)
> > I have tested the latest version 5.1.6.3, However, the issue is still here. In version 5.1.6.0, everything works well. I hope the issue can be fixed as players usually need to pset the additional flags in their residence.
> 
> You may need to provide feedback to the author of the quickshop plugin, as the compatibility itself is provided by quickshop.

Although I am not the quickshop dev, I am the dev who developed one of the residence addon for the server. Since the API didn't change, it is most likely residence side problem. Correct me if I am wrong.

As @siulung201314 said, using `FlagPermissions.addFlag(String);` to create a flag, and then use the command `/res pset {username} {flag} true` will not work. In my observation seems like the command is currently broken as the command only works with default flag. 

Note: `/res set` works, only `/res pset` is broken

**Comment by Zrips** [comment]
c663ff426ec6f6b7a575d72dafcde85ee2ba361c
