### ISSUE TITLE
Issue in /res PSET with REMOVE flags

### ISSUE THREAD

**Issue by smscentras** [Zrips/Residence#1212]
**Describe the bug**
Did not remove flags in PSET(while command SET removing)

**To Reproduce**
/res pset ResidenceName PlayerName beacon remove

**Server version:**
Residence version 5.1.6.2
CMILib version 1.5.1.4
Server version Purpur 1.21.1(2311)
Java version 21.0.4

**Comment by Zrips** [comment]
bc76ec9c061d0be05757ee2e78baa640cbc0f7f4
