### ISSUE TITLE
command `/resadmin rename [oldName] [newName]` not work

### ISSUE THREAD

**Issue by BredyAK** [Zrips/Residence#1216]
**Describe the bug**
command `/resadmin rename [oldName] [newName]` not work. if i run it with console, i will get:
```
&eUsage: &6/res rename [OldName] [NewName]
You must be the owner or an admin to do this.
The name must not already be taken by another residence.
```
but, i'm already the admin.

**Server version:**
Residence version: 5.1.6.3
CMILib version: 1.5.1.6

**Comment by Zrips** [comment]
ce26dc3976b99943bcadfcee3f85f228f7d368bb
