### ISSUE TITLE
When player doesnt have allowed move, is randomly teleported to different world

### ISSUE THREAD

**Issue by pjindras** [Zrips/Residence#1217]
**Describe the bug**
When player, who doesnt have move allowed in residence try to go into this resicence (walking from world etc.) than he is teleported 2 steps back into mobarena, which is absolutely in different world and the player was there 10 minutes ago.

**Server version:**
18:37:35[INFO] Residence version: 5.1.6.3
18:37:35[INFO] CMILib version: 1.5.2.2
18:37:35[INFO] Java version: 21.0.2

Minecraft 1.21.1

**Additional context**
Please fix this issue.

**Comment by Zrips** [comment]
7fdc84c9c70de59cb2d25c2c786627e435c4658f
