### ISSUE TITLE
Flag permissions dont work in PEX. [Resolved]

### ISSUE THREAD

**Issue by NorthWestTrees** [Zrips/Residence#122]
So I have tried to use the permission nodes below to restrict flags in PEX groups but all players can still use all the flags via the /res set command.

I may have an older version of res and I will need to make sure all the plugins we use update to 1.12.1 if I go to test to see if its fixed hopefully there is a setting I missed and someone can walk me through how to set I up properly but in the case I have done everything right then please add support for PEX.

Permission format I used:
- residence.flag.build

Thanks in advance.

**Comment by L-E-iT** [comment]
Have you tried giving a user the following permission?
``` -residence.flag.build``` ? This would take away the permission to use the build flag I believe.

I think that sounds like your issue.

IF you have not disabled the flag in your config files, make sure to do that as well.  That would be the first place to disable the flag, not through permissions.  That permission node is used to override the configuration file setting.

**Comment by NorthWestTrees** [comment]
The config worked thank you so much!!! I had a feeling that there was an extra step I need to do but could not figure it out thanks a tone!
