### ISSUE TITLE
Chat Placeholder not working!

### ISSUE THREAD

**Issue by L-Clockworker** [Zrips/Residence#123]
I'm trying to use this feature:
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-12.11480/update?update=97051

Chat Prefix with uChat.
I can't get the prefix to show.

**Comment by MothGirlMusic** [comment]
i have the same issue. Using CMI however, written by the same person who writes this plugin....

**Comment by MothGirlMusic** [comment]
https://github.com/Zrips/Residence/issues/241

**Comment by Zrips** [comment]
a295e0f5098694dc11d1adc3f3e94c8365db784c
