### ISSUE TITLE
Bigger claim size depending on rank?

### ISSUE THREAD

**Issue by SaltedBiscuit** [Zrips/Residence#125]
Is something like this possible:

Guest: 25x25 claimspace
Member: 50x50
VIP: 100x100

If so, how would i accomplish this?

**Comment by L-E-iT** [comment]
In the ```groups.yml``` config file you should be able to create new profiles based on different ranks you have on your server.  From there, you can use the groups permissions to assign different groups to those ranks.  Within the ```groups.yml``` file, for the new group, change the ```MaxEastWest``` and ```MaxNorthSouth``` values and adjust how many residences they can own to control area claimspace and residence counts.

[Here](https://github.com/Zrips/Residence/blob/e8eae810b2722b5c3007c0609cf139bb37d4d753/src/groups.yml#L17) is one of the nodes I referenced in the ```groups.yml``` file
