### ISSUE TITLE
[Request] Support for Renting Flags

### ISSUE THREAD

**Issue by NorthWestTrees** [Zrips/Residence#128]
I messaged the developer a while ago maybe a week ago or so, I still have not gotten a response so I thought I would post this here as I am unsure if my request got through to you guys.

Anyhow, I am unsure if its just a problem with the version I have or if there is no support for flags and renting but, there need to have an option for setting flags for rentable subzones and residence, the version I have does not give the following perms witch have to be set by my staff as we want to rent out player shops at spawn and spawn house.

- Use
- Doors
- Break
- Place
- Build

We have one massive residence in our spawn world to protect spawn using residence, I would use world guard but they take too long to update that plugin now these days. I have been working on my server 2 years to build a really awesome spawn and find plugins like yours that update fast and are reliable for release.

I just think that there should a way to set flags for rentable zones for the people that rent the subzone or residence.

If it a bug or there is a hidden a way to set up flags for those residences that still provide the protection that they won't get griefed please tell me how.

**Comment by smmmadden** [comment]
please provide the version of Minecraft you are using, Spigot, Craftbukkit, Bungee, etc and it's version along with the Permission plugin used and the version of Residence you have.  Without that, no one would be able to make suggestions on how to proceed.

**Comment by NorthWestTrees** [comment]
I am using the following platform:
Spigot 1.12.1 (build 60) from what I have written down not sure if its 100% accurate or not should be.

For permissions, I am using the following.
PermissionsEX
Uses Vault
Version 1.10 (works with 1.12.1)
https://dev.bukkit.org/projects/permissionsex

Vault:
Plugin Version 1.5.6
MC Version: 1.11.2 (Plugins seem to have no problems with 1.12.1 that I have installed or the MC version may be outdated in my update document.)
https://dev.bukkit.org/projects/vault

Residence info (looks like this is up to date on my document.)
Minecraft Version 1.12
Plugin Version 4.7.1.2
Date: July 27, 2017.
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-11.11480/

**Comment by NorthWestTrees** [comment]
Not sure if anyone is still looking into this problem, but I still need help, please.

**Comment by Zrips** [comment]
fd3609c09abfd0cfd7241356424881a8d45e4d07
