### ISSUE TITLE
Can Res flags override Worldguard region flags?

### ISSUE THREAD

**Issue by Flyerminer** [Zrips/Residence#13]
Hello my name is Flyerminer, a highly privileged admin of a server called CapitalCraft. The problem we are facing is that we wish to use **Worldguard** to deny access to build, but still use the **Residence plugin** and have residences created which you can build in. When we create a Worldguard region, and tell it to deny building, and put a residence inside with the flag for building enabled, it still denies building rights. Is there any way to resolve this? This also applies to when there is no region, but building is disallowed by Worldguard across the server. the plugin claims optional WorldGuard support but I'm missing where the plugins are able to interact. 

_Any help_ would be appreciated, thank you.
~The CapitalCraft Staff

**Comment by D3thw0lf** [comment]
Same Problem...Any news?

**Comment by Zrips** [comment]
Currently its prevents residence creation in world-guard regions or overlapping them in one or another way. To override worldguard flags we would need to actually create sub world guard regions with particular flags and permissions for that player('s). We cant force worldguard to ignore actions in region when you are in residence at same time. It would be better for worldguard plugin dev's to add support for this as that would be simpler.
