### ISSUE TITLE
Unhandled exception in /res select coords

### ISSUE THREAD

**Issue by adamlaughlin** [Zrips/Residence#138]
Hey there, I get a little confused sometimes between worldguard and residence command syntax, and revealed an exception to myself by trying this command:

`/res select coords`

without a selection initialized.  Got some spew from the console so I spent a little while taking out all of my recent plugins, as I believed that command was supposed to select a cuboid before I realized I was being a dummy :P

Handling the exception with something like "You need a selection dummy!" would be nice and could save some people a little time =)

Thank you for making this plugin a Freemium download.  I am trying to find work and using this server to keep myself working and still enjoy life.  I will definitely hold up my end when possible and hope you find satisfaction in your generosity.

**Comment by Zrips** [comment]
81b1cc707e4ec348f84b7421d2faec101ce0650d
