### ISSUE TITLE
Residence and Worldguard

### ISSUE THREAD

**Issue by HawkxX1337** [Zrips/Residence#140]
How I could get Residence work together with Worldguard? I can't find something in the config ore somewhere else. My problem:

 If I create a residence with the server as owner and going to rent/buy it I can't build something if the "__global__" (means the whole world as region by WorldGuard) region uses the "passthrough deny" flag from WorldGuard. I want to create a city where you can only build in your rented residence. I don't get it...

**Comment by Zrips** [comment]
I cant filter out each event to by ignored by 3rd party protection plugin. WorldGuard will prevent any action player does in that area independent what residence flags he has. WG could add support for it by giving priority for residence to handle things like this, but in general this is not possible to achieve without some complicated recode to have support like this.

**Comment by HawkxX1337** [comment]
But there ist "(Optional: WorldGuard Support)" in the Plugin Description. I thought, I would work together allready.
