### ISSUE TITLE
Admins losing access to their residences

### ISSUE THREAD

**Issue by Pyrite-Ace** [Zrips/Residence#141]
Spigot version - 1.12.2
Residence version 4.7.6.0

At this point in time, any player with the "*" permission finds themselves unable to retain their residence after a restart. The residence in question will still list the player as the owner, but will not recognize the actual "player character" as the owner of the residence.

(Hard to explain... basically, for my case, my residences list me as the owner, but when I do /res list - there is no residences in my personal list, and I have to use /resadmin to make changes on the residences that still list me as "owner". ) Note, this only happens after a restart, before that, I can make residences, have them populate to my /res list, and change flags fine.

**Comment by Zrips** [comment]
Which exactly is this permission? Are you giving actual "*" permission node? Which is terrible idea. Its more less like giving out OP. More information will be needed to find cause
