### ISSUE TITLE
Minecraft with hopper

### ISSUE THREAD

**Issue by dunaland1** [Zrips/Residence#144]
I found a bug that fixes itself if I remove residence. So if you place rails and a minecraft with hopper on top, then remove the rails and place a slab on top of the minecraft hopper, you can place rails. 

And in vanilla minecraft that minecart with hopper sucks items from passing minecarts (another minecart with hopper in my case). But something in residence breaks this. Can you help me if there is a config option that takes care of this or fix it if its a bug.

**Comment by Zrips** [comment]
5b5fd8a972bd353b525cfe012bc79eb60dc20bea
