### ISSUE TITLE
res select vert not work

### ISSUE THREAD

**Issue by Vlader97** [Zrips/Residence#146]
The commands **/res select vert** and **/res select sky** do nothing. I don't see any error in console.
Plugin version 4.7.6.0

**Comment by Zrips** [comment]
Its expands to max allowed by your residence limits, so if you are higher than you can select already, then you will not see any change.

**Comment by Vlader97** [comment]
The limit is allowed from 0 to 256. I select 2 points and use /res select vert. After I don't receive any information message as in older version. If I use /res select coords I see same points with out change.

**Comment by Vlader97** [comment]
In new version 4.7.8.0 is working correctly.

**Comment by Vlader97** [comment]
The problem is that the messages "Selection expanded to your lowest allowed limit." and "Selection expanded to your highest allowed limit." not show always if I use the commands ** / res select vert ** and ** / res select sky **. Sometimes show sometimes not.
I use the lasted version 4.7.8.2 on spigot 1.12.2.
