### ISSUE TITLE
BlockBreakEvent causing major lag

### ISSUE THREAD

**Issue by Guddina-tim** [Zrips/Residence#152]
This is similar to this issue, but their solution for reducing Residence sizes didn't help me: https://github.com/Zrips/Residence/issues/87

The BlockBreakEvent is causing massive lag. 
![res](https://user-images.githubusercontent.com/5891184/38802502-379d78f0-4132-11e8-99d8-91e9be97d3cb.PNG)

This also massively affected mcmmo's TreeFeller ability, causing mcmmo to have a 20,000%+ increase in Pct Tick, as you can see here: https://timings.spigotmc.org/?url=feduxubico

When I disabled Residences in the world, resource usage dropped significantly, TPS went back to normal, and TreeFeller no longer caused problems. This tells me that Residences is the cause of the lag. I am rather disappointed that I bought this plugin now, because I can't use it on the server unless this issue is resolved.

I am running the latest Spigot 1.12.2 build and the latest version of Residences.

**Comment by Zrips** [comment]
3a5758579411ef4f452597461ef7e4f79d391f8a
