### ISSUE TITLE
Permanent fly bug from fly flag

### ISSUE THREAD

**Issue by ghost** [Zrips/Residence#153]
Steps for recreating the bug:
1. Give individual / group a permission for the fly flag and the other no permission for the fly flag
2. Using the individual with the fly perm, create a residence and turn fly on
3. Have the individual with fly permission give the residence to other player while flying
4. The original owner of the residence will have permanent fly

Latest Residence (Updated at 10 April)
PaperSpigot (Latest Version)

**Comment by arturek1666** [comment]
There is other issue issue xD. If you go to a region where res set fly true is on then if player on fly teleport with home to own region he will be able to fly, this method sometimes work sometimes it don't :(

**Comment by Blackdigits** [comment]
Update from the fly bug. Now players can just press space, spam jump all the time while on a residence with a fly flag on, and they'll fly :/

**Comment by Zrips** [comment]
6afbae4ebc5d8f45727a21d639f954b3b2fd126a
