### ISSUE TITLE
Earning larger claims?

### ISSUE THREAD

**Issue by gerardvanschip** [Zrips/Residence#156]
I come from Factions, Towny and Griefprevention which all let the user earn more claim credits over time. I noticed that Residence has a groups file which lets me set limits per group which I can assign to a user but that is a manual process. Also in large chunks. Is there a way for players to very slowly earn more claim blocks? If that is not possible can that be added?

**Comment by gerardvanschip** [comment]
No reply since may?

**Comment by Zrips** [comment]
New system has to be added to track players progress, which would include information like current max residence size, next increment and so on. Currently we only saving players residences. Adding players in general require us to add MySQL support, which would solve some issues, add some performance boost and so on. But this is huge rework for a base code and how residences are been saved.

**Comment by Zrips** [comment]
https://github.com/Zrips/Residence/issues/150
