### ISSUE TITLE
Feature Request - block certain/all command with flags?

### ISSUE THREAD

**Issue by ghost** [Zrips/Residence#162]
Hi there, I have bought both your residence and CMI plugin and I loved it. I have a feature request if you're open for requests :)

Recently, player has a lot of residence where they're hosting their own PVP events, and with that, there's FFA, or any sort of pvping. but when they die and they are sent back home, they can just /back and they're back in the game. I've told the residence owner to just kick and ban them from entering the residence, but it's been quite troublesome since the arena is very big to look for the player breaking the rules.

What I propose is:
a flag where you can disable commands. Player inside the region won't be able to do any commands at all, or they can at least do a few whitelisted commands (can be set in-game by each player, which command is allowed)

Thanks for reading!

**Comment by Zrips** [comment]
/res command block/allow
Is actual command which can prevent command usage in residence
