### ISSUE TITLE
[Request] Residence and Towny

### ISSUE THREAD

**Issue by Baktus79** [Zrips/Residence#163]
Hey

This might look stupid but I want to use Residence and Towny at the same time. I want to use the claim system from Residence for players that do not want to build a Town, and I want to use the Towny features for those who want to build towns. Yes I could use Residence for both, but I prefer to use Towny for town system. 

So my question is: Is it possible to make them both co-exist? My worries are all about overlapping claims on each other. I want Residence to recognize Towny claims and prevent from overlapping.

**Comment by Zrips** [comment]
Residence could be made to avoid overlapping with towny, but towny can still be overlapping with residence. This support should be made by both plugins, otherwise you will have issues.
