### ISSUE TITLE
[Request] "time" flag (and other non-boolean values)

### ISSUE THREAD

**Issue by HydroSnow** [Zrips/Residence#165]
Hello,
Instead of sticking to boolean flags, and keeping "day" and "night" flags for exemple, why not implement special values flags ?
Then, we will be able to put enter / leave flags, shop descriptions, time lock with flags. That would be easier to deal with for players !
Thanks for reading (and sorry for the grammatical mistakes if I made any).

**Comment by Zrips** [comment]
entire flag system currently is based on boolean value, changing it would introduce quite few changes to the base code. I did had some though about custom flags with some particular values, but at this point it would only introduce extra complexity without hug benefit.
