### ISSUE TITLE
/res set bucket true -> invalid flag

### ISSUE THREAD

**Issue by Oruss7** [Zrips/Residence#167]
Hello, 

See the title.

Thanks

**Comment by Eredrim** [comment]
Bucketfill and bucketempty flags does not work too.

**Comment by Eredrim** [comment]
The flags have been removed. See : https://github.com/Zrips/Residence/wiki/Flags-and-Commands

**Comment by Someone-NEW** [comment]
Hey i found there some flags not work to me too, if for example use **/res set** inside residence, for example for bucket this give me message in chat "Invalind Flag..." maybe are here more than this i see, than when if i use flag for water flow and lava flow both is true and **water will not flowing**.....

- Residence version: 4.8.3.1
- Server version: Spigot 1.12.2-R0.1-SNAPSHOT
- Vault version: 1.6.11(+)
Server Type (Spigot/Paperspigot/etc):1.12.2
Server Version (using `/ver`):CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Its been removed as they are deprecated
