### ISSUE TITLE
Residence and trademe

### ISSUE THREAD

**Issue by arturek1666** [Zrips/Residence#168]
I had notice that player can trade even if he has limit with the regions yes i have usemaxlimit to true evidence:
Residence:
  UseMaxLimit: true

However player still can trade even with limits xD. 

Using: 
Residence: 4.7.8.2
TradeMe: 5.1.4.8

**Comment by CloudeLecaw** [comment]
why dont simply block the trade command in the region?

**Comment by Zrips** [comment]
@CloudeLecaw 
there is command for that purpose /res command block

**Comment by arturek1666** [comment]
This is really old thread and I think issue is resolved as I could not recreate it again. Closing
