### ISSUE TITLE
Bug with enter/leave messages

### ISSUE THREAD

**Issue by Filip1004** [Zrips/Residence#172]
Please fix problem with eneter/leave messages in residence 
![2018-07-26_00 56 22](https://user-images.githubusercontent.com/41746087/43266626-273b219c-90ec-11e8-81cd-9da8530072d4.png)

**Comment by TheTopCz** [comment]
The error occurred when importing from version 2.6.7.0

**Comment by Zrips** [comment]
e80f929d0454febc68f71aab38fc5bfe60906599
