### ISSUE TITLE
Feature request: earning more claim blocks

### ISSUE THREAD

**Issue by gerardvanschip** [Zrips/Residence#175]
While waiting for your plugin to be updated to 1.13 I had to use Griefprevention in the meantime. Just to tie us over and me and my players forgot how nice it is to have a simple build in block earning system like griefprevention has.

My question to you, could you add that as a feature? Something we can switch on or off. Or even make it an addon which I happily pay for.

**Comment by Zrips** [comment]
Residence is based on economy, so by earning money you are earning blocks you can use to expand your residence. Its quite deprecated thing to add, some system which would reward you with some extra blocks while its can be done with simple payments.

**Comment by Zrips** [comment]
https://github.com/Zrips/Residence/issues/150
