### ISSUE TITLE
TPS drop with Residence4.8.0.2Experimental

### ISSUE THREAD

**Issue by gerardvanschip** [Zrips/Residence#181]
First off, ZERO complaints. Love the plugin and the early release which a lot of devs dont do!

That said, want to help to get it working right.
Using Residence4.8.0.2Experimental with Spigot git-Spigot-2b0e71c-7c341e9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Claiming, expanding, shrinking, etc all seem to work ok. Console is not showing errors but there is a big drop in TPS.
- without residence 19.80 TPS
- with residence within 2 minutes of starting the server, it drops to 18 TPS
- within 6 hours TPS will be around 16 and keep dropping till its our 24 hour server restart

Is there anything I can do to help? The log files show no errors. I looked in the config and did not see an option for debug.

**Comment by Zrips** [comment]
This should be some what fixed by now, report if issue still present for you
