### ISSUE TITLE
1.13 - Some settings wont have any effect on the plugin

### ISSUE THREAD

**Issue by Baktus79** [Zrips/Residence#184]
Hey

I see that some settings done in either groups or config file wont work. I will test this out further but for now I can report about `IgnoreY: true`. It wont select from top to bottom. 

And groups doesnt seem to work unless I add a player manually to
```YML
GroupAssignments:
     baktus_79: default
```
No errors or warnings are showing in the console.

**Residence version:** 4.8.0.2
**Server Type:** Paper
**Server version:** git-Paper-146 1.13-R0.1-SNAPSHOT

**Comment by Baktus79** [comment]
You where completly right. Everything is working correctly, and the one thing I really overlooked was a perm that ignores the Y setting in the config :( Feel so stupid. 

Thanks for pushing me on the right path @smmmadden

**Comment by smmmadden** [comment]
no worries, glad I was able to steer you in the right direction to resolve it. :-)
