### ISSUE TITLE
move=false can create trapped player

### ISSUE THREAD

**Issue by mb243** [Zrips/Residence#19]
When a player is set to NoMove and falls into a protected area, they are continuously teleported back to their entry point above the claim in a neverending loop, which not only can't be rescued from, but the game client keeps re-grabbing keyboard and mouse focus. Very bad. :(

The only way out is currently to fly out if you're in creative, but if you're in survival, it's a bad day.

Residence version 4.6.1.3

**Comment by mb243** [comment]
This appears to be related to the 'MoveCheckInterval' check, which is 500ms by default. Raising this would give the player longer to react, but wouldn't solve the issue of them getting teleported back to the spot above the residence where they fell in, creating the loop. The ideal solution here would be to either:

1. Teleport them to a spot on the ground outside the residence (most desirable), or alternatively
2. Teleport them to the location specified in 'KickLocation'

**Comment by Zrips** [comment]
This is know issue and will try to come up with some work around to prevent stuck players. Wait for next build.
