### ISSUE TITLE
Trident Duplication Bug

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#194]
Throwing a trident with or without enchants in a residence with the nodurability flag set to true duplicates the trident! 

Using Residence 4.8.1.0 with git-Spigot-145a37a-3123a06 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT).

**Comment by Zrips** [comment]
c6b36a598e1944e80d379a64d771cc0863bd5d7b

**Comment by blek-id** [comment]
Still happening on 4.8.7.4
Trident has these enchantment:
Channeling
Impaling 5
Loyalty 3
Unbreaking 3
