### ISSUE TITLE
Trap doors & fences doors aren't protected with "use" and "door" flags

### ISSUE THREAD

**Issue by Bagman96** [Zrips/Residence#195]
Hello,

I want to submit a problem to #protect areas with "use" or "door" flags that don't work with fences barriers and with tap doors (we can use it with "use : false", but it works fine with classic doors), i thinks i't cause of recents colors updates of these in MC 1.13.1.

Thanks in advance, you realy do a great job, i'ts a very nice plugin ;)
Have a nice day

**Comment by RescoolCZ** [comment]
I have the same problem

**Comment by eightbitx** [comment]
Issue is also present in Residence version: 4.8.1.0
Using Paper version git-Paper-"f188863d" (Aikar's Async Chunk Gen beta)

**Comment by ACluco1** [comment]
I have the same problem, players can use Oak Fence Gate, Oak Door and wooden trapdoor.. Im using Spigot 1.12.2 on my server and residence version is 4.8.0.2

**Comment by Zrips** [comment]
This is fixed now
