### ISSUE TITLE
Hooking up Residence with a custom Economy plugin

### ISSUE THREAD

**Issue by duplxey** [Zrips/Residence#196]
Hello,

I'm running a custom economy plugin on my server and I'm trying to hook it up with Residence. I went through the API but there's no way to set Main's 'economy' field to my own (Class that implements EconomyInterface). I also tried it using reflection, but it throws an error: http://prntscr.com/kurtfy

Have a nice day,
Nick

**Comment by Zrips** [comment]
You can always utilize Vault as bridge for residence and your economy plugin. Other then this you will need to have class which implements EconomyInterface and then replace economy variable in main residence class with yours
