### ISSUE TITLE
Residence breaks EditableSign plugin

### ISSUE THREAD

**Issue by eightbitx** [Zrips/Residence#199]
Residence version 4.8.1.0
Paper version git-Paper-"b666ff53" (Aikar's async chunk gen beta)
EditableSign version 4.2.0

When Residence is installed, EditableSign throws an error when clicking on a sign to edit it. EditableSign plugin: https://www.spigotmc.org/resources/editablesign.2502/

**Comment by Zrips** [comment]
If this is still an issue, repost it and include actual error message
