### ISSUE TITLE
[Bug] Shulkers are not protected

### ISSUE THREAD

**Issue by Baktus79** [Zrips/Residence#201]
I have noticed that shulkers are not protected in a claim with the flag container=false.

**Residence version:** 4.8.0.2
**Server Type:** Paper
**Server version:** git-Paper-279 (MC: 1.13.1)

**Comment by eightbitx** [comment]
Issue is also present in **Residence version:** 4.8.1.0
Using Paper version git-Paper-"f188863d" (Aikar's Async Chunk Gen beta)

**Comment by Baktus79** [comment]
Oh god, typed in the wrong version number :D I am also using the 4.8.1.0 :D

**Comment by Zrips** [comment]
Will be fixed with next update
