### ISSUE TITLE
AntiGreef enabled on any overworld coord  - paperspigot 1.13.1 and version 4.8.1.0 

### ISSUE THREAD

**Issue by haugsvar** [Zrips/Residence#203]
With Paperspigot 1.13.1 and residence version 4.8.1.0, default config and no created residences:

Water and lava willl not flow and dispensers does not dispence water on any overworld coordinates.

Disabling the respective AntiGreef settings in the config file establishes flows as expected.

**Comment by Zrips** [comment]
AntiGreef is to prevent water flow outside residence areas. There is option for that too.
