### ISSUE TITLE
resadmin deletion gives the admin the refund

### ISSUE THREAD

**Issue by eightbitx** [Zrips/Residence#207]
If an admin deletes a claim, they get the money. It should go to the player who created it & for server owned claims it probably shouldn't involve money at all.

**Residence version:** 4.8.1.0
Using Paper version git-Paper-"f188863d" (Aikar's Async Chunk Gen beta)

**Comment by Zrips** [comment]
84b9c13bf46d2f5d2a75f05156c72c5da2dd374e
