### ISSUE TITLE
Players can create claims within WorldGuard regions 1.13.1

### ISSUE THREAD

**Issue by eightbitx** [Zrips/Residence#209]
Residence is not supporting WorldGuard like expected. Players can create residences within/overlapping WorldGuard regions.

**Residence version:** 4.8.1.0
**Worldguard version:** 7.0.0-SNAPSHOT;1745-e43daa7
**Paper version:** 1.13.1 git-Paper-"63f95962" (Aikar's async chunk gen beta)
**Config:** https://pastebin.com/pMaQti1r

**Comment by Zrips** [comment]
This should be fixed currently.
