### ISSUE TITLE
Sponge

### ISSUE THREAD

**Issue by ArcasCZ** [Zrips/Residence#21]
Hello there!

I want to ask you if you can port Res to Sponge API?

**Comment by Darkfield** [comment]
Hello, nobody is using Sponge mate. Would be just wasted time porting to it.

**Comment by ArcasCZ** [comment]
But it's only one chance to make modded server on higher version than 1.7.10...

**Comment by Darkfield** [comment]
Spigot is up to latest version - any version.

**Comment by ArcasCZ** [comment]
But Spigot is unusable for modded servers, 'cause there's no implementation of Spigot into Forge server... There is Thermos / KCauldron, which allows run Spigot plugins and Forge mods at once, but last version is 1.7.10.

**Comment by smmmadden** [comment]
that is correct, you have to use Sponge or Forge for modded worlds.  Then you have to use plugins made specifically for Sponge/Forge (https://forums.spongepowered.org/c/plugins/plugin-releases).  What you're asking is to build residence for Sponge/Forge so it can be used in a modded world.  The answer provided is that it would take too much effort with very little gain to justify the time/cost to make it.

**Comment by Zrips** [comment]
Agreed to smmmadden. All this work involving remake of entire plugin to support completely new platform would cost allot of time and in most cases different platform don't have same API or same possible features as another ones, so it would be completely different build of residence for Sponge than for any other non moded server. If there was stable official version of moded platform which would definitely survive, as Sponge could at any time just close its project, then i could spend all this extra time remaking everything.
