### ISSUE TITLE
moneycharged message wrong format for currency

### ISSUE THREAD

**Issue by eightbitx** [Zrips/Residence#210]
The formatting for currency variable in the moneycharged and moneyadded messages are different. One says "$x,xxx.xx" and the other says "xxxx.x" - no dollar sign, no comma, and no cents place.

**Residence version:** 4.8.1.0
**Paper version:** 1.13.1 git-Paper-"63f95962" (Aikar's async chunk gen beta)
**Image:** https://imgur.com/qM0RjfU
**Language file**: https://pastebin.com/C6HPyAbu

**Comment by Zrips** [comment]
Will be fixed with next update
