### ISSUE TITLE
"build" flag doesn't give "destroy" perms

### ISSUE THREAD

**Issue by eightbitx** [Zrips/Residence#212]
Players with "build" flag are unable to break blocks.

Residence version: 4.8.1.0
Paper version: 1.13.1 git-Paper-"63f95962" (Aikar's async chunk gen beta)
Flags config: https://pastebin.com/NEcv0g3Z

**Comment by Zrips** [comment]
Because they need to have Destroy flag. they are separate ones depending on what you want to give for players.
