### ISSUE TITLE
/res market bug

### ISSUE THREAD

**Issue by WHiZSTA** [Zrips/Residence#214]
bug on using /res market list rent

29.09 12:27:57 [Server] ERROR Exception when SirEdrick attempted to tab complete res market list 29.09 12:27:57 [Server] INFO org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/res market list' in plugin Residence v4.8.1.0 29.09 12:27:57 [Server] INFO at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:144) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at org.bukkit.command.Command.tabComplete(Command.java:90) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:217) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabCompleteCommand(CraftServer.java:1690) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabComplete(CraftServer.java:1662) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:68) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:379) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:514) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161] 29.09 12:27:57 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d] 29.09 12:27:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161] 29.09 12:27:57 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 2 29.09 12:27:57 [Server] INFO at com.bekvon.bukkit.residence.text.help.HelpEntry.getSubCommands(HelpEntry.java:286) ~[?:?] 29.09 12:27:57 [Server] INFO at com.bekvon.bukkit.residence.utils.TabComplete.onTabComplete(TabComplete.java:22) ~[?:?] 29.09 12:27:57 [Server] INFO at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:132) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]

**Comment by Zrips** [comment]
Will be fixed with next update
