### ISSUE TITLE
Flag Crossover Issue

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#217]
There's currently a pretty serious issue with flags, especially noticeable when using the GUI but I think it also affects flags when setting with commands. 

I'm not getting any errors on it and it's hard to tell exactly what's happening, but there is some crossover between residences. For example, if one player sets flow to true, flow is also turned on in a different player's completely unrelated residence. If the second player turns it off, it's turned off again in the first residence. Neither has perms to change flags in the other residence.

Some are also reporting that flags aren't saving, although I think this is more likely due to what I described above. One player says she keeps turning monsters off and comes back the next day and the monsters flag is set to true again without having changed it. 

I feel like we've had this issue crop up before, but it was only occasional.  Really hard to tell, but it wasn't noticed to this degree until the update to 1.13.1.

This is for Residence 4.8.1.0 on the latest Spigot 1.13.1, and yes I know there's a 4.8.2.0 now and I haven't had a chance to test it but didn't see flags listed in the changelog. I'll update this when I have a chance to test on 4.8.2.0.

**Comment by Zrips** [comment]
Any chance for some additional information? Like residence names for both residences which suffered this cross over flag setting?

**Comment by mercurialmusic** [comment]
> Any chance for some additional information? Like residence names for both residences which suffered this cross over flag setting?

When I witnessed it happening with the flow flag mentioned it was between a subzone, "ocean.storage", and the other player's "A-Corp" (main residence). In case it's useful here's the residences file for that world: https://hastebin.com/suvukayefa.sql 

Would anything else be useful?

**Comment by Zrips** [comment]
Found possible cause, will push out new updated version today which should fix this issue.

**Comment by mercurialmusic** [comment]
I was unclear on GUI vs. commands (or if it mattered at all) but it did _seem_ more likely to happen when using the GUI. Thanks for looking into it!
