### ISSUE TITLE
Polygon selection/WorldEdit selection conversion

### ISSUE THREAD

**Issue by Pixelclone** [Zrips/Residence#219]
When using `/res select worldedit` to convert a polygon selection in WorldEdit to a selection in Residence, the polygon aspect is lost and the Residence selection becomes a square.

There is no dedicated function to selecting multiple points/creating a polygon in Residence so WorldEdit is used to make the polygon selection (`//sel poly`) and then the selection is copied into Residence using `/res select worldedit` but the selection fails to remain a polygon.

**Comment by Zrips** [comment]
Residence works on squares and not on polygon's. So you cant have option to convert WE polygon into residence protection area as having support for polygons in residence would increase its calculation demands like 1000x times... So no go on this one.
