### ISSUE TITLE
Fly flag doesn't work correctly

### ISSUE THREAD

**Issue by Eredrim** [Zrips/Residence#22]
Hello, I have a problem with the fly flag. Normally, if a player has this flag, he should be able to fly on entering in the residence and fall on leaving. Actually it doesn't work with me, this is how I tested.
I just kept the following plugins on my server :
- EssentialsX
- GroupManager (Essentials)
- PerWorldInventory
- Multiverse Core and Portals
- Vault
- Lockette
- WorldEdit
- WorldGuard
- WorldBorder
- Residence (obviously)

I go on the server like a lambda player (no fly permission, no op, etc.)
From the console, I type /res pset resname playername fly true
And at this step, there are two cases :
Either I am in the residence when the command is executed and I got the fly but without limit. I can leave the residence, go anywhere and even use teleportation.
Or I am out of the residence during command execution and I can't fly at all.

I hope you could help me.

**Comment by Oruss7** [comment]
Any news ?

**Comment by Zrips** [comment]
Working on this to be addressed as originally it was aimed to be only for residence and not per player flag what is causing some strange issues.

**Comment by Zrips** [comment]
Should be fixed with next build
