### ISSUE TITLE
help me Residence 4.8.3.0

### ISSUE THREAD

**Issue by MCScorpions** [Zrips/Residence#220]
good day in console running bug for purchased residence [17:00:41 ERROR]: Could not pass event BlockPhysicsEvent to Residence v4.8.3.0 org.bukkit.event.EventException: null at org.bukkit.plugin.java.JavaPluginLoader $ 1.execute (JavaPluginLoader.java:308) ~ [minecraft_server.jar: git-spigot-f6a273b-db10914] and I do not know what I thank in advance for your help

**Comment by Zrips** [comment]
f47342792000031c430604ba417b5d3a937f9e27
