### ISSUE TITLE
Question: How to stop allowing players tp to their claims?

### ISSUE THREAD

**Issue by lifehome** [Zrips/Residence#226]
As topic, this is very un-natural to a vanilla-like server...

**Comment by Oruss7** [comment]
Hi,

Use 
```
FlagPermission:
    tp: true
```
Only resAdmin will be permits to change this flag.

Then 
```
  ResidenceDefault:
    tp: false
```
to set default false.

**Comment by Zrips** [comment]
You could simply negate residence.command.tp permission node or disable tp flag usage and set it to false by default
