### ISSUE TITLE
Please help with the residence I bought from you

### ISSUE THREAD

**Issue by MCScorpions** [Zrips/Residence#227]
here is the link to the error in the residence, thank you in advance in the worst case I'm waiting for the repair in the new update here you have a link to the bug in the console https://hastebin.com/emujudakaj .pl in advance thank you for your help and help

**Comment by Zrips** [comment]
Will make some adjustments, but its quite specific issue which doesn't seem to be common in normal situations. Can be related to custom world map generator of some sort.
