### ISSUE TITLE
/res auto issue

### ISSUE THREAD

**Issue by arturek1666** [Zrips/Residence#233]
plugin Version: 4.8.3.1 same issue on Residence4.8.4.4 just to say it :)
paperspigot 1.13.2

Hi,

I have a problem as the command /res auto (name) (radius) don't work properly, why even if i do 
/res auto testing 50 it will not give me region 50x256x50 but it will give me the max possible region with is 300x256x300. Yes I have economy enabled. And yes player has enough money to get max region but he wanted to have 50x256x50 :(. Think that radius don't work

**Comment by user127001** [comment]
I confirm this. Variable ```radius``` just ignored and created residence have size max allowed minus 1 block ([issue #234](https://github.com/Zrips/Residence/issues/234))

**Comment by arturek1666** [comment]
Also I had find that if you have nofall on region when you have totem in your inventory it will use the totem by they way xD. Not sure if it's because I use CMI function:
Totem:
  # When this set to true, on players death totem will be used even if he is not holding it in hand
  RemoveFromInventory: true

But wanted to say that as well :)

**Comment by arturek1666** [comment]
The issue: (issue #234) has nothing to do with this post as issue is not fixed.

**Comment by Zrips** [comment]
e5219694ffbffa2219626b4a5b1ef1b88bd9888a
