### ISSUE TITLE
[BUG] /res auto incorrect calculation

### ISSUE THREAD

**Issue by user127001** [Zrips/Residence#234]
Hello!

If group in ```group.yml``` contain:
```
MaxEastWest: 16
MaxNorthSouth: 16
MaxUpDown: 16
```
Then ```/res auto``` will create 15x15x15

If group in ```group.yml``` contain:
```
MaxEastWest: 17
MaxNorthSouth: 17
MaxUpDown: 17
```
Then ```/res auto``` will create 16x16x16 etc.

Regards.

**Comment by Zrips** [comment]
With next update this should create correct size
