### ISSUE TITLE
Flags not working as expected on **1.13.2** offline-mode server

### ISSUE THREAD

**Issue by austinhuang0131** [Zrips/Residence#235]
Yes I'm the guy who wrote #23 

* Residence 4.8.3.1
* Spigot 1.13.2
* Offline mode
* `OfflineMode` is `true` in config.yml
* Tried turning `UUIDConvertion` to `true` also, changes back to `false` upon restart
* Uses PEX, `default` group has permission `residence.group.default`

Say there's a residence called `example`. When I do `/res set example move false`, no one can enter the residence, which is as expected. However, when I do `/res set example door true` or `/res set example container true`, no one can open doors nor open chests other than myself (OP), **even if** `/res check example door/container <username>` returns true. **They're not told by the plugin that they don't have door/container permissions.**

`gset` doesn't work either, but `pset` works fine.

**Comment by Zrips** [comment]
This should be ok with latest builds.
