### ISSUE TITLE
Can't add custom flags

### ISSUE THREAD

**Issue by Indyuce** [Zrips/Residence#240]
Hey,

I am working on integration with Residence and can't manage to add register flags. I've added
`FlagPermissions.addFlag("test");` to the onEnable() of my plugin and can't find that flag anywhere, neither in the flags list using `/res flags` nor in the `/res set` menu. Have I done sth wrong or is it a bug?

I am currently running Residence 4.8.3.1 on a 1.12.2 spigot server.

**Comment by Zrips** [comment]
You dint do anything wrong and its not a bug in particular. Currently residence only shows preset flags, custom flags will not appear in flags list even tho it still gonna work and residence will have this flag set to the residence. Will try to come up with some better way to handle things like that with next update.
