### ISSUE TITLE
How to resize a residence without expand / contract

### ISSUE THREAD

**Issue by AntoineHrn** [Zrips/Residence#242]
Hello

I saw there was a residence.resize permission but I cannot figure what it is its use.
I hoped it would permit a resize command so users don't have to repeat expand / contract commands but I can't manage to find this command. So is there a way to resize with a stick ?
Thank you.

**Comment by smmmadden** [comment]
While you are standing in the residence, you can use the /res expand ## where ## is how many blocks you want to expand in the direction you are facing.  It would get repeated as needed in all four (N, S, E, W) if you choose.  The opposite is using the /res contract ## with the same details.

**Comment by AntoineHrn** [comment]
You haven't read my question lol. I was looking for another way to resize the residence. Not the expand / contract commands.

**Comment by smmmadden** [comment]
actually I did but the only way without these commands is to remove and re-create the residence with the size you need.  The expand/contract parameters were designed to let players increase/decrease each direction if they wanted.  The developer is looking into the issue though to see why its throwing exceptions (which I can reproduce).  Though a resize option would be nice to maintain the shape but expand/contract all four at once.

**Comment by AntoineHrn** [comment]
Yeah it would be really useful. So what is the use of the residence.resize permission ? Does it give the permission to both expand & contract commands ?

**Comment by smmmadden** [comment]
yes, for the expand/contracts.  You can get more details on [wiki here](https://github.com/Zrips/Residence/wiki/Permissions)
