### ISSUE TITLE
Question: How to hide flags from GUI and altering market signs

### ISSUE THREAD

**Issue by AsaAlv** [Zrips/Residence#244]
Hi, 

I've been playing with residence for some hours now and there are a couple of things I can't figure out. Maybe simply cause its just not possible. But I thought to just ask in the hope that I'm wrong. 

1. Is it possible to hide flags from the gui to only show the ones that a player have permissions on? In other words I want to be able to only allow a few of the flags and the rest should preferably not be visible to the player. It gets to cluttered in the gui. 

2. Market signs have 4 rows that according to the language file should be possible to alter:

RentedTopLine: '%1'    
RentedPriceLine: '&8%1&f/&8%2&f/&8%3'    
RentedResName: '&8%1'    
RentedBottomLine: '&1%1'

The 2 bottom ones are fine to alter. But RentedTopLine and RentedPriceLine doesn't change whatever I try. It just seems like the code doesn't even look at those 2 parameters.

**Comment by Zrips** [comment]
Flag list in Gui should include only those flags which ones you can actually change. In example /resadmin set will return allot more flags then regular /res set
For signs lines, in general RentedTopLine is deprecated as Sign_RentedAutorenewTrue and Sign_RentedAutorenewTrue will be used, but will make it work too, as we already have it.
for second line, yea, its a bug will make it pick correct line when residence is rented
892cd29c44be15f3e1f48e35debc79fdd640fc4f
