### ISSUE TITLE
Can't create residence with worldedit

### ISSUE THREAD

**Issue by Eredrim** [Zrips/Residence#247]
Hello,

I have a problem when I want to create a Residence. I select two points with Worldedit and when I type `/res create resname` I have the error 'You must select two points before using this command'.

I tried with the latest Residence version (4.8.4.2) and a minimal server running only essentialsX, GroupManager, Vault, Worldedit and Residence. I tried with WorldEdit 7.0 beta 4 and with the latest snapshot version (build 3997).
There is no error displayed in the console.

Regards

**Comment by Eredrim** [comment]
Problem found and fixed. Please merge https://github.com/Zrips/Residence/pull/270

**Comment by Zrips** [comment]
There was an issue with we selection tool detection, but in general residence never recognized directly we selections, you have to perform /res select worldedit before you can use world edit selection. Residence selection and world edit selections are different things while residence can take we selection if you would perform command before hand

**Comment by Oruss7** [comment]
So, WE selection is now reserved for admins ? I don't see players taping `/res select worldedit ` command.

**Comment by Zrips** [comment]
Will have a look at that tomorrow and make it "old" way
