### ISSUE TITLE
Residence cannot be load

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/Residence#250]
Server version: 1.12.2 Spigot
Worldedit: FastAsyncWorldEdit (FAWE) lates version https://empcraft.com/fawe/download/?bukkit
Worldguard: 6.2.2

Residence v4.8.4.3

Error here:
https://hastebin.com/ikisimuyur.md

**Comment by Oruss7** [comment]
Duplicate https://github.com/Zrips/Residence/issues/249. Please read my comment

**Comment by TheTopCz** [comment]
Resolved in version
4.8.4.4
