### ISSUE TITLE
Residence Selection/Expansion Error

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#251]
So I know why this is happening: https://pastebin.com/Y9j2cRb0

It's happening because I'm a dumbass who uses FAWE/FAVS and for some reason their version of WorldGuard because they can't make FAWE play nice with regular WorldGuard and it's taking them forever to fix the loads of problems they're having. It's been fun.

Am I basically screwed without going to real WE/WG? 

Using 4.8.4.4 with git-Spigot-f56e2e7-4385562 (MC: 1.13.2)

**Comment by tianji1993** [comment]
got same problem here, maybe add an option to allow residence use which version WE API is a good idea.

**Comment by muzyeh** [comment]
me too ... help~~

**Comment by momoservertw** [comment]
I have this problem too.

In addition, when I use the stick to select the area, it will show out this error message.
https://pastebin.com/kUsWygNR

**Comment by tianji1993** [comment]
@Zrips could you check this, please?

**Comment by mercurialmusic** [comment]
@tianji1993 Well, really, at this point he shouldn't. FAWE announced not long ago that they're (rightly) abandoning their attempts at a standalone WE and have started work on a compatible plugin (as it was pre-1.13). The FAWE devs have also said on their Discord, straight up, that you shouldn't be using FAWE in its current state due to significant chances of chunk corruption. 

Any work that Zrips would do at this point to make Residence compatible with FAWE would be pointless. Closing this issue for now since there's not much he can do about it. I highly recommend going back to traditional WE for now.
