### ISSUE TITLE
Issue with ProCosmetics and Residence

### ISSUE THREAD

**Issue by TopicDogg** [Zrips/Residence#253]
Hello, I'm having an issue with ProCosmetics where when a player that has multiple cosmetics equipped teleports to an area claimed with a Residence the server stops responding.

**Plugin Version**: 4.8.4.4
**ProCosmetics Version**: 5.6
**Server Platform**: Spigot
**Server Version**: git-Spigot-f56e2e7-07e504c
**Client Version**: 1.13.2
**Java Version**: openjdk 10.0.2
**How to reproduce**: Equip multiple cosmetics, teleport to a residence in unloaded chunks
**Error**: https://paste.ubuntu.com/p/m8NTTvBJHF/

I also reported this in the ProCosmetics Discord

**Comment by Zrips** [comment]
This should be handled and optimized by ProCosmetics plugin. i cant really do anything about it from my end. It should be related to PlayerInteractEvent and ProCosmetics firing it manually to many times in short period or something between those lines. And if this error is when you are teleporting to unloaded chunk, then simply inform ProCosmetics to fire PlayerInteractEvent couple ticks later to allow chunk to be loaded before they doing that strange thing. Or even better, they should check if chunk is loaded before they sending interact event. In short, issue is with ProCosmetics plugin.
