### ISSUE TITLE
Feature request: Configurable/Localized language strings

### ISSUE THREAD

**Issue by SlimeDog** [Zrips/Residence#254]
Residence 4.8.4.4 and previous

- Please support configuration of more internal strings, such as _Server_Land_ for server-owned residence plots. All in-game and log/console strings should be localizable.

**Comment by SlimeDog** [comment]
and subplot names. Current functionality:
> resadmin subzone BuildSites A0

becomes
> BuildSites.a0

in res_world.yml, and cannot be changed. If I stop server, edit the file to capitalize the names, and restart, they revert to lowercase.

**Comment by Zrips** [comment]
4c34d1f9426a3752510a6f5311a679da6445c761

**Comment by SlimeDog** [comment]
Confirmed Server_Land localizable in R 4.8.4.5; thank you.
