### ISSUE TITLE
Duplicate chat output

### ISSUE THREAD

**Issue by SlimeDog** [Zrips/Residence#255]
With _Global.ActionBar.General:false_, enter and leave messages are posted to chat twice. Did I miss a configuration option?

**Comment by Zrips** [comment]
Could you elaborate on server version? As this doesn't seem to be issue on 1.13.2 servers

**Comment by SlimeDog** [comment]
Spigot 1.13.2

However, I have changed configuration since reporting this issue. It does not happen with my current configuration. I should have posted the configuration at the time. :(

**Comment by Zrips** [comment]
Will close this one for now. If issue persists give me know.
