### ISSUE TITLE
Subplot names converted to lowercase

### ISSUE THREAD

**Issue by SlimeDog** [Zrips/Residence#256]
Spigot 1.13.2
Residence 4.8.4.4

Subplot names are converted to lower case when typed, and again when server is shut down. For example:
> resadmin subzone BuildSites A0

becomes
> BuildSites.a0

in-game, and is saved that way res_world.yml. If I stop server, edit the res_world.yml to capitalize the names, and restart, they are as I typed them, but when I stop the server, they again revert to lowercase.

Please leave them as typed in-game (or manually edited in file).

**Comment by Zrips** [comment]
4feff0a883544b5361562221a35e0d5a659987fd

**Comment by SlimeDog** [comment]
Confirmed fixed if R 4.8.4.5; thank you.
