### ISSUE TITLE
Bug with name in Residence

### ISSUE THREAD

**Issue by Filip1004** [Zrips/Residence#261]
Hello,
I found a bug in the Residence plugin: When someone has a name with capital letters (e.g. Filip), it gets changed next day to completely lowercase (filip). The owner of the residence then has no access to his protected region.
Is there any way how can I get this fixed?

I use Residence with version 4.7.8.2 on Spigot 1.8.8

**Comment by Zrips** [comment]
Its quite outdated version, newest version doesn't have this issue.
