### ISSUE TITLE
Op Players cannot bypass and all the configs changed all of suddent.

### ISSUE THREAD

**Issue by iliquide** [Zrips/Residence#264]
Hello
We are running the last version of residence on our server 1.13.2, since months, we never had any problems. Then our VM drive got full, so some crashes occured, since in residence op player cannot bypass, like usual, all the config reset. Some config.yml and groups.yml get cloned. Any idea what we could do ? .... without losing the residence of over 6k players ? Thank you for you Help.

**Comment by Zrips** [comment]
You have backup folder for situations like this one, which saves all essential files in it. So you will not loose data, you will only suffer some rollback depending on what you have set in your config file.
