### ISSUE TITLE
Residence cannot be load

### ISSUE THREAD

**Issue by Iziiiiii** [Zrips/Residence#269]
Server version: 1.12.2
Residence version: Residence4.8.4.4

Error: https://pastebin.com/fTgHbUs6

**Comment by smmmadden** [comment]
According to your log on line one, you are not using 4.8.4.4
[16:01:59 INFO]: [Residence] Enabling Residence v4.6.3.1

**Comment by Iziiiiii** [comment]
Sorry, https://pastebin.com/16QdFgwp

**Comment by smmmadden** [comment]
is this an upgrade from a previous version (4.6.3.1) or earlier?  Could you post the full startup log if you're not able to tell what else might be causing it?  First step is to rule out conflicts with other plugins and/or startup errors, exceptions & warnings.
