### ISSUE TITLE
Residence / LuckPerms - You dont have permission for this

### ISSUE THREAD

**Issue by PRM85** [Zrips/Residence#275]
Hello,

I am running a Paper 1.13.2 server (Build 564)
I currently only have two plugin running.  LuckPerms and Residence (paid for)

When running admin commands in Residence I get the "You don't have permissions for this"
Within LuckPerms my user account is in the owner group which have access to the following node 'residence.*'

I've read though the wiki and can't seem to figure out what I am doing wrong.

I have also tried with the 'residence.admin.*' node also.

I am fairly new to this so apologies if the solution is obvious.

**Comment by El-pika** [comment]
Tried to /resadmin ? 
The *admin* commands are just /resadmin instead of /res

**Comment by Zrips** [comment]
As @El-pika said, admin commands usually requires you to use /resadmin instead of /res command. Which bypasses some of the check if you have access to admin command in general.

**Comment by stepa7521** [comment]
what permission is on sizes/max size in luckperms and how to make so i dont have to pay with vault money for the residences
