### ISSUE TITLE
Build failed because of iConomy6.jar is unavailable

### ISSUE THREAD

**Issue by CBM1014** [Zrips/Residence#277]
I ran command `ant` in the project's root folder, then build failed because of a file which is not available.

> class:
>       [get] Getting: https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/lastSuccessfulBuild/artifact/Essentials/target/Essentials-2.x-SNAPSHOT.jar
>       [get] To: /var/lib/jenkins/jobs/Residence/workspace/lib/Essentials.jar
>       [get] Getting: https://cdn.getbukkit.org/spigot/spigot-1.12.2.jar
>       [get] To: /var/lib/jenkins/jobs/Residence/workspace/lib/Bukkit.jar
>       [get] Getting: http://towny.palmergames.com/file-repo/iConomy/5.0.1/iConomy.jar
>       [get] To: /var/lib/jenkins/jobs/Residence/workspace/lib/iConomy5.jar
>       [get] Getting: http://ltcraft.lt/wp-content/uploads/2017/05/iConomy.jar
>       [get] To: /var/lib/jenkins/jobs/Residence/workspace/lib/iConomy6.jar
>       [get] Error opening connection java.io.FileNotFoundException: http://ltcraft.lt/wp-content/uploads/2017/05/iConomy.jar
>       [get] Error opening connection java.io.FileNotFoundException: http://ltcraft.lt/wp-content/uploads/2017/05/iConomy.jar
>       [get] Error opening connection java.io.FileNotFoundException: http://ltcraft.lt/wp-content/uploads/2017/05/iConomy.jar
>       [get] Can't get http://ltcraft.lt/wp-content/uploads/2017/05/iConomy.jar to /var/lib/jenkins/jobs/Residence/workspace/lib/iConomy6.jar
> 
> BUILD FAILED

**Comment by shawnanastasio** [comment]
Running into this issue as well. It seems all URLs in build.xml that reference ltcraft.lt are offline.

**Comment by Zrips** [comment]
Use basic export method for time being, build is broken at this moment
