### ISSUE TITLE
Skeleton weird glitch in residence

### ISSUE THREAD

**Issue by blek-id** [Zrips/Residence#279]
Skeleton in residence move very fast towards the player when they shoot an arrow. I'm using the latest Residence

**Comment by Zrips** [comment]
Can't reproduce. And i cant recall any code which would change entities speed or change its behavior in general while its in residence area.

**Comment by htAngryFace** [comment]
Don't think it's an issue with Residence. Just disabled all my plugins and Skeletons "heat-seek" while in/on farmland. If I'm in it they'll just continuously run towards me and go in circles. If I'm off farmland, they just go really quick until they're off.

Looks like it's a Minecraft or Minecraft + Spigot issue.

Sure scared the hell out of me when a skeleton came at me at Mach fucking 7... 😅

Video for documentation purposes:

* https://streamable.com/ugvj1

---

**Plugins:** (Sat about toggling Res flags and whatnot. Eventually disabled all plugins and it kept happening.)
`CoreProtect, LuckPerms, WorldEdit, ClearLag, PlugMan, WorldBorder, ChestSort, Multiverse-Core, ProtocolLib, WorldGuard, AdvancedPortals, EditableSign, CraftingStore, Multiverse-NetherPortals, Vault, Essentials, Towny, Jobs, Residence, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, DynamicShop`

**Spigot**:
`CraftBukkit version git-Spigot-c8d4cef-1fee35b (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)`

**Minecraft**:
`1.14 + preview_OptiFine_1.14_HD_U_F1_pre6`
