### ISSUE TITLE
[URGENT] Players can pull blocks out of residences with sticky pistons

### ISSUE THREAD

**Issue by DoNotSpamPls** [Zrips/Residence#28]
What the title says.

**Comment by smmmadden** [comment]
can you share the settings you have for piston, pistonprotection flags for the residence and player?
also what do you have for the same in flags.yml for ResidenceDefault or other group you're using?

**Comment by DoNotSpamPls** [comment]
This is my flags.yml: http://pastebin.com/G1Gr3DFw
This is my groups.yml: http://pastebin.com/79ZWuR6d

**Comment by smmmadden** [comment]
You do NOT have piston protection enabled.  Read the Wiki page on how to enable piston protection.

**Comment by DoNotSpamPls** [comment]
I have set both piston and pistonprotection to true in flags.yml, but yet when I create a new residence, I have to set it manually. (Yes, I have reloaded every part of the plugin with /res reload)
