### ISSUE TITLE
4.8.4.5 Initialization Error

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#280]
Residence 4.8.4.5 won't startup, getting this error:

https://gist.github.com/mercurialmusic/2c8eb676fe9f7593f9534443d2e9ad3c

Tried it both on the Spigot version I'm running successfully with 4.8.4.4 (CraftBukkit version git-Spigot-f09662d-7c395d4 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)) and on the latest, no dice either way.

**Comment by Zrips** [comment]
1a5e069008ecac9d045321d4da85a153fd7df2d6

**Comment by mercurialmusic** [comment]
You're too quick! :)
