### ISSUE TITLE
Paid product (not tampered with) not wanting to load on brand new FRESH server

### ISSUE THREAD

**Issue by WWDerek** [Zrips/Residence#281]
I have the following plugins: All EssentialsX, World Edit, World Guard, and Residence. The server starts fine with all plugins but residence, but when I try to launch with residence, it gives me errors. Here are all the errors from my log. Please help me, don't want this purchase to go to waste. https://hastebin.com/urugilihil.md

**Comment by Zrips** [comment]
Will be fixed today. Tho you do have issue with worldguard loading too. If you need it working now and cant wait until end of day, open flags.yml file and remove 2 spaces in from of RentedDefault section to be on same line as CreatorDefault
b58e2e80efabd22a35ed592b5e74531b80e74d9f
