### ISSUE TITLE
Stepping on a lot of pressure plate causes TPS to go down (Timings Provided)

### ISSUE THREAD

**Issue by blek-id** [Zrips/Residence#285]
Residence Version 4.8.4.7
Version according to CMI: Paper(614) 1.13.2-R0.1-SNAPSHOT
Timing:
https://timings.aikar.co/?id=6a0e22998be24496aa26079625a23104#timings

When a lot of player is walking over pressure plate, TPS goes down significantly. It doesn't matter if the pressure plate is in a region or not

**Comment by Zrips** [comment]
152453e8ff3db99cf3743003ca8001610984a83d
