### ISSUE TITLE
can't use /res set

### ISSUE THREAD

**Issue by alan67160** [Zrips/Residence#289]
can't use /res set

Version

> Residence4.8.6.2Experimental

Error 

> [WARN] [Residence] Plugin Residence v4.8.6.2 generated an exception while executing task 218

Plugin list

> CoreProtect, LuckPerms, WorldEdit, Essentials, EssentialsChat, PlaceholderAPI, betterSleeping, LumberJack, AutoMessage, ViaVersion, Vault, EssentialsSpawn, Multiverse-Core, ProtocolLib, WorldGuard, TitleManager, DiscordSRV, LockettePro, Residence, RandomTP, LiteBans, QuickShop

Server Version

> This server is running CraftBukkit version git-Spigot-1eece4f-5a37f43 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

**Comment by cheesepufftyler** [comment]
same here

**Comment by arturek1666** [comment]
same here :)

**Comment by alan67160** [comment]
Paper spigot version 11 fixed this issues

**Comment by arturek1666** [comment]
Oh paper spigot is out good good :) finally :)

**Comment by alan67160** [comment]
but paper spigot is more instability. I have run it one time then 11h whole VPS goes down because of memory overflow issues on paper spigot 1.14 build 11.

**Comment by Zrips** [comment]
1fb3e9043b8cf80456d027ee57931e8759858249
