### ISSUE TITLE
Feature request. Visualisation commands. Wiki update

### ISSUE THREAD

**Issue by user127001** [Zrips/Residence#292]
~~Please add extra commands to visualize the selected area and the already created residence.~~
Well. So please update documentation, because no one page in the wiki do not contain this command. I still do not know command that open GUI.

Best regards.

**Comment by Zrips** [comment]
We do have /res show already. What else do we need?

**Comment by user127001** [comment]
Edited

**Comment by Zrips** [comment]
if we are talking about flag set gui, then you have to enable it in config file and any time you are using something like /res set or /res pset without defining flag, gui will open will all options

**Comment by user127001** [comment]
Solved. Thank you!
