### ISSUE TITLE
Residence Doesn't Like Username Changes

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#294]
This has been around for ages but recently came up again. Not a huge deal, but would be nice if it can be fixed eventually. On an online Bungee with offline Spigot servers, having issues with name changes and the residences not recognizing the owner after a name change. UUIDs are normal vanilla and other plugins don't seem to be affected by name changes. Relogs and restarts don't seem to matter. I've been working around it by using the '/res give' command to give the player their residence. Players are not able to use the command themselves.

Using Residence 4.8.5.0
LuckPerms if it matters
Server version: CraftBukkit version git-Spigot-f09662d-3697519 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Thanks as always!

**Comment by Zrips** [comment]
Check your config file, OfflineMode should be set to true if you want to have support by players UUID instead of his name. Having it at false will check residence owner by name, not by his UUID.

**Comment by mercurialmusic** [comment]
It was true, but it looks like you may have done something with that in today's update, too. Will check it out, and thanks. Incidentally, I do have UUIDConversion set to false -- what is that and should that be true as well? The big scary "DONT change this if you are not sure what you doing" always made me leave that alone lol.

**Comment by mercurialmusic** [comment]
Nope, still issues with name changes in 4.8.6.3. Someone just changed their name today and got locked out.

**Comment by ZodoxMC** [comment]
hmm i wonder... normally
OfflineMode: False means its "online" so uses UUIDs
OfflineMode: True means its "offline" so it uses Names since UUIDs change with name changes
or not?

**Comment by Zrips** [comment]
@ZodoxMC 
When its set to true then residence owner will be recognized by players name and not by his UUID
