### ISSUE TITLE
Market Signs not working

### ISSUE THREAD

**Issue by cheesepufftyler** [Zrips/Residence#296]
Im running 4.8.6.2Experimental on spigot 1.14.   i have a subzone that is rentable and type /res market sign TheOreBoys_Spawn.subzone16   while looking at a blank sign. i get this:

12.05 05:26:47 [Server] INFO ... 17 more
12.05 05:26:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
12.05 05:26:47 [Server] INFO at com.bekvon.bukkit.residence.commands.market.perform(market.java:154) ~[?:?]
12.05 05:26:47 [Server] INFO Caused by: java.lang.NullPointerException
12.05 05:26:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:806) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:889) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:896) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.jar:git-Spigot-1eece4f-0d76f86]
12.05 05:26:47 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.6.2
12.05 05:26:47 [Server] Server thread/ERROR null
12.05 05:26:47 [Server] Server thread/INFO cheesepufftyler issued server command: /res market sign TheOreBoys_Spawn.subzone16

**Comment by Zrips** [comment]
6197280511a4881b12c9a0b20785d48261cca195
