### ISSUE TITLE
LuckPerms with Residence group not working

### ISSUE THREAD

**Issue by haer0248** [Zrips/Residence#297]
I set "residence.group.DonaterGroup" for donater group
but in-game the player still display "default group"
(the player have "residence.group.DonaterGroup" this permission node)
It's my problem or LuckPerms not supported? (LuckPerms save as MariaDB)

**Comment by user127001** [comment]
`...player still display "default group"`
Where you see it?

**Comment by user127001** [comment]
You created `DonaterGroup` in `groups.yml` of residence folder?

**Comment by haer0248** [comment]
Yes

**Comment by user127001** [comment]
Please write first 2 lines from result after using `/res auto`

**Comment by KamosRZ** [comment]
I have the same problem. Everything was working untill today when I updated residence. Now people are in default.

**Comment by haer0248** [comment]
umm I mean
A player is **default group** it's correct, because A player doesn't have residence group any permission node
B player is **default group** but it's not correct, because B player has **residence.group.DonaterGroup** this permission node.
If permission node **residence.group.DonaterGroup** work, the player is **DonaterGroup** not **default**

Sorry my english is very poor, thanks!

**Comment by Zrips** [comment]
Tested out and it does seem to work correctly, keep in mind that group doesn't update instantaneously, but takes couple seconds. 
Your groups file would be nice to see too.

**Comment by Zrips** [comment]
074bf284a1bba263512ce72e18ff4e361d50a9c0

**Comment by krustymk** [comment]
Test it again but sleep in a bed, the player logs in and is in the correct group then returns to the default group after sleeping in a bed
