### ISSUE TITLE
Players can't remove they residence.

### ISSUE THREAD

**Issue by Straiker123** [Zrips/Residence#298]
Residence: 4.8.6.3
Server: Spigot 1.14.1
Players can't remove they residence with command /res remove <residence>.. no message, same problem have players with OP, /resadmin remove <residence> is only working.

**Comment by haer0248** [comment]
It's a bug
If update to **Residence-4.8.6.3**
**Old residence** the owner flag **admin** will be **REMOVE**

**Comment by Zrips** [comment]
2fcd9467010b495a784ba672e19d7b4654fb6dce
