### ISSUE TITLE
Players cant select

### ISSUE THREAD

**Issue by mpdk** [Zrips/Residence#300]
Our players cant select areas anymore, no errors. But nothing happens, I can see on spigot that we are not the only ones with the problem. Running latest release and latest spigot 1.14.1

And thx for a fantastic plugin.

**Comment by Zrips** [comment]
its quite wage description of issue. I need more information. Do you get any feedback message? Are you using correct selection tool? Can you destroy blocks with that tool?

**Comment by mpdk** [comment]
Sorry shrips, we figured it out, we changed item 280 to the name and it worked. sorry about that
