### ISSUE TITLE
/res remove command responds nothing and can't be used

### ISSUE THREAD

**Issue by smartmadio** [Zrips/Residence#305]
Residence version: 4.8.6.3
Server version: Spigot 1.14.1
When you use /res remove command,the residence responds nothing(no error message or the confirm message).

**Comment by cheesepufftyler** [comment]
same. also it can crash sometimes if you do /resadmin remove

**Comment by MercerK** [comment]
I'm having the same issue, have same residence version, but on 1.13.2.

`/res tp` doesn't seem to respect the "CanTeleport" in groups.yml as well.

**Comment by Zrips** [comment]
2fcd9467010b495a784ba672e19d7b4654fb6dce
