### ISSUE TITLE
Feature request:residence enter title message

### ISSUE THREAD

**Issue by tianji1993** [Zrips/Residence#307]
Could you add a flag "title"? if a residence has this flag set true, when a player enters this residence he/she will see a title message like this:
![image](https://user-images.githubusercontent.com/5179956/58369679-4851f800-7f30-11e9-8267-e52cebdb99c3.png)

Thanks!

**Comment by ZodoxMC** [comment]
Or overall a option to switch between titles and actionbar messages would work too i think (for most)

**Comment by Zrips** [comment]
2586110821dfdcd4fad96bd69323f97a4536a707
