### ISSUE TITLE
do not block players

### ISSUE THREAD

**Issue by jbbpt** [Zrips/Residence#308]
Hello, I select the home make /res create name_home is everything ok but then any player enters the house open doors chests destroy na construct the plugin does not block anything already tried several times erased everything from the server and still the same I have spigot 1.14.1 thanks

**Comment by ZodoxMC** [comment]
Have you checked for the corresponding flags?

**Comment by Zrips** [comment]
2fcd9467010b495a784ba672e19d7b4654fb6dce
