### ISSUE TITLE
/res set   which permission about it?

### ISSUE THREAD

**Issue by Bayminkk** [Zrips/Residence#314]
which permission about it?
player type /res set    click icon in GUI,but it respond "NO PERMISSION"
player type /res set residencename build t.  it respond "NO PERMISSION"
but player type /res set build t.  in his residence,it correctly going on,dont respond "NO PERMISSION"
SO..................

**Comment by Nety01** [comment]
You probably already solved this. Anyway for anyone who could have the same issue, you can set this in flags.yml. And if you want to allow another player (not-owner of residence) to change flags in a residence, the owner of the residence has to give him flag admin by command /res pset <player> admin true.
