### ISSUE TITLE
pls support utf-8

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/Residence#318]
can you support utf-8 for languages such as German, Turkish or similar

**Comment by Zrips** [comment]
Where exactly? As locale files should handle them as they should, residence files should handle that one too. So can you be more specific which place failed to process utf-8?

**Comment by HomeLandingsDE** [comment]
I have everything translated into German and umlauts are not displayed but replaced by symbols - if I switch to English is everything back to normal - hence the UTF-8 request
