### ISSUE TITLE
Fly bypass

### ISSUE THREAD

**Issue by arturek1666** [Zrips/Residence#319]
**Issue:**
Player can fly even if not in region with simple trick, for easy understanding there is a video
Video: https://www.youtube.com/watch?v=8FnT9pxHnqo&feature=youtu.be
**Plugin list:**
`Anti Commands Suggestions, 
AsyncWorldEdit-3.6.5, 
BottledExp2.2.6.0, 
ChatControl-8.2.4, 
CMI8.6.5.1, 
DropEdit2, 
Elevator, 
GlobalMarketChest-1.3.0, 
HeadDatabase, 
Jobs4.13.0, 
JupiterCore, 
LiteBans, 
LuckPerms-Bukkit-4.4.26, 
MobFarmManager1.5.1.3, 
OnlyProxyJoin 1-1-2, 
OreAnnouncer-2.1.0, 
PhantomSMP-1.1.1, 
PlaceholderAPI-2.10.2, 
PlugMan, 
ProtocolLib, 
QuantumShop 1.13+, 
RecipeControl-2.2.5, 
ReWorld, 
SkinsRestorer, 
Spartan, 
SpecializedCrates, 
Vault1.6.11, 
WorldBorder, 
worldedit-bukkit-7.0.0, 
worldguard-bukkit-7.0.1-beta-01, 
WorldGuardExtraFlags
`

**More info:**
Paperspigot 1.14.2
Residence4.8.6.4

**My residence config in case**
https://gist.github.com/arturek1666/4bae17a3245a05f23d9caea750175689

**Comment by Zrips** [comment]
Hmmm, watched that video couple times, still confused what you meant by saying that player can fly outside region. He should not be able too? Should it get disabled when he leaves?

**Comment by arturek1666** [comment]
That's the problem it dosn't disables when he leaves

**Comment by arturek1666** [comment]
If you are in region and you are flying in that moment and you type /res reset it will reset the flags and it will not disable fly for them, So now they can leave region and fly free everywhere

**Comment by Zrips** [comment]
Doe he have residence.flybypass?

**Comment by arturek1666** [comment]
Nope, they don't.

**Comment by arturek1666** [comment]
So old issue closing.
