### ISSUE TITLE
Res TP broken in 4.8.6.5

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#321]
The set teleport point is being overridden in 4.8.6.5 and it's teleporting everyone to the top and center of the residence, usually their roof. Setting a new /res tpset has no effect. Seems to happen more often on slabs or transparent blocks, but still happens on regular blocks as well. Didn't have any issues (that I know of) in 4.8.6.4.

Still on Spigot 1.13.2 if it matters.

Thanks!

**Comment by linbo10** [comment]
Me too! everyone use /res tp XXX ,teleporting to the top and center of the residence in 4.8.6.5 even if use /resadmin tpset

**Comment by blek-id** [comment]
can confirm

**Comment by mcpanglei** [comment]
me too

**Comment by Zrips** [comment]
d8c530cc7652a9731121ebdc09b2370a7223d86a
