### ISSUE TITLE
/res rt Does not work.

### ISSUE THREAD

**Issue by MikuSnow** [Zrips/Residence#323]
When i type '/res rt'
It tell me 'Could not find correct teleport location, please wait'

But, When i use old version, this command can work normal.

**Comment by Zrips** [comment]
Server version?

**Comment by MikuSnow** [comment]
spigot 1.12.2

**Comment by Zrips** [comment]
Cant really reproduce this issue at this point. Check your config file for possible issues, maybe you have minCoord set to a bigger number then maxCoord. If you are still having this issue, let me know.
