### ISSUE TITLE
PreventRemoval and /res lease renew not work

### ISSUE THREAD

**Issue by GodsCity** [Zrips/Residence#324]
1.config.yml/Rent:-PreventRemoval set true, owner still can remove a rented residence.
2./res lease renew, the command will cost money even reach max lease day

**Comment by xiarixing** [comment]
And another one, I found it today.
When you type command “/res market rentable <residence> <money> <rentdays> <true|false>”
rentdays can set to very large number, even large than groups.xml MaxRentDays !
My english is not good, I hope I made myself clear,fix it plz, this is a awesome plugin!

**Comment by xiarixing** [comment]
And,the rent system, it works well on its own.But if you add subzone system on it,it will lots of bugs, like the owner still have subzone's build and destroy permissions!

**Comment by Leonardo-Fiori** [comment]
> 1.config.yml/Rent:-PreventRemoval set true, owner still can remove a rented residence.
> 2./res lease renew, the command will cost money even reach max lease day

2) Me too! Thats annoying

**Comment by Zrips** [comment]
895124d4002db46956510371ddd651873fe709bf
e1b6858dc7820fe45724bdde09583815e2066e74

**Comment by Zrips** [comment]
10f955f896c1a2d3b0a59a33fa3ec00a3fd25494
