### ISSUE TITLE
/res tp cause exception

### ISSUE THREAD

**Issue by PhantomXN** [Zrips/Residence#325]
when players use /res tp or /res rt will sometimes cause spigot null and generate the following exception
[res1.txt](https://github.com/Zrips/Residence/files/3354843/res1.txt)
[res2.txt](https://github.com/Zrips/Residence/files/3354844/res2.txt)
and eventually cause spigot crash
here is the crash report
[res3.txt](https://github.com/Zrips/Residence/files/3354846/res3.txt)
what is the problem?

**Comment by Zrips** [comment]
This should be no longer an issue with 1.14.4 version
