### ISSUE TITLE
Trident can kill mobs/animals even if there is flag to prevnt killing

### ISSUE THREAD

**Issue by arturek1666** [Zrips/Residence#327]
I had notice that players can kill mobs and animals with **trident**, and yes players did use flag to prevent mobs and animals to get killed, but somehow the **trident** can kill anyway.
UPDATE:
Looks like the only way to stop player from killing animals mobs is to set shoot false however then even players added our even owner can't kill them with that item is there a way to fix that?
**Engine API:**
Paperspigot 1.14.3#127
**Residence:**
4.8.6.6

**Comment by Zrips** [comment]
e2fb82a81cd3f26dbf48f2fa14ec2e18afffef31
