### ISSUE TITLE
Enter/Leave Message - %Subtitle% wont work

### ISSUE THREAD

**Issue by jiubook** [Zrips/Residence#328]
Ver 4.8.6.6

config.yml:
>        Messages:
>            # Defines where you want to send residence enter/leave/deny move and similar messages. Possible options: ActionBar, TitleBar, ChatBox
>            GeneralMessages: TitleBar
>        ActionBar:
>            ShowOnSelection: true

Group.yml:
>        Messaging:
>            # Whether or not the player can change the Residence enter and leave messages.
>            CanChange: False
>            # The default enter message to apply to new Residences created by players in this group.
>            # Leaving the message blank will disable it.
>            DefaultEnter: oh! %player ! welcome ! %subtitle% Here is %owner 's %residence .
>            # The default leave message to apply to new Residences created by players in this group.
>            # Leaving the message blank will disable it.
>            DefaultLeave: %subtitle% You are leaving the %residence.

but "%subtitle%" does not work in the game，It will still display the title.

E.g “oh! Jiubook ! welcome ! %subtitle% Here is Jiubook 's special home .”

**Comment by Zrips** [comment]
Should it? I mean, it never been announced to support thing like this and there is no code which would process it in this way. 
ab9901dfec5529bf6d38af3ba45539c41b00b393
