### ISSUE TITLE
Written Book Bypass Container and Use Perm

### ISSUE THREAD

**Issue by CharlyZhu** [Zrips/Residence#332]
My players can use written book to open chest and use doors and lever etc in others' residence. Is this my config error or an plugin error.

**Comment by Zrips** [comment]
Cant reproduce issue. Player is not able to interact with chests, doors or levers without appropriate permission node even if you hold a book in hand, same with written ones. Try removing other plugins to rule out posible issue with compatibility, if that doesnt help, rename residence folder and allot for default files to be generated to make sure that issue disappeared, if so, then you have wrong setup.

**Comment by CharlyZhu** [comment]
Sorry, the error was fixed, it turned out to be an error within my plugin.
