### ISSUE TITLE
Doesn't block players from building.

### ISSUE THREAD

**Issue by 0Lou** [Zrips/Residence#338]
A player claims some land, but other players are free to build and destroy on that land
and even open chests, furnaces etc. It's like the claim isn't even there.

Version (1.14.4)

**Comment by mercurialmusic** [comment]
Post your flags.yml? Your default settings may be messed.

**Comment by Zrips** [comment]
@0Lou If you have player with OP mode or has all residence permissions, like flag bypass, then he can do anything he wants. Or residence itself is not properly set and protected with flags. Without more information we cant help out.
