### ISSUE TITLE
Adding option for storing data in MessagePack format instead of YAML

### ISSUE THREAD

**Issue by dalibor-drgon** [Zrips/Residence#34]
You know that loading time of YAML files ain't no nice on big servers with lot of residences. What about adding option to config to store data in [MessagePack](http://msgpack.org/) format. Not only it's a lot of faster but also way smaller. I may try to make Pull Request if you find it not a bad idea. Thanks

**Comment by Zrips** [comment]
Will do some extra research on that, but from first look it looks like good idea to move to this type of data storage.

**Comment by dalibor-drgon** [comment]
As I am looking into various formats, if you want maximum performance, then it may be good to move into something modern like https://github.com/EsotericSoftware/kryo . These serializers are a lot faster than map-to-file ones, because they can JIT compile serializers and deserializers for each class.
