### ISSUE TITLE
Issue with FIRESPREAD flag

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/Residence#340]
Hello!
Activation of the `FIRESPREAD` flag leads to the fact that when any combustible block ignites, it will never went out. Yes, the fire does not spread, but makes any combustible block (foliage, wood, etc) forever burning like Netherrack.

Residence 4.8.6.6
Paper 1.14.4

Best regards.

**Comment by mercurialmusic** [comment]
I actually use this as a feature! It behaves the way it's supposed to, though... the fire doesn't spread and the block isn't consumed.

**Comment by Zrips** [comment]
Well @mercurialmusic is correct, this flag prevents fire spread and not fire ignition, while fire itself will never went out because for it to do so it has to consume block itself, which is prevented by this flag. So behavior of this flag is correct.
