### ISSUE TITLE
Inventory Duplication when Keep Inventory Flag is True

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#341]
Putting this here so you don't forget =p Can't update Spigot until this is sorted. 

**Description of issue:**
In a recent spigot build players in a residence with the keep inventory flag set to true both keep and drop their inventories, duplicating everything.

MD_5's comment on the situation:
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-4-development-builds.369724/page-81#post-3491206

**Residence Version:** 4.8.6.6
**Server Type (Spigot/Paperspigot/etc):** Spigot
**Server Version (using /ver):** CraftBukkit version git-Spigot-1981d55-3e7b386 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Thanks!**

**Comment by Zrips** [comment]
0840a7eaa9722eb18eb62869dad909799da5094d
