### ISSUE TITLE
Suggestion: Player command to give ownership

### ISSUE THREAD

**Issue by Iwitrag** [Zrips/Residence#345]
My players would like to be able to give their residences to other players.

So I'm suggesting new command to do that - or maybe it could use /res setowner but there would be two permissions - one for players (so they can give only their own residence) and one for admins.

Of course all limits should be respected - for example if target player has too many residences created, command will not work. This does not apply to command called by admin.

Thanks

**Comment by Zrips** [comment]
You do have /res give [residenceName] [playerName]
