### ISSUE TITLE
[Urgent] Server crash when removing huge residence (logs and details inside)

### ISSUE THREAD

**Issue by blek-id** [Zrips/Residence#348]
Residence version: 4.8.6.6

When a player is removing a residence, it causes the server to crash. This has happened more than 3 times today on the same exact residence. The residence is huge, size is 428000. I tried deleting a small residence I just created and it works fine.

Here are the logs when the crash happened:
https://pastebin.com/FRUA7JTY
https://pastebin.com/HrZVr6uc

![image](https://user-images.githubusercontent.com/26654664/62557761-cd974880-b8a1-11e9-8d0b-885a0e3b57d8.png)

![image](https://user-images.githubusercontent.com/26654664/62557776-d720b080-b8a1-11e9-878e-20fe3ab9ab28.png)

**Comment by Niko302** [comment]
have same problem over here.

**Comment by blek-id** [comment]
Bump. Hey there, It's been happening again and again here, and I think it's coming from lease expiration as well.
https://pastebin.com/vcUziLBz

**Comment by blek-id** [comment]
What version of java are you using? @Niko302 
I'm using java 11

**Comment by blek-id** [comment]
Fixed by disabling auto clean
