### ISSUE TITLE
Server crash when removing a big residence

### ISSUE THREAD

**Issue by Niko302** [Zrips/Residence#349]
Removing a big residence Version: 4.6.6 makes the whole server crash.

**Comment by blek-id** [comment]
Happening on latest residence version as well. @Zrips

**Comment by LogGits** [comment]
@Niko302 provide an error log.

**Comment by blek-id** [comment]
Error log is probably similar to #348 
I fixed it with disabling something called auto clean or something from config

**Comment by Zrips** [comment]
4ec1c08b1a59468373be5a1bac4ef5c7fc101e06
