### ISSUE TITLE
/res list "Name"

### ISSUE THREAD

**Issue by Someone-NEW** [Zrips/Residence#35]
I dont know why is happening this by using /res list /res list "PlayerName" sometime show me Invalid page than sometime i dont see the full list for example player have a lot of residences and i see only 1, next time cant see no refresh and stable lists of residences for other and my list of residences i use the latest version 4.6.1.4 of Residence and Spigot 1.10.2 The same sometime with /resadmin I dont know who and how many residence have some players ............ Please can you fix this? thanks

**Comment by dalibor-drgon** [comment]
This happen to me too - I created new server, type "/res list" and it shows me "Invalid page"

**Comment by smmmadden** [comment]
was able to confirm it results in Invalid Page. . . when issued on the **Console Only**.  In-Game, /res list and /res listall work fine.

**Comment by Someone-NEW** [comment]
smmmadden sorry man, but i think this is need to be fixed i dont know what you say about but this is the big problem i see for now, thanks. /res list and /res list "PlayerName" have problems need to be fixed though.

**Comment by smmmadden** [comment]
my message must have lost translation to you.  I confirmed IT IS a bug and also stated it WORKS in-game.  You however, did not say where you were using the command, so I checked both places.  It's up to the developer @Zrips to fix it, not me.  Keep in mind that not all commands are suited or will work on the console and in those cases you must be in the game to use it.

**Comment by dalibor-drgon** [comment]
This is kind of temporal fix https://gist.github.com/dalibor-drgon/5631b2a10c8d66a0b266f14a32cc145d
It simply makes sure that `totalPages` is always at least 1, so `/res list (1)` and `/res list <nick> (1)` always work and instead of `Invalid page` returns list with no entries in it. Probably it would be better to add message that says `Player x does not own any residences yet`

Tested and working http://imgur.com/a/FAM8o
```
/res list
/res list 1
/res list 2
/res list player 1
/res list player 2
```

**Comment by Zrips** [comment]
Will add message to inform that player don't have any residence.

**Comment by Someone-NEW** [comment]
This "add message" i think wil not resolve the problem this happen when player have already residence too.
And using by me the admin or user command will not solved too.
