### ISSUE TITLE
Spam in console and restarting server

### ISSUE THREAD

**Issue by Khidari** [Zrips/Residence#351]
Hello, I purchased the Residence plugin. It worked for a few days, but suddenly it stopped working. The plugin starts spamming the console and causing the server to restart. Here I pin a file with my log. I have last version of Residence - Residence 4.8.7.0, but before I had 4.8.6.6 and it doesnt work too. And my server run on Spigot 1.14.4.

[latest.log](https://github.com/Zrips/Residence/files/3478880/latest.log)

**Comment by Zrips** [comment]
You might have broken file itself, redownload it and it should get to normal.
