### ISSUE TITLE
[bug] Issue with bypass permission.

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/Residence#352]
Hello!
I have `residence.*` permission node. I can do everything in any residence. But I can not put out the fire with a hit of hand if the flag of a residence `build = false`. I can easily put out the fire by simply placing the block on the fire, but I can’t hit it. I get the message:
`You do not have permission to build flag`.

Best regards.

**Comment by Zrips** [comment]
e20f8249ba85e4d21a8ed41f4e699b2c5f2dd1a6
