### ISSUE TITLE
/res auto {name} {radius} is simply broken

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Zrips/Residence#353]
Edit: maybe I simply misunderstood the functionality of res auto. Probably what I was searching for is /res select X Y Z

If i try to do /res auto **specifying a radius**, it simply ignores it.

I can't understand whats going on very well.. 

It makes the area bigger or smaller depending on how many money i have, ignoring the max radius i set.

It also makes it taller or shorter on the Y axis following some weird criteria that i could not manage to understand.

**It should simply claim a X by X by X area around you! Where X is the radius that you specify...**

Can we fix this issue? Players on my server are starting to get very angry at me because they don't like the new claiming system and they can't understand how to use it without /res auto..

If this is not an issue and its a feature.. well, this feature is pretty useless and incomprensible, expecially without an adequate documentation. You should add a command like /claim {radius} {optional: radius x, radius, y, radius z}

Paper version git-Paper-162
Residence 4 8 6 6

**Comment by Zrips** [comment]
Command format is /res auto (residence name) (radius)
Which means that you need to provide residence name before providing radius. Will make some changes to ignore numeric values as posible residence name to allow name skipping and only provide size.

**Comment by Zrips** [comment]
ef9f6c6d2eb9de0b1693b1574b102cddff1fcd39
