### ISSUE TITLE
It seems that the witherdestruction not work on 1.14.4 (Paper)

### ISSUE THREAD

**Issue by EterLzb** [Zrips/Residence#354]
The plugin is runs on Paper, version: git-Paper-"b6c32b2a" (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
When I set the witherdestruction false, the wither still can broke the broke

**Comment by Zrips** [comment]
Unconfirmed, could you provide screenshots of particular residence when using /res info and flags file?
