### ISSUE TITLE
Random tp permission

### ISSUE THREAD

**Issue by ZagyMC** [Zrips/Residence#364]
Hi, we have issue with permissions on random teleport "/res rt". Any player can use random tp without permission and when we add negative permission on the command it doesnt work either.

**Comment by Zrips** [comment]
if adding negative permission doesn't resolve issue then you have an issue with permission setup or with permission plugin in general.  Every command requires base permission node, /res rt is accessible by default as everyone gets residence.command.rt permission node. When you are negating this permission node, make sure that it is negated and check its state with your permission plugin.
