### ISSUE TITLE
land isn't protected from other players after purchase

### ISSUE THREAD

**Issue by chillerkraft** [Zrips/Residence#37]
i can't figure out why other players can still build on the land i bought
bear with me please i am new to this plugin

**Comment by chillerkraft** [comment]
it's something to do with my plugins
AsyncWorldEditInjector, LuckPerms, AsyncWorldEdit, AntiCreeper, EnderdragonRespawner, CS-CoreLib, Vault, Multiverse-Core, ProtocolLib, NoCheatPlus, LibsDisguises, WorldEdit, Slimefun, Essentials, EssentialsChat, KillerMoney, EssentialsSpawn, WorldGuard, RandomCoords, ConditionalPerms, Residence, ChestShop, LockettePro, ChestShopNotifier
know of any which aren't compatible?

**Comment by chillerkraft** [comment]
it's worldguard
i thought worldguard was compatible?

**Comment by Zrips** [comment]
Its compatible to avoid overlapping regions or creation of residence inside restricted worldguard region. It wont bypass world guard protections.
