### ISSUE TITLE
Player can steal items protected by residence

### ISSUE THREAD

**Issue by smartmadio** [Zrips/Residence#373]
Player can steal items prootected by residence. A player in my server has a 6*6*256 resicence,but all his items in his chests and in the item-freamwork in this residence are stolen by another player B.

I don't konw how that happened.Default config settings of residence and default flag settings,player B doesn't have any permission in his residence.

We have tested in this residence ,none of us could open his chests in this residence and do anything to the item-freamwork in this residence.

Player B admitted he could steal any items in the chests and item-freamworks in any server that using residence plugin,but he refuse to tell me how that happened.

Need fix ,thx.Many players reported to me that they've lost many things.

**Server version:**
Spigot 1.12.2
**Residence version:**
4.8.7.4

**Comment by Zrips** [comment]
I need something more to go on then report that someone managed to steal from a residence. I have no starting point to go on. Was this related to flags. Maybe to his name, maybe with residence name. Maybe related to world. Maybe something else. A way to reproduce it would be a thing by which i could solve this issue.

**Comment by lihugang** [comment]
I happened to see that someone put an hopper minecart a few blocks below the chest and the items in the chest were sucked into the hopper minecart.

But I can't reproduce it.
