### ISSUE TITLE
Sonic Diamond Disruptor can grief protected block 

### ISSUE THREAD

**Issue by pdglobal** [Zrips/Residence#374]
Hello, love the plugin, and so do my players, however, there is one small pitfall when combined with the TARDIS plugin.

The diamond distruptor module for the sonic screwdriver can break glass and iron bars inside a residence where it should not be allowed.

I've had to disable this circuit on my server for this reason, if you could by chance add some kind of hook to detect an attempt to break protected blocks with the sonic, we would much appreciate it so we can re-enable the feature on our server.

Thanks
-PDGLOBAL

**Comment by Zrips** [comment]
Well... If that Tardis plugin could simply fire blockBreakEvent to check if it can break blocks at that location would solve everything without any need for me to go throw specific direct integration of that plugin. So to put it simply, for Tardis dev to add support will be 3 lines of code, for me it will be more like 50+. Try contacting Tardis developer about this, if he is not willing to help, then i will have to spend my time figuring out how to fix this one
