### ISSUE TITLE
Massive lags when residence remove

### ISSUE THREAD

**Issue by EncryptSL** [Zrips/Residence#377]
Version of plugin: 4.8.7.4

Aikar: [Link on Timings](https://timings.aikar.co/?id=381e376a2a0842069b10e3ccbd2d1815#timings)

Server version:  Paper version git-Paper-195 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Me main problem is when i use command /res remove and /res confirm. Server have massive lag.
Only when is residence big but small residence removing process works normal without lag.
Sometimes plugin crash the server.

- Size of selection: 5737500
- X size: 150
- Y size: 255
- Z size: 150 

And Paper Watchdog call this error:
https://pastebin.com/6Whk9hZe

Groups.yml
https://pastebin.com/nTsv5aX1

**Has solution this problem ?**

**Comment by Zrips** [comment]
Try disabling residence cleaning on it removal, as it could cause issues if we need to check huge area.

**Comment by EncryptSL** [comment]
Yes sir, this works thanks for help lags solved. Sorry for another question but plugin no send me information about remove residence. In translate this is  `Remove: '&eResidence &6%1 &ehas been removed...'` But plugin no send this information.  Something wrong in translate or in code ?

**Comment by Zrips** [comment]
4ec1c08b1a59468373be5a1bac4ef5c7fc101e06
1e1b01dc99694eedda4e251c53cea5d7348ac949
