### ISSUE TITLE
BlockPhysicsEvent lag

### ISSUE THREAD

**Issue by Snewmy** [Zrips/Residence#378]
Hello, residence seems to be causing a ton of lag with the blockphysicsevent and i am not sure why, are you able to check this out? https://timings.aikar.co/?id=cc6a7afdc1db4869b1f8da07b29e26f6

**Comment by Zrips** [comment]
Well it doesnt look that bad, i mean, you have allot more plugins which cause allot more load on server then Residence in general. Tho will make some small optimization for that event to have as low impact on server as possible. Other then this, you can simply globally disable dryup flag. 
7f850794ec603b9b1e373ed7d54a520e9d9c3d4b
