### ISSUE TITLE
can not set own flags propely on subzone 

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/Residence#379]
If you do a subzone and allow mobspawn, most you set in main residence nomob false (main residents overtake subzone permissions). 

But cause other problem you don't want mobs go in to main residence. If you set no monster spawn in main res and allow in sub it spawn i subzone, but just nomobs flag in main res take over from subzone (is not mater how i´m setting nomobs in subzone).

**Comment by Zrips** [comment]
a5dc4bd1f928c3ff0627f31a339eb61078ca6e47
