### ISSUE TITLE
Config > Allowing /res rt in specific world.

### ISSUE THREAD

**Issue by NicoFilippo** [Zrips/Residence#38]
Greetings.

I have this issue: Command /res rt (random teleport) is working in the Overworld, but now in nether (neither in the End dimension). It is quite an issue, and I have no idea how to allow players to use the command. 

**Any possible solvations?**

_Thank you, Nico :)_

**Comment by Zrips** [comment]
You need to define world in you config file under RandomTeleportation section like
> RandomTeleportation:
>     # World name to use this feature. Add annother one with appropriate name to enable random teleportation
>     LT_Craft:
>       # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
>       MaxCoord: 1000
>       # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
>       MinCord: 500
>       CenterX: 0
>       CenterZ: 0
>     # World name to use this feature. Add annother one with appropriate name to enable random teleportation
>     LT_Craft_the_end:
>       # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
>       MaxCoord: 200
>       # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
>       MinCord: 0
>       CenterX: 0
>       CenterZ: 0
