### ISSUE TITLE
Residence size dont work

### ISSUE THREAD

**Issue by AlvarZ4** [Zrips/Residence#380]
I have 3 groups created on the groups.yml file [Default, CityMayor(Alcalde in Spanish), Admin], with the permmisions added to the groups of LuckyPerms (residence.group.default, ad the same for others), but when I modify the max size east-west, south-north to other size on the groups.yml file nothing happens, the game say that the limit still being 20 blocks .

Notes:
I use the version 4.8.7.4
I tried whith a clean spigot installation only with the residence plugin and it doesn't work too.

**Comment by Zrips** [comment]
Check /res limits output, second line indicates which group you are actually getting. If its not the correct one, then something is set incorrectly.
