### ISSUE TITLE
Added an area to a residence

### ISSUE THREAD

**Issue by Letraqueur** [Zrips/Residence#382]
Hello,

I want to add an area that I selected to a residence. To be precise my residence at the tail of a chunck and I would add the chuck adjoining with this command:

/res area [add/remove/replace] [areaID] 
- Add or remove areas to the residence. These can overlap with areas of the same residence.

The worry is that it is necessary to know the ID of the area to add to the residence ...
How to know this ID? That of the area I selected.

Is there another way to go? Without using :
/ res expand

PS: sorry for my English, I'm French.

Thank you in advance,
Letraqueur

**Comment by Zrips** [comment]
Its custom ID, basically a name for that area, in same way as you define residence name, this will represent name of that area
