### ISSUE TITLE
Players can still use enchant table

### ISSUE THREAD

**Issue by Nety01** [Zrips/Residence#383]
I have set flags enchant, craft and table to false in my residence, but another players can still use enchant table and crafting table, do I need to set anything more, or is it a bug?

Paper 1.13.2 (build 652)
Residence 4.8.7.4

**Comment by Nety01** [comment]
Same for redstone repeaters, I have set diode to false but another player can still change the tick on a repeater.

**Comment by Zrips** [comment]
5879141ff678a5c931901aefb16586d35cfabf3c
