### ISSUE TITLE
massive lag when using anvil,workbench

### ISSUE THREAD

**Issue by NuNeTomas** [Zrips/Residence#389]
hi so i encountered lag where when trying to use anvil or workbench it takes a bit of time to enter them everything else is perfectly fine but just that i did the timings stuff and found out that some part of residence plugin is causing this lag https://timings.aikar.co/?id=249f29a3d37b4abc906861d164c15918#timings i hope this problem can be solved fast

**Comment by NuNeTomas** [comment]
and i am pretty sure that it is from residence because removing residence plugin fixes the lag

**Comment by Zrips** [comment]
Will make some adjustments, tho its not really enough information to go by. If issue persists with next update, could you provide a screenshot of flags in those residences which has this issue?
