### ISSUE TITLE
Res Info - Flag is 0000-0000 or Server_Land - Non Admin can buy but has no flags afterwards

### ISSUE THREAD

**Issue by Loivado** [Zrips/Residence#39]
**Version:** 4.6.1.4
**Minecraft Version:** 1.9.4
**Server Platform:** Spigot
**Interfering Plugins:** World Guard

**Repro:** 
- Create a Residence.
- Set Flags.
- Restart the Server.
- Go on a Residence you just created.
- Type /res info

**Currently:** 
- Players flags print "00000000-0000-0000-0000-000000000000[my flags]" (see screenshot)
OR
- Players flags print "Server_Land[my flags]"

- Everyone can buy these Residences.
- Flags are not working (players can't build / destroy) for example if these flags got set.

**Expected:**
- Flags are working normally.
- there is no confusing zeros in the player flags
- There is no Server_Land flag in the flags?

**Additonal Infos:**
- Seriously everytime we restart our server this state with zeros comes back. 
- Each time we have to buy all residences as admins and release it again... Super annoying.

![flags 0 or server_land](https://cloud.githubusercontent.com/assets/22766892/25555264/a7871966-2ce1-11e7-9dbb-48c62175ec91.png)

**Comment by smmmadden** [comment]
Just a suggestion here, but this is not reproducible in 1.11.2 of Spigot Server.  1.9.4 is an old build and 1.12 is already being tested, so I'd recommend updating to at least 1.11.2 to make sure you have the latest bug fixes and features to go with them.

**Comment by Loivado** [comment]
Thanks for the Info. 
Updating the Spigot Server Software is now no option for us right now, just to fix the Residence problem. Saidly many others of our Plugins have no support higher then 1.9.4 atm.

**Comment by smmmadden** [comment]
Have you looked at the Spigot Compatible Plugins page for the latest updates?  Here is the https://www.spigotmc.org/wiki/spigot-1-11-plugin-compatibility-list that I keep updated.  

There may be other alternatives for how you have your world setup.

**Comment by Loivado** [comment]
Thanks for the link. 
It's not only a simple world setup. We wouldn't have stayed on version 1.9.4 for so long then. 
We are doing a complex Multi World Concept with already selfmade Plugins. Not only our own Plugins but also other small Plugins are seemingly stopped developing. 
We just have not enough dev resources to update to any higher version atm. :/

**Comment by Zrips** [comment]
Server version should not impact on data saving. Tho cant reproduce this issue on test server. I can see from picture that some issues are definitely there. And what you actually mean by saying "Copy the settings for other Residence Plots."

**Comment by Loivado** [comment]
Sry for late update on my side. 
About "Copy the settings for other Residence Plots." doesn't really matter as the same behavior happens when we create a fresh plot aswell with same "settings".

Strangely in version 4.7.1.1 the behavior changed. The 00.. problem is still there but the flags get assigned correct again. So it's no more functional issue anymore from my point of view.

**Comment by Loivado** [comment]
nvm issue is still persisting in a similar outcome.
when player is renting the residence: on restart the 0000 "user" gets assigned and the player has no more flags to modify the residence, only a "admin" flag.

**Comment by Loivado** [comment]
We tested more about this... When the Residence is not owned by "Server land" the issue is not occuring in any state. 
The Residence Owner stays the creator of the Residence, in our case an Admin which gets the renting price in his pocket everytime a player rents the Residence. Not so optimal but a workaround for us.
