### ISSUE TITLE
/res reload flags doesn't reload flag lists (trusted,...)

### ISSUE THREAD

**Issue by Nety01** [Zrips/Residence#390]
As title says, so when I add flag "door" to trusted list and do "/res reload flags" then "/res padd player" doesn't add the door flag for the player. It's needed to restart the server to make that work.

Paper 1.13.2 (build 652)
Residence 4.8.7.4

**Comment by Zrips** [comment]
7528e855eefb23b209d00154a14cc8c043cc63ac
