### ISSUE TITLE
This plugin is terrible to optimize

### ISSUE THREAD

**Issue by Shesper** [Zrips/Residence#392]
When the Wither is in a protected area. 

plugin version: 4.8.7.4 3288

https://timings.spigotmc.org/?url=ivogosofiy

Never use this plugin!

This plugin is your server are slow down.

**Comment by Zrips** [comment]
You have 3 plugins which use more server resources then Residence does... It seems to spike up once in 18 minute sample. Even tho its not clear which part actually lagged out, but it can be related to residence removal and its area cleaning, which was optimized.
4ec1c08b1a59468373be5a1bac4ef5c7fc101e06
