### ISSUE TITLE
You are blacklisted from using this item here

### ISSUE THREAD

**Issue by MrWay** [Zrips/Residence#393]
Hello, can you help me with issue that players are not able to open their chests, doors, furnances etc. ? They got this error "You are blacklisted from using this item here"

**Comment by MrWay** [comment]
Resolved downgrading to 4.8.7.4

**Comment by Zrips** [comment]
Would be nice to know server version.

**Comment by Zrips** [comment]
93372a05301978863b12dbcad7ec87efee396f22
