### ISSUE TITLE
/res rt with no permission doesn't send "no permission" message

### ISSUE THREAD

**Issue by Nety01** [Zrips/Residence#395]
As said in title. When a player doesn't have a permission for /res rt and sends the command, nothing happens, it should send the error message that he has no permission to do that.

You already closed my old issue on that but the problem is still here

Paper 1.13.2
Residence 4.8.8.1

**Comment by Zrips** [comment]
By default anyone without residence.command.[commandName] will get feedback message about missing permission node. Tested this one out and it does work as intended.
