### ISSUE TITLE
Players can steal from burning furnaces.

### ISSUE THREAD

**Issue by Luky584** [Zrips/Residence#398]
Debug info:
> Residence version 4.8.8.2
> Server is running Paper version git-Paper-1618 (MC: 1.12.2)
> Default configuration

Recorded video: https://ctrlv.tv/7c6f

There is probably problem with different item names "furnace" and "burning_furnace".

It would be nice to fix it.

**Comment by Zrips** [comment]
e23142c4816206c9b4c1a6df62c09127c9d4b808
