### ISSUE TITLE
IgnoreY: true doesn't work and Residences can't be 256 Blocks tall

### ISSUE THREAD

**Issue by saschahi** [Zrips/Residence#403]
Hi, 

_1. IgnoreY: true doesn't do anything on my server. the Regions can still be made at any height.
- Configs are on pasebin
- Creating Regions works just fine, it just doesn't max out the height automatically
- Yes, I restarted, not reloaded
- Yes, I reinstalled the plugin and deleted all configs - Twice_

Cut 1. Completely out. I'm dumb and didn't know about the bypass.ignorey permission. 2. still stands.

2. Regions cannot be from height 0 to 256. they can only be from 1 to 256 or from 0 to 255
- Max Up/Downsize shows 0-255
- Min/Max Protection Height shows 0-256

Residence versionm 4.8.8.2

Paperspigot 1.15.1

Config:
https://pastebin.com/ECJeZvun

Groups:
https://pastebin.com/mm1BnPT6

pls help

**Comment by saschahi** [comment]
Cut out 1. I didn't know about the bypass.ignorey permission

**Comment by Zrips** [comment]
aabd71e0559341f9c5a5391de52d73e19fe44e1a
