### ISSUE TITLE
Too heavy ResidencePlayerListener load?

### ISSUE THREAD

**Issue by Luky584** [Zrips/Residence#409]
Hello, recently I have found that many Residence listeners are putting heavy load on my server.

I have 10-20 online players with 3840MB of RAM.
Here are PaperSpigot timings: https://timings.aikar.co/?id=7cd00144a9f045bba675bf7eb114c93c

Is there any way to improve those timings?
I will be happy to hear any tips ;)
Thanks.

**Comment by bigsmileling** [comment]
Same issue here, a fucking shame, I reported this issue since september and here we are,
Using paper 1.15.2, i7 7700K 5ghz, 64gb 2400mhz, nvme raid0, 8tps when residence is active, 20 without it, this things is happening since 4.8.7.0

**Comment by mrfloris** [comment]
> Same issue here, a fucking shame, I reported this issue since september and here we are,
> Using paper 1.15.2, i7 7700K 5ghz, 64gb 2400mhz, nvme raid0, 8tps when residence is active, 20 without it, this things is happening since 4.8.7.0

Do you perhaps have a timings report of say 15 to 30 minutes or more?
It might help narrow down the problem.

**Comment by mrfloris** [comment]
A friend told me that it looks like server commands is high, is there perhaps a command block looping commands or something?



> Hello, recently I have found that many Residence listeners are putting heavy load on my server.
> 
> I have 10-20 online players with 3840MB of RAM.
> Here are PaperSpigot timings: https://timings.aikar.co/?id=7cd00144a9f045bba675bf7eb114c93c
> 
> Is there any way to improve those timings?
> I will be happy to hear any tips ;)
> Thanks.

**Comment by bigsmileling** [comment]
> > Same issue here, a fucking shame, I reported this issue since september and here we are,
> > Using paper 1.15.2, i7 7700K 5ghz, 64gb 2400mhz, nvme raid0, 8tps when residence is active, 20 without it, this things is happening since 4.8.7.0
> 
> Do you perhaps have a timings report of say 15 to 30 minutes or more?
> It might help narrow down the problem.

You can see some of them here https://www.spigotmc.org/threads/residence-1-7-10-up-to-1-15-paid.88667/page-157#post-3678068
This one is when I reported this lag in September, 2019 https://timings.aikar.co/?id=c5c03513cf3f4f42a6d17c2f93ab76e3

**Comment by Zrips** [comment]
Will do (Well already did some) couple optimizations, as your mentioned 4.8.7.0 version give me idea what could have went sideways after this version. Will be posting new version in couple days.

**Comment by kamziksvk** [comment]
I am giving here also my timings - (Protocol Support disabled) but still heavy load on Residence plugin - https://timings.aikar.co/?id=117a64bf31c042f7bda897827ece754d

**Comment by Zrips** [comment]
@kamziksvk 
Just wait for next version which will contain some optimizations and report back if that one helped out. Until then will close this ticket.
