### ISSUE TITLE
Issue with hook flag

### ISSUE THREAD

**Issue by Nety01** [Zrips/Residence#410]
Hey, I have hook: false in ResidenceDefault and hook: true in CreatorDefault, but still when I create a residence and try to hook anyone, it sends me that I have no permission for hook.

Paper 1.13.2 latest build
Residence 4.8.8.2

**Comment by Zrips** [comment]
Player who is hooked should be in residence which has hook set to true. If this flag is not present then parent zone hook state will be used.

**Comment by Nety01** [comment]
Umm ok, anyway when player with hook true tries to hook a animal so he can't I think that it's a bug. And residence admins maybe should have allowed hook even when it's set to false in residence.
