### ISSUE TITLE
Res restricted?

### ISSUE THREAD

**Issue by EchocallingEarth** [Zrips/Residence#411]
How to adjust the area size allowed?

When attempting to expand the res I get a notice that says: 
_Your x selection length 29 is too big. Allowed 16 and less.
Area size is not within your allowed limits._

Another Example is

_Your selection height (21) is too big. Allowed 20 and less)
Area size is not within your allowed limits_

This is extremely annoying and is preventing us from properly testing before buying the plugin.
We need to be able to buy areas not restricted however I have searched through the configs and am not sure what should be changed. 

Please advise.
Thank you

(Side note and personal interjection below)
PS I tried the Discord first but sadly the discord is useless except for a few people and even then the biggest issue seems to be the lack of actual help. I looked back over the discord in hopes to find more help and realized that the discord on all accounts (all plugins) is not the most helpful. Concerning as we just purchased CMI, already have Jobs and are purchasing Residence and Selection Visualizer on February 1st, 2020.

**Comment by thepeachyviking** [comment]
I am having this issue to. I Paid for the plugin and have loved it. I can make the area bigger using the Resadmin command. But I don't want to be doing that for all my players.

**Comment by thepeachyviking** [comment]
OOF. Literally just found it. You can change the max size in the groups.yml file. Everyone starts at the default residence group. Either upgrade them or make the default bigger.

**Comment by Zrips** [comment]
groups.yml contains all limitations for groups you want to have. Those groups will be given to player depending in his main permission group name, which should match same name as set in groups.yml file or by using **residence.group.[groupName]** permission node
