### ISSUE TITLE
Residence GUI menu items can be dropped and picked up in Paper 1.15.1 Build 58

### ISSUE THREAD

**Issue by In77** [Zrips/Residence#413]
![FC39F1F5-F297-46F5-829C-92152D9F4472](https://user-images.githubusercontent.com/44344308/72674058-5a7b3a80-3aad-11ea-994e-ce34b76b45aa.jpeg)
![3EFAF756-3421-4BFA-903C-097BA171717D](https://user-images.githubusercontent.com/44344308/72674059-5a7b3a80-3aad-11ea-9675-52bf000fb16c.jpeg)
![5B411BC2-E0EE-44C4-B22F-1A09F3CE88C2](https://user-images.githubusercontent.com/44344308/72674060-5b13d100-3aad-11ea-8706-5f11d6578be5.jpeg)
For unknown bug, GUI item can drop out from gui and pickup.
Res 4.8.8.2 Paper 1.15.1 Build 58
Please fix it ASAP.

**Comment by Zrips** [comment]
33a252f79a7367e4fe23994ce22a591b3978e386
