### ISSUE TITLE
Bypass of fly flag

### ISSUE THREAD

**Issue by Nety01** [Zrips/Residence#417]
**Paper version:** 1.15.2 Build 86
**Residence version:** 4.8.8.2

When you do `/res set fly false` so the player can't fly, but in the moment when he enables the flying with `/fly` command he can fly in the residence.

**Comment by Zrips** [comment]
He can only start hovering, but at the moment he tries to fly around he will be dropped down. This is not really fixable without introducing some heavy repeating check on each player movement as there is no fly trigger event.
You could disable /fly command inside residence with **/res command block fly** and then **/res set command false**
