### ISSUE TITLE
Visual bug when trying to pick water

### ISSUE THREAD

**Issue by Nety01** [Zrips/Residence#418]
**Paper version:** 1.15.2 Build 86
**Residence version:** 4.8.8.2

When you don't have permission to, but you try to pick the water in the bucket, sometimes you can see that you picked it, but it's only visual bug for you, another players don't see it and when you teleport away and back the air blocks are filled with water again.

https://i.imgur.com/LzvCZPo.mp4

**Comment by Zrips** [comment]
Tested out couple workarounds, but in general, this is known minecraft bug which was reported already but we dint got any fix for it yet. As this is mainly caused on client side and i can't really do anything about it without creating some elaborate code which would update a bunch of water around player each time he cant pick up any of it, which is quite overkill.
