### ISSUE TITLE
The creation of a residence does not work

### ISSUE THREAD

**Issue by RayCodeCSC** [Zrips/Residence#421]
Hello, I bought a residence plugin from you. I downloaded the latest version, and put it on my server. The problem is that when I want to create a residence (/res create test), I get the error "An internal error occurred while trying to perform this command". But the residence creates me, I can work with it normally. But I don't see the message that I walked in or out of the residence, etc...

I using Minecraft version 1.9

**Comment by Zrips** [comment]
I will need exact error message you got. This can be found in your server log files or from console. Without actual error message i cant really say whats broke. In normal situations residence should be created with some feedback message when this happens and area will get marked appropriately. Then you will get messages when you enter or leave it.
