### ISSUE TITLE
Residence is fine but i got error infos

### ISSUE THREAD

**Issue by HaloSense** [Zrips/Residence#422]
New guy in the field of server establishing.

Installed a server on a Raspberry Pi. It seems that the Residence plugin needs a few more other plugins to function, such as economy?

where should I be looking for those plugins?

**Comment by HaloSense** [comment]
server end is paper 1.14.4, installed no other plugins.

**Comment by Zrips** [comment]
You need any version of Vault plugin and then you need an actual economy plugin. But in general, you can disable economy entirely in config file if you want too.
