### ISSUE TITLE
Protection not working

### ISSUE THREAD

**Issue by kiritodragneel** [Zrips/Residence#425]
I am not sure what I can say here. 
Someone comes on the server selects to points and does /res create and it 
creates a res in that are fine. 

But then someone else can just walk on up and break stuff, no errors in console or anything. 
Also its not permission based as I removed all res permssions from users and they could still break

**Comment by Zrips** [comment]
Residence protection is mainly based on what flags it has. If you dont want from other people breaking blocks in residence, then it should have **break: false** which should be seen with /res info command. Other then this some of the flags can be bypassed with appropriate permission nodes. So ether your residence dont have appropriate flags set or player had bypass permission or res admin enabled. 
I would suggest to reset flags.yml file or manually check what you have set under ResidenceDefault section in flags.yml file which determines what flags residence will have initially when creating it.
