### ISSUE TITLE
Server version upgrade and Residence issues

### ISSUE THREAD

**Issue by XiaoNiuC** [Zrips/Residence#429]
Originally using Residence version 1.7.2
Now want to upgrade to 1.15
But residence area data does not seem to be transferred properly
If I use the old data and then install the new version
Protected area ownership will be assigned to the same player
And the subzone areas cannot be updated normally
Is there any quick way to solve this? Thank you

**Comment by Zrips** [comment]
You are trying to jump over quite allot of version which got quite allot of changes when it comes to data save and data read and general format in general. I cant even comment on 1.7.2 version as i took over this project from 2.6.6.5. My best suggestion would be to try and download multiple versions ranging from 2.6 up to 2.11.0.1, then skip entirely Residence 3, as that one is not even from the same branch, and then get couple versions from 4.x version, run them in sequence and it should convert data over from one version to another. Can't really guarantee that you will get positive results tho. In general this would require a specific converter or you will need to make a fresh start.
