### ISSUE TITLE
Skeleton can shoot items down from itemframe.(Bypass?)

### ISSUE THREAD

**Issue by smartmadio** [Zrips/Residence#430]
Skeleton can shoot items down from itemframe which is protected by residence.

Attract a skeleton to shoot you and then stand in front of an itemframe,then skeleton's arrow can shoot down items in itemframe even if it's protected by residence.

Hopes it could be fixed.

Server version:Paperspigot 1.12.2 (1618)
Residence version:4.8.8.2

**Comment by Zrips** [comment]
Residence which has destroyed set to false will be protected and will not allow from items dropping from item frames if it was hit by an arrow
