### ISSUE TITLE
Residence causing lag spikes (again) on version 4.9.0.0

### ISSUE THREAD

**Issue by kamziksvk** [Zrips/Residence#432]
Hello, I have just used the newest residence version. The problem is that we are again getting lag spikes caused by the residence plugin, mainly with PacketPlayInUseItem and Packet processing. When you take a loser look at the timings you will notice bad Listeners - Residence::Event: c.b.b.r.l.ResidencePlayerListener (PlayerInteractEvent), Residence::Event: c.b.b.r.l.ResidencePlayerListener (PlayerInteractEvent) (SELF), Residence::Event: c.b.b.r.r.ResidenceRaidListener (ResidenceFlagCheckEvent)

Including timings: https://timings.aikar.co/?id=640858c27e364975877466b9cdf42c33

Running version 1.15.2

Can you please provide us assistance?

**Comment by Zrips** [comment]
Testing and found some possibility to optimize some of the things and might have found bug with residence signs which could have caused these spikes when someone interacts with signs. Wll be posting hot fix in an hour or two after I go throw the code just to make sure i dint missed something else.

**Comment by Zrips** [comment]
You can test it now
