### ISSUE TITLE
Residence version 4.9.0.2 – lag spikes

### ISSUE THREAD

**Issue by KillerXCoder** [Zrips/Residence#434]
Hello, 

I am from MidasCraft team, like kamziksvk (he posted last issue where you replyed that you‘ll try to reduce plugin demand on server resources), we have still problem with lag spikes on residence version 4.9.0.2, as you can see plugin residence have still huge load on server CPU. 

Timings: https://timings.aikar.co/?id=7a84b20b373048a8838f783c4d0bfaa0

**Comment by Niko302** [comment]
Do you have the following option set in config ?
    ResCleaning:
      Use: false

**Comment by KillerXCoder** [comment]
Yes, res cleaning is turned off

**Comment by kamziksvk** [comment]
The latest timings. It seems like, that the version 4.9.0.2 is more laggy than version 4.9.0.0. Strange...

Timings link: https://timings.aikar.co/?id=ade18aa60f464075b2518646eda8f595

@Niko302 i dont see a connection between ResCleaning and e.g. - 
Residence::Event: c.b.b.r.l.ResidencePlayerListener (PlayerInteractEvent) This means I am not sure how this could inflict anything but as Killer said - it is turned off.

**Comment by Zrips** [comment]
New version is out, could anyone test this new version and get back with results? As this is strange issue and i had to recheck quite a few code lines related to provided timings, even tho its not as usefull as i would want to, as it doesnt indicate which exact part of code causes issue, only that we have issue with interact event which is like 1000 lines of code across multiple classes... And this might be ralted to some specific action, but i cant really cause excesive load on server, so something is different in your situations and mine. 
Anyways, test it and let me know how it went.

**Comment by kamziksvk** [comment]
Hello @Zrips, i am posting here the latest timings on the Residence plugin:
https://timings.aikar.co/?id=2f8afdc192204097954563bd0d788bb1

Still no possitive effect

**Comment by Zrips** [comment]
Which version was the last one which dint had this issue for all of you?

**Comment by kamziksvk** [comment]
Tough question... it was probably back on spigot 1.14.4 but we are encountering this problem literally for a months.

**Comment by Zrips** [comment]
Well got some hints from other posts that it might be somewhere around 4.8.6.6 which still dint had this issue, waiting for confirmation tho. In any case, will have to investigate what changed after this version if this is the latest one without this issue.

**Comment by kamziksvk** [comment]
Unfortunately I am afraid that this is not a solution :( 1.15.2 is not compatible with 4.8.6.6

```
[19:16:29] [Server thread/INFO]: [Residence] Enabling Residence v4.8.6.6
[19:16:31] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_15 and server will shutdown
```

**Comment by Zrips** [comment]
Latest version should have resolved this issue
