### ISSUE TITLE
after removing the residence, water is cleared

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/Residence#438]
Residence: 4.9.0.3
Server -> Paper: git 143

If a player delete a residence in which the water was water is remove. But only if the water was laid there before creating res

**Comment by Zrips** [comment]
Disable ResCleaning in config file. When this is enabled, after user removes residence some blocks will be removed too, like water. This only applies from 63 block height and up by default. Block list is actually missing with current version, but will be added back with next build.
