### ISSUE TITLE
Request to add softdepend for plugins: ServerControlReloaded, TheAPI

### ISSUE THREAD

**Issue by TheDevTec** [Zrips/Residence#439]
Greetings Zrips, Our plugins SCR (ServerControlReloaded) and TheAPI needs to have softdepend of your Residence plugin because they do not manage to load the worlds created by our SCR/TheAPI plugin, the worlds are loading and the residence also -> In some created worlds, the residence disappears.

**Comment by Zrips** [comment]
In general you could have simply added loadbefore in your plugin.yml file. But well, i can add softdepend from my end anyways.
6c0764ec0310f5b83aa9a95a4d63e2e07a7855ea
