### ISSUE TITLE
Enabling Shop Flag Enables PVP

### ISSUE THREAD

**Issue by Cynadyde** [Zrips/Residence#442]
I am using Residence 4.9.0.5 with Spigot MC 1.15.2.

When a player sets the `shop` flag `true` in their residence, it automatically sets the `pvp` flag `false`. However, when the `pvp` flag is `false`, pvp is enabled within the residence. When the `pvp` flag is `true`, pvp is disabled. 

I'm not sure if the `shop` flag is intended to set `pvp true`, or if `pvp false` is meant to disable pvp, but the current behavior is certainly a bug.

**Comment by Zrips** [comment]
Tested it out and checked code itself to make sure. Cant reproduce this issue and by code itself, pvp is only set to false if shop flag is set to true
