### ISSUE TITLE
/res listall <page> does not work and other issues

### ISSUE THREAD

**Issue by CirnoTH** [Zrips/Residence#443]
Residence: 4.9.0.5
Paper: 1.13.2-654
1. /res listall <page> does not work, players can't turn page.
![listallbug](https://user-images.githubusercontent.com/34177737/79627731-5b377180-816d-11ea-9a32-1f9e8a4e6dd2.png)
2. /res set can't display detailed message for residence permissions.
![guibug](https://user-images.githubusercontent.com/34177737/79627738-6e4a4180-816d-11ea-857a-0f71b23f7d4e.png)
4.8.8.2 pictures:
![4 8 8 2gui](https://user-images.githubusercontent.com/34177737/79627743-84f09880-816d-11ea-9fcc-c4fb662b101f.png)
3. residence players permissions issues.(/pset /padd /pdel)
![perbug](https://user-images.githubusercontent.com/34177737/79627757-9cc81c80-816d-11ea-8729-1c9df8368f92.png)
The above issues does not exist in 4.8.8.2. Please check them.

**Comment by Luky584** [comment]
1. /res listall <**world**> <page>
It is not supposed to show next page. You should use clickable chat symbols or use command like this: /res listall * <page>

3. Havent you changed any of those config options? Are you running online or offline server?

```  # Starts UUID conversion on plugin startup
  # DONT change this if you are not sure what you doing
  UUIDConvertion: false
  # If you running offline server, better to check this as true. This will help to solve issues with changing players UUID.
  OfflineMode: false
```

4. LockettePro is **Abandoned**.

**Comment by CirnoTH** [comment]
No i didn't change any config options.
They were normal until I upgraded to 4.9.0.X.

**Comment by tiarnia** [comment]
im having same issue clicking the next button takes you too page 1 no mater what you only see page 1 
/res listall 2   gives you page 1  as well

**Comment by Tomasan7** [comment]
Same problem with /res listall <page>

**Comment by Zrips** [comment]
51de99e2a1f85adcf9bbc0db4e2356872719eb1a

**Comment by Zrips** [comment]
03e81080d5c3aefa82e130ac8bfa2461dfab2025

**Comment by Zrips** [comment]
26b2d9fb48e4406e9f88720bb8e2d4beccd83829
