### ISSUE TITLE
Flags and permissions issues

### ISSUE THREAD

**Issue by EkonC** [Zrips/Residence#444]
I added a player to a residence (/res padd...) but he could not destroy or build any blocks. So I checked his flags (/res pset...). They were all set correctly, but he still couldn't do anything. So I added him permissions residence.bypass and residence.admin. Still couldn't do anything. I added him residence.*, still nothing. So I opped him and still nothing.

Then again I tried to grant permissions to another player. It worked, but when I tried to remove him, he still could do anything in that residence. So I set all the player flags to true and then to false. He couldnt place blocks but he could destroy them. All the flags were set correctly (also in the /res set flags was everything false)

**Comment by EkonC** [comment]
Paper 1.15.2
Residence 4.9.0.5

**Comment by MrMorganCz** [comment]
Yes, I have a similar or maybe the same problem.

4.9.0.5
Paper:  Build 144 1.15.2

**Comment by kamziksvk** [comment]
Confirming the same problem, version 4.9.0.5, Paper: Build 147 1.15.2

**Comment by christaylor201** [comment]
I can confirm the same issue on PaperMC 1.15.2 build 162 with Residence 4.9.0.5.

We've looked into the issue a little bit on our server and we've found out the player flags inside `Residence/Save/Worlds/res_<world_name>.yml` flat database are duplicated for some players – the first one has player name as the key whereas the second one has UUID.

Example:
```yml
<residence_name>:
  Permissions:
    PlayerFlags:
      JohnDoe:
        destroy: true
      8c2eff0b-d217-44e3-8218-f22694328345:
        destroy: false     
```
We have no idea how this happens; you have to delete both of the keys and add the player again to fix the issue. It seems restarting the entire server fixes it, too.

**Comment by kamziksvk** [comment]
In our case, the server restart didnt helped, it is the long-term issue.

**Comment by PintaPepo** [comment]
Investigating, will report back.

**Comment by Zrips** [comment]
26b2d9fb48e4406e9f88720bb8e2d4beccd83829
