### ISSUE TITLE
RandomTeleport cannot set world options

### ISSUE THREAD

**Issue by XiaoNiuC** [Zrips/Residence#445]
I am using the 4.9.0.5 version of the plugin and found that the setting of whether each world is enabled for Random teleport is missing in the config
At present, if the Random teleport is opened, all worlds can be used.
Can it be changed to a switchable option?

**Comment by 100petr** [comment]
I solved it by permission  (negative permission to world). 
for example permissionsex: pex group <group> add -residence.randomtp <world>

**Comment by Zrips** [comment]
deeb2c50f5da55ef3ee0f4c2b7d172f279a0cfd5
