### ISSUE TITLE
Animalkilling issue

### ISSUE THREAD

**Issue by R1NZLER15** [Zrips/Residence#448]
Players can bypass the animalkilling flag with spectral arrows or tridents with the channeling enchantment, this is an issue that has been going on since months ago, i thought that with the latest updates this would get fixed. 

Paper 1.15.2: Build 155

Residence: 4.8.8.2 (Not using the latest version because its way too broken, players can grief residences and padd/pset/pdel are not working properly)

**Comment by PintaPepo** [comment]
Confirmed bug on Residence 4.9.0.5, will start working on a solution

**Comment by PintaPepo** [comment]
Would you mind verifying if the problem is fixed?

**Comment by Zrips** [comment]
d2e6a083443b3d7201f56b4b45df7b6cc6d07d1a
