### ISSUE TITLE
Subzone removal prevention

### ISSUE THREAD

**Issue by 5okl** [Zrips/Residence#450]
Hello,
i will try to explain my problem. But first, i will explain how i want to use your plugin.
So, the concept of my server is simple, players can walk all around the world for build, mine, etc… but nothing is protected. To protect their things, a player can buy a residence (very very expansive), or a subzone in an existing residence. If he decide to buy a residence, he call the server admin. This one comes to the place where the player decided to build his residence, create it and sell it (only server admin can create residence). The player, new owner of the residence, can create subzones, to sell them to other players players who don't have enough money to buy a residence. The server will be filled with residences which themselves will be filled with subzones.
So actually 95% of this project is ok, there is only one problem with Residence plugin : the owner of a residence has the right to remove a subzone even if this subzone has been purchased by a player… that's a big problem because if the residence owner don't follow the rules, he can rip off the players.
My question is simple, is it possible to prevent subzone removal by the residence owner ? when this one has sell the subzone to an other player.
Best regards, Rémi "5okl".

**Comment by Zrips** [comment]
Check Rent -> PreventRemoval and set it to true

**Comment by 5okl** [comment]
It is already on true

**Comment by 5okl** [comment]
it's not for a rent, it's for a solded subzone

**Comment by Zrips** [comment]
Keep in mind that you can bypass this option if you have residence.delete.subzone permission node. And this option does apply for sold subzones. I might need to separate it, just to avoid confusion in future.

**Comment by 5okl** [comment]
Ok, but how the residence owners can remove a subzone without the residence.delete.subzone permission ?

**Comment by Zrips** [comment]
They could have resadmin enabled
