### ISSUE TITLE
[BUG] Flag "bed" doesn't work

### ISSUE THREAD

**Issue by ijerrychan** [Zrips/Residence#451]
Server version: 1.15.2 spigot/paper (both tested, without any other plugin)
Residence version: 4.9.0.5  4.8.8.2 (both tested)
Issue: flag "bed" doesn't work, I've tried setting it up in residences, global and groups, but players can still use beds. Then I used the default config and nothing changed.

**Comment by Zrips** [comment]
If players have use flag they will bypass this protection by default.
