### ISSUE TITLE
[BUG]  Error when doing /res select expand

### ISSUE THREAD

**Issue by TimRambo** [Zrips/Residence#453]
https://pastebin.com/rw6Zxn4b
MC Ver: 1.15.2 
Res Ver 4.9.0.5

When doing /res select chunk it gives "An internal error occured while attempting to perform the command" Also been having trouble with claiming ever since the change was added
"Your x selection length(10) is to small allowed 256 or more"
And when X length is greater then 10 it sends "An internal error occured while attempting to perform the command?

**Comment by Zrips** [comment]
b10ac9f0e3c84656b5857ee86e077751d6a066ec
