### ISSUE TITLE
"/res pset"not work when the player is offline on the offline server

### ISSUE THREAD

**Issue by w1O42O86726** [Zrips/Residence#455]
**player "fjfh" uuid is "ebcd6100-1f30-307a-8674-a573340aba38"**

  ak47:
    TPLoc: 16095.97:40.0:-2308.95:-1.06:358.71
    Messages: 1
    BlockSellPrice: 0.25
    Permissions:
      PlayerFlags:
        d3ef96ef-8537-3118-8868-458b20e87a65: 1
        c19f5f43-65eb-3b9f-9d88-e8299c64b05a: 1
        **ebcd6100-1f30-307a-8674-a573340aba38: 1**
        b297f5b9-7afe-3169-b77a-a268c3cc0ea8: 2
        **fjfh: 29**
        de6865bc-2c72-3098-bb6a-da5103f76657: 1
      AreaFlags: 30
      OwnerUUID: b297f5b9-7afe-3169-b77a-a268c3cc0ea8
      OwnerLastKnownName: baizhiheiyue
    CreatedOn: 1586836306993
    Areas:
      main: 16064:12:-2332:16123:67:-2271

**Comment by Zrips** [comment]
26b2d9fb48e4406e9f88720bb8e2d4beccd83829
