### ISSUE TITLE
If I installed COFH , fluid will put the private residences successfully

### ISSUE THREAD

**Issue by Damnie** [Zrips/Residence#46]
Flags set,but it doesn't work
KCauldron - 1.7.10 Server
my report:
https://www.spigotmc.org/threads/residence-1-7-10-up-to-1-11-paid.88667/page-123#post-2350890
https://www.spigotmc.org/threads/residence-1-7-10-up-to-1-11-paid.88667/page-123#post-2352929
COFH:https://mods.curse.com/mc-mods/minecraft/cofhcore
(My english is not very good)
Thanks!

**Comment by Zrips** [comment]
This is plugin and mods uses completely different methods to handle events. I can't add support for custom blocks.

**Comment by Damnie** [comment]
I know , but Redprotect Plugins can.
Fluid means all fluid , like mc's water,lava ...

**Comment by Damnie** [comment]
COFH issue : https://github.com/Zrips/Residence/issues/46
