### ISSUE TITLE
Residence flags don't get overridden when adding or removing a player from the residence

### ISSUE THREAD

**Issue by bunzybunz** [Zrips/Residence#460]
This bug is present in Build 4.9.0.5 | Paper 220
In 4.9.0.3 it works as expected, but in this latest one whenever a player tries to add someone else to the claim using any command (res padd | res pdel | res pset) the flags just duplicate. So if Player1 has the move flags set to false and the owner of the claim tries to set the move flags to true, in the /res info I can see Player1 move:false and Player1 move:true. In the save file the second player name shows as a uuid. So there's both the name and the uuid of that said player.

**Comment by Nety01** [comment]
Can confirm with Residence 4.9.0.5, Paper 1.15.2

**Comment by w1O42O86726** [comment]
> Can confirm with Residence 4.9.0.5, Paper 1.15.2

After testing, there is indeed this problem

**Comment by Zrips** [comment]
Cant really reproduce this issue currently, unless i'm missing something obvious here. Could some one elaborate more on this one?

**Comment by bunzybunz** [comment]
Have you tested it with the offline uuids option turned on in the config? Because that's what I used when I tested and found this bug.

**Comment by 100petr** [comment]
![2020-05-13_12 20 53](https://user-images.githubusercontent.com/29830635/81801217-59669100-9514-11ea-94d2-a4582f3993c3.png)
![2020-05-13_12 21 10](https://user-images.githubusercontent.com/29830635/81801229-5c618180-9514-11ea-8e64-1abb69b3b745.png)
First screen - /res pset __TauroN__ trusted t
Second screen - /res padd __TauroN__

**Comment by bunzybunz** [comment]
Like 100petr displayed here, the flags get duplicated for that specific player. One set of flags is saved for the player name and one set of flags is saved for the player's uuid.

**Comment by Zrips** [comment]
Yea, some what reproduced this issue, as its quite strange one and quite specific, will fix it soon enough.

**Comment by Zrips** [comment]
26b2d9fb48e4406e9f88720bb8e2d4beccd83829
