### ISSUE TITLE
Crossbow Fireworks ignores PVP flag

### ISSUE THREAD

**Issue by crevice** [Zrips/Residence#466]
Firework Rocket fired from a crossbow deals EXPLOSION damage to players in residence with pvp:false flag, i think it must be affected with the pvp flag.

Suggestion for bootleg: cancel firework explosion damage in EntityDamageByEntityEvent if pvp:false is present.

This server running Residence version: 4.9.0.5

**Comment by PintaPepo** [comment]
Confirmed, will work on it on my current fork.

**Comment by Zrips** [comment]
@PintaPepo 
https://discord.gg/dDMamN4
Join and send me pm.

**Comment by Zrips** [comment]
12294f994da45ed9a22065c7e9dd8166c7870c60
