### ISSUE TITLE
Some flag only enable on certain place

### ISSUE THREAD

**Issue by WhiteHappy** [Zrips/Residence#482]
I hv a server`s residence with almost all flag set to false.
I hv make sure door build flag have been set to false, but it only work near the spawn,player still can use door and break/place block few block away from spawn(in area of residence)

**Comment by Zrips** [comment]
Flag access is not limited by distance or by place players are in. You might need to check what permission access they have in those places. Other than this i cant really debug this one as it does look like some specific incorrect setup in your situation causing this issue
