### ISSUE TITLE
Growing Redwood/Mega Spruce Tree outside a claimed residence removed grass blocks inside the residence

### ISSUE THREAD

**Issue by cvrunmin** [Zrips/Residence#483]
As the title mentioned, when a redwood/mega spruce tree grows outside a residence, grass blocks inside the residence are removed.
By Minecraft Wiki, when a redwood grows, it turns nearby grass blocks in a radius of 6 into podzol. With the residence protection, however, grass blocks inside residence should keep intact. That means those removed grass blocks are expected not to be removed.

saplings and residence before the tree grow. Note that the 10x10 grass block platform is inside a residence that has flag `build` and `destroy` set to false
![](https://i.imgur.com/HYIJmtA.jpg)
After:
![](https://i.imgur.com/e2cIY0I.jpg)

The suspected code is found here:
https://github.com/Zrips/Residence/blob/deeb2c50f5da55ef3ee0f4c2b7d172f279a0cfd5/src/com/bekvon/bukkit/residence/listeners/ResidenceBlockListener.java#L185
this line sets any blocks that inside a protecting residence and being affected by tree grow to air, regardless the original block

**Comment by Zrips** [comment]
Excellent point, its completely wrong with current code.
922774541030fa933adf65e841dc431c16cb092d
