### ISSUE TITLE
/res pset no longer works from console

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#484]
Didn't notice this until tonight so I'm not sure which version was initially affected - some new players exploring some of our quests that rely on console commands from CMI kits to give teleport permission. While /res pset [res-name] mercurialmusic tp true works in game, the same command in console only returns the help info (no error otherwise):

```
>res pset atlantis.maze.mazestart mercurialmusic tp true
> [01:23:58] [Server thread/INFO]: Usage: /res pset <residence> [player] [flag] [true/false/remove]
> [01:23:58] [Server thread/INFO]: Usage: /res pset <residence> [player] removeall
> [01:23:58] [Server thread/INFO]: To see a list of flags, use /res flags ?
```

We run the command in a CMI kit with the asConsole! prefix.

Residence version: 4.9.0.6
CMI version: 8.6.27.2
Server version: CraftBukkit version git-Spigot-a99063f-c9d7c16 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Thanks!

**Comment by Zrips** [comment]
16be4fd43d8078cf1a18d69826cd6debd7ac04bc
