### ISSUE TITLE
1.15.2 Paper 370 /res remove is not refunding

### ISSUE THREAD

**Issue by Kirrasio** [Zrips/Residence#485]
Using CMI 8.6.24.1, Residence 4.9.0.6, and CMIEInjector 1.0.2.1
On residence removal, the money does not get refunded. I have tried to set it to vault and cmieconomy.
I have submitted my config, each of the groups have the corresponding permission nodes for the residence groups.
[Residence.zip](https://github.com/Zrips/Residence/files/4806839/Residence.zip)

**Comment by Zrips** [comment]
You need to enable ResMoneyBack in config file for this to work. Will include this information into default groups file to avoid confusion in future.
