### ISSUE TITLE
Random teleportation worlds are unconfigurable

### ISSUE THREAD

**Issue by Baterka** [Zrips/Residence#486]
I am not able to configure min/max coords values for random teleportation (`Global.RandomTeleportation.Worlds`).

Everytime I edit or create new world definition in config (eg. `Global.RandomTeleportation.Worlds.world_nether`) and I reload plugin (or restart server), config is rewritten (just the part with Random teleportation) and my settings are not applied or even removed from config.

**Comment by Kirrasio** [comment]
Having the same issue.

I also have this inside my config, which looks a lot like the random teleportation line. https://cdn.discordapp.com/attachments/526403195476639744/725191289078808576/Capture.JPG

**Comment by Zrips** [comment]
ecff72e07392af1b6d0de1cacc775d641290d131
