### ISSUE TITLE
RentEventType.UNRENT appears to do nothing

### ISSUE THREAD

**Issue by v3Monsta** [Zrips/Residence#487]
So I have added residence support to a different plugin, however when I when to use this check
`if (event.getCause() == ResidenceRentEvent.RentEventType.UNRENT)` the plugin doesn't seem to pass this event properly and ends up skipping a huge chunk of my code right after this check when using `/res market unrent`.

I have resorted to using a `if (event.getCause() != ResidenceRentEvent.RentEventType.RENT` as a workaround but ideally I would use the correct enum for this check rather than adding unexpected bahaviour to the plugin.

Just to reiterate, my implementation works just fine with the != check and I've isolated the issue to RentEventType.UNRENT

**Comment by Zrips** [comment]
You might want to check for RentEventType.UNRENTABLE type event too, which is done in case we simply remove player from rented residence but we don't remove residence itself from being able to be rented. 
FYI your example of `/res market unrent` command doesn't trigger any events, `/res market confirm` does, which can ether trigger player kicking out of rented zone or removing residence from being rentable in general.
