### ISSUE TITLE
1.15.2 Paper 370 /pset Not working for individuals

### ISSUE THREAD

**Issue by Kirrasio** [Zrips/Residence#488]
The command /pset is setting the base flags on most of the flags and will not work for the individual players for individual flags.
It just gives a conformation that the flag has been changed in the whole residence.

It does oddly enough work for some groups -> Fire, Trusted, and Redstone.

The flag Craft does not appear to work at all.

/pset (res) (name) (flag) (true/false)
/pset (player) (flag) (true/false)

Using CMI 8.6.24.1, Residence 4.9.0.6, and CMIEInjector 1.0.2.1

**Comment by Volgeop** [comment]
Have to agree, for me it doesn't work too. Look at the Discord where are reported more examples

**Comment by Zrips** [comment]
Small issue with default flag name. In general it should be different one than already existing flags. We do have fire flag as a single and specific one, so we cant have grouped flags by same name. Other than this, fire flag is only for residence and not for players in specific. Will add some extra feedback message with better information why we cant set some of the flags when we are doing pset or set sub commands
ad525fa2a9e69c8831b9814cfd4af53e610bc352

**Comment by Volgeop** [comment]
@Zrips and could you make list of flags we can use for players?
