### ISSUE TITLE
/res shop like display value is too dark

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Residence#49]
There are actually 2 likes for the shop, but the value isn't readable.  Perhaps add config option to control the color to orange, yellow or even white? 
![image](https://cloud.githubusercontent.com/assets/10309346/26231245/254d28d8-3c1c-11e7-83b5-7f7f92195f9b.png)
The value on the sign looks readable with the exception of line four it is a bit light for the word Likes
![image](https://cloud.githubusercontent.com/assets/10309346/26231311/76823c52-3c1c-11e7-987e-fdf4a429bd14.png)

**Comment by Zrips** [comment]
Will change
