### ISSUE TITLE
/res info console warning

### ISSUE THREAD

**Issue by ZagyMC** [Zrips/Residence#493]
After command /res info i have some warns in console, i have loaded save folder with 7 residences from old server. In game it looks like its working, but in console i see this.

> [14:29:40] [Server thread/INFO]: ZagyDee issued server command: /res info
> [14:29:40] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
> [14:29:40] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [14:29:40] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [14:29:40] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [14:29:40] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [14:29:40] [Server thread/WARN]: at com.bekvon.bukkit.cmiLib.RawMessageManager.send(RawMessageManager.java:64)
> [14:29:40] [Server thread/WARN]: at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:631)
> [14:29:40] [Server thread/WARN]: at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:615)
> [14:29:40] [Server thread/WARN]: at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:661)
> [14:29:40] [Server thread/WARN]: at com.bekvon.bukkit.residence.protection.ResidenceManager.printAreaInfo(ResidenceManager.java:746)
> [14:29:40] [Server thread/WARN]: at com.bekvon.bukkit.residence.commands.info.perform(info.java:46)
> [14:29:40] [Server thread/WARN]: at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:267)
> [14:29:40] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [14:29:40] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
> [14:29:40] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:755)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1702)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1545)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:919)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
> [14:29:40] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [14:29:40] [Server thread/WARN]: Caused by: com.google.gson.JsonParseException: Unexpected empty array of components
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:229)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:148)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:1)
> [14:29:40] [Server thread/WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:493)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:517)
> [14:29:40] [Server thread/WARN]: at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:357)
> [14:29:40] [Server thread/WARN]: ... 30 more
> [14:29:40] [Server thread/INFO]: Failed to show json message with packets, using command approach
> [14:29:40] [Server thread/INFO]: Invalid chat component: Unexpected empty array of components
> [14:29:40] [Server thread/INFO]: ..."ZagyDee" ["",{"text":"","extra":[{"text":"§ePlayers flags: §6"}]},{"text":"","extra":[{"text":"§aJancicka§r"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"§2bed §2container §2door §2ignite §2note \n§2egg §2anvil §2use §2admin §2animalkilling \n§2button §2hook §2cake §2vehicledestroy §2itempickup \n§2place §2subzone §2table §2move §2shear \n§2destroy §2lever §2pressure §2brew §2enderpearl \n§2dye §2beacon §2trade §2itemdrop §2build \n§2flowerpot §2chat §2enchant §2leash "}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"§2EeRaOfficial§r"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"§2container §2ignite §2move §2shear §2use \n§2destroy §2animalkilling §2trade §2mobkilling §2build \n§2vehicledestroy §2leash "}]}}},{"text":"","extra":[ ]}]<--[HERE]

*I checked it, it doesnt load old players added in ressidence, it shows only creator in chat when i type /res info.

**Comment by ZagyMC** [comment]
It gives warns info in console, it doesnt show added players in info, but enabled flags for them are working.

**Comment by Zrips** [comment]
fixed with latest builds
