### ISSUE TITLE
admin group

### ISSUE THREAD

**Issue by ZagyMC** [Zrips/Residence#494]
I created admin group "admin", i added permission residence.group.admin for admin permission group. But when i type /res limits it shows me the last group in config added. So i had residence group vip even i had permission for admin group, after i put admin group bellow vip it showed me residence group admin. 

I guess its not that important for normal players it gives group depend on their permission note. But it should work for admins too i guess.

**Comment by Zrips** [comment]
We are checking to which group player has access too and if its more than one group then we will pick last one. So ether remove access to vip group by negating permission node to that group or switch places one with another and make admin group as last one in the list
