### ISSUE TITLE
Using /res info will cause an error

### ISSUE THREAD

**Issue by XiaoNiuC** [Zrips/Residence#498]
Currently using the latest version of Residence
The server version is 1.16.1
These messages will appear when entering /res info
https://pastebin.com/2qeWbnhZ
-
[Tue, 30. Jun 2020 17:45:05 HKT INFO] ENG_tw issued server command: /res info
[Tue, 30. Jun 2020 17:45:05 HKT WARN] java.lang.reflect.InvocationTargetException
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at jdk.internal.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at com.bekvon.bukkit.cmiLib.RawMessageManager.send(RawMessageManager.java:64)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:631)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:615)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at com.bekvon.bukkit.cmiLib.RawMessage.show(RawMessage.java:661)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at com.bekvon.bukkit.residence.protection.ResidenceManager.printAreaInfo(ResidenceManager.java:746)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at com.bekvon.bukkit.residence.commands.info.perform(info.java:46)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:267)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1203)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at java.base/java.lang.Thread.run(Thread.java:834)
[Tue, 30. Jun 2020 17:45:05 HKT WARN] Caused by: com.google.gson.JsonParseException: Unexpected empty array of components
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:229)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:148)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:101)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:493)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:517)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:358)
[Tue, 30. Jun 2020 17:45:05 HKT WARN]     ... 29 more
[Tue, 30. Jun 2020 17:45:05 HKT INFO] Failed to show json message with packets, using command approach
[Tue, 30. Jun 2020 17:45:05 HKT INFO] Invalid chat component: Unexpected empty array of components
[Tue, 30. Jun 2020 17:45:05 HKT INFO] ... "ENG_tw" ["",{"text":"","extra":[{"text":"Players flags: "}]},{"text":"","extra":[{"text":"December_tw"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"container ignite move shear use \ndestroy animalkilling beacon trade mobkilling \nbuild chat vehicledestroy tp leash \n"}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"ENG_tw"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"container ignite move trade shear \nmobkilling build use destroy vehicledestroy \nleash animalkilling "}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"CatMoon_tw"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"container ignite move shear use \ndestroy animalkilling beacon trade mobkilling \nbuild chat vehicledestroy tp leash \n"}]}}},{"text":"","extra":[ ]}]<--[HERE]

**Comment by Zrips** [comment]
Fixed with latest builds
