### ISSUE TITLE
Bug-Blacklisted Item

### ISSUE THREAD

**Issue by MrNeeony** [Zrips/Residence#503]
Hello, when player tries to open crafting table or chest it writes:
(in Czech)
Toto zde nemuzes pouzit.
Translation:
''You can't use that in here''
or something like that.

But when player opens it when he's holding something in his hand, then he can open it.
![2020-07-04_21 50 45](https://user-images.githubusercontent.com/67321863/86530275-a719cd00-beb7-11ea-9163-d210bae67baa.png)

**Comment by Zrips** [comment]
246da2092709d96073d291f25c87580394040414
if issue persists, next time please include server version
