### ISSUE TITLE
Move default residence enter/leave message to Language yml

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [Zrips/Residence#504]
Now every player has to type `/res message` to do customize.  
Or in case I don't want the message to be customized and have a default value (RPG style or something)...  
Further more, everything is local language but only the default join/leave message are English.

Didn't find this value from Language yml or `config.yml`

**Comment by Zrips** [comment]
Enter/leave messages are defined in groups.yml file where it can be customized by players groups. Other than this, if you want to prevent players changing those messages, simply negate residence.command.message permission node

**Comment by mhtvsSFrpHdE** [comment]
@Zrips Didn't realize the default message were stored in `groups.yml`, but that's work!

I should use some IDES like vscode to do text search across multi files,  
then unless it's hard coded in jar binary,  
I may be able to found it before submit an issue
