### ISSUE TITLE
On compatibility with mmoitems

### ISSUE THREAD

**Issue by killertuling** [Zrips/Residence#506]
When the plug-in runs with mmoitems, there are four compatibility options
But if I set these options to prevent players from modifying them, they will still appear in the GUI
At present, you can only use reload flags once after the server is turned on.

v; 1.15.2-1.16.1    plugins:4.8.8.2-4.9.1.1

**Comment by Zrips** [comment]
No idea what you are talking about here. Reporting issues which involves other plugins needs to have as much information as possible. I'm not that familiar with mmoitems to know exactly what you mean by those four options, what it should do or even where i should look for them.

**Comment by killertuling** [comment]
Thank you for your reply!
i 'm sorry,I didn't explain the problem clearly.

MMOItem is an RPG item plugin,Maybe it's actively compatible with "residence".
When I install it, it will actively generate 4 flags.
Just like other flags,Their role is to control the effect of items in the territory.

But it has a small problem：
If I'm in 'flags.yml' set "use = false", then when the player uses the "/res set" command,they will not be able to find "use" in the GUI.  ( It's normal, right?
But if I set the 4 new flags generated by "mmoitem" to false, after the server started, I found that it still existed in the GUI.
It doesn't disappear until I use the "res reload flags" command.

I don't know much about plugins,I guess this is because the plugin checks for flags earlier than other plugins add flags?

My English is not very good,I use translation software to communicate,If there is anything else that I have not made clear, please point out that I try to make it clear.

**Comment by killertuling** [comment]
> No idea what you are talking about here. Reporting issues which involves other plugins needs to have as much information as possible. I'm not that familiar with mmoitems to know exactly what you mean by those four options, what it should do or even where i should look for them.

---
Thank you for your reply!
i 'm sorry,I didn't explain the problem clearly.

MMOItem is an RPG item plugin,Maybe it's actively compatible with "residence".
When I install it, it will actively generate 4 flags.
Just like other flags,Their role is to control the effect of items in the territory.

But it has a small problem：
If I'm in 'flags.yml' set "use = false", then when the player uses the "/res set" command,they will not be able to find "use" in the GUI.  ( It's normal, right?
But if I set the 4 new flags generated by "mmoitem" to false, after the server started, I found that it still existed in the GUI.
It doesn't disappear until I use the "res reload flags" command.

I don't know much about plugins,I guess this is because the plugin checks for flags earlier than other plugins add flags?

My English is not very good,I use translation software to communicate,If there is anything else that I have not made clear, please point out that I try to make it clear.

**Comment by Zrips** [comment]
You could try simply negating residence.flag.mi-abilities permission node

**Comment by killertuling** [comment]
> You could try simply negating residence.flag.mi-abilities permission node

I tried,Just like other falgs. But these 4 permissions don't work.
there is no such permission node.
