### ISSUE TITLE
/res tp is broken

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Residence#507]
Hi, /res tp command on another residences doesn't work... even if player has residence.admin.tp

**Comment by Zrips** [comment]
Residence needs to have tp flag set to true or it being removed for player being able to teleport to residence. Other than this, not enough information to determine issue in your situation.

**Comment by Volgeop** [comment]
Here you are... player has residence.admin.tp + there is tp flag to true in residence but it says that player can't teleport (translated). https://imgur.com/a/kiK11HL @Zrips

**Comment by Volgeop** [comment]
Wanna reopen, because it's still broken. @Zrips
