### ISSUE TITLE
Residence is deleted after server crash

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Residence#508]
Hi, residence is deleting after server crash..... Maybe if player created it few minutes ago, it deletes....

It's probably due to:
```
  # The interval, in minutes, between residence saves.
  SaveInterval: 64
```

Bcse when server crash and server is killed, it won't save....

**Comment by Zrips** [comment]
Well you are describing issue and a cause of it. If you have same interval like this then any changes done during this time will not be saved if server crashes. Set this interval to 10 minutes, 15 max. having it at 64 only invites issues.
