### ISSUE TITLE
/res set cake flag invalid problem

### ISSUE THREAD

**Issue by gregman98** [Zrips/Residence#509]
In the wiki says that cake's flag is "allows or denys players to eat cake."
And I set the residence **flag to false**. But my test player found they **still can eat cakes**. It's very strange.
So I tried to use default setting but something happened again.
Maybe it was my mistake, or just a bug that needs to be fixed.
Sorry my bad English.
Hope to receive a satisfactory reply as soon as possible.
Residence version is 4.9.1.2
Paper version is 1.15.2 build 374

**Comment by Zrips** [comment]
d91d9bf47d50949c220297a8ece21c4393d854f4
