### ISSUE TITLE
Pvp flag and consume bug

### ISSUE THREAD

**Issue by melinstagibson** [Zrips/Residence#51]
Found a minor bug

If PVP in a claim is set to "remove" and you try to eat something it gets cancelled upon receiving damage (very annoying if you are on fire)

if its set to "true" eating works just fine. weird little glitch but should probably be fixed

Also the anvilbreak flag in the gui has that weird texture of an unknown item. atleast in 1.11.2

**Comment by Zrips** [comment]
Will fix anvil icon issue. 
But can't reproduce issue with PVP flag, all seems to be working as intended.

**Comment by melinstagibson** [comment]
Yes, it seems like it was caused by something else but enabling pvp somehow fixed it temporarly (it returned later). So i doubt it was related to residence.
