### ISSUE TITLE
/res set anvil flag problem

### ISSUE THREAD

**Issue by gregman98** [Zrips/Residence#510]
Set the flag of the **anvil to false**.
If the anvil is **not chipped**, then everything is normal.
If that is opposite, **chipped**, then player **can use**.
Sorry my bad English.
Hope to receive a satisfactory reply as soon as possible.
Residence version is 4.9.1.2
Paper version is 1.15.2 build 374

**Comment by Zrips** [comment]
96b7128d5753d3ef9c38143ce200d6c2a5a2bf78
