### ISSUE TITLE
incompatible plugin issue

### ISSUE THREAD

**Issue by ChrisFlyer7** [Zrips/Residence#511]
please fix below issue
https://pastebin.com/ndYfcyRc
incompatible plugin
https://www.spigotmc.org/resources/kingdomsx.77670/
thanks a lot

Residence version is 4.9.1.2
Paper version 1.16.1 #89

**Comment by Zrips** [comment]
As i dont have access to this plugin i can only fix issue with this error preventing plugin loading, but i cant add actual support for it at this moment. 
531813f1177f3b716ebc6c87869454f74cc94512

**Comment by ChrisFlyer7** [comment]
in fact you can download the free version from join the plugin 's Discord.

https://www.spigotmc.org/resources/kingdomsx.77670/

thanks for will fix the issue.
[image: 2020-07-13_182317.jpg]

Zrips <notifications@github.com> 於 2020年7月13日 週一 下午6:03寫道：
