### ISSUE TITLE
/res set wspeed1/2 join problem

### ISSUE THREAD

**Issue by flandretw** [Zrips/Residence#515]
Hi, the speed needs to corrected.
Player **logout** server with **wspeed**(1or2) flag in the residence and **rejoin again**, the flag doesn't work. Player recover normal speed.
Sorry my bad English.
Hope to receive a satisfactory reply as soon as possible.
Residence version is 4.9.1.3
Paper version is 1.15.2 build 374

**Comment by Zrips** [comment]
Can reproduce this issue at this time. You will need to retest it without any other plugin on server to make sure this is not a result of another plugin overriding players speed on join.

**Comment by gregman98** [comment]
I found the problem. 
Essentials causes speed to fail. But how do I make speed work again? (The Essentials setting is default.)

**Comment by gregman98** [comment]
@Zrips
