### ISSUE TITLE
[Feature request] Daily fees for residences

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Residence#521]
Hi, what about adding feature that could make a condition for players to have enough money to daily pay for residences. If they won't have money, then their residence will be deleted OR added to server account (or shop or something like this). So daily fees for owning residences.

**Comment by Zrips** [comment]
Lease system. You will need to enable it in config file and then adjust how often you want to charge money and how much for each residence player group which can be found in groups.yml file
