### ISSUE TITLE
Scoreboard bug money

### ISSUE THREAD

**Issue by Frax2554** [Zrips/Residence#524]
Hello, I have the problem that the marker of my server is bugging with the money that the works have (ex: Coins: 194.99999999932k) It is quite ugly, probe with premium marker and remains the same. I use vault, spigot 1.10, and the plugin is as I downloaded it.

**Comment by Zrips** [comment]
Money is usually handled by economy plugin which includes its format. As you have format with a K at end this will be issue with your economy plugin not formatting balance properly and not Residence plugin as it doesn't format balance in this way at all.

**Comment by Frax2554** [comment]
Okay, I remove the K and that's it?

**Comment by Frax2554** [comment]
Still the same

**Comment by Zrips** [comment]
Which economy plugin are you using? And where exactly are you getting this number? I need information...

**Comment by Frax2554** [comment]
I use vault, I put the variable% vault_ecobalance% and I let the reborn Jobs plugin work, when I have the explorer kit it adds money and the marker updates, but sometimes it buggers and it remains 6051.000000531

**Comment by Zrips** [comment]
This is residence plugin github, if you have issue related to Jobs Reborn plugin then you will need to post issue over there.
https://github.com/Zrips/Jobs/issues/new?assignees=&labels=Bug+Report&template=bug_report.md&title=
