### ISSUE TITLE
The Residence plugin cannot be used in spigot version 1.16.1 of Minecraft

### ISSUE THREAD

**Issue by xxxxj-up** [Zrips/Residence#538]
The Residence plugin cannot be used in spigot version 1.16.1 of Minecraft. You heard it right, it's totally unusable! ! !

**Comment by Zrips** [comment]
Sounds cool and dandy, issue is that it does work perfectly fine on 1.16.1 If you have any errors or you could elaborate on any actual details whats not working then let me know.

**Comment by xxxxj-up** [comment]
In a version that supports 1.16.1
If it is not the latest version, the update prompt will still pop up
All instructions can be completed using tab
The instructions resreload and reload return themselves
There was no response to the rest of the instructions
Sorry, my English is not very good, if there are grammatical errors, please forgive me

**Comment by xxxxj-up** [comment]
> Sounds cool and dandy, issue is that it does work perfectly fine on 1.16.1 If you have any errors or you could elaborate on any actual details whats not working then let me know.

In a version that supports 1.16.1
If it is not the latest version, the update prompt will still pop up
All instructions can be completed using tab
The instructions resreload and reload return themselves
There was no response to the rest of the instructions
Sorry, my English is not very good, if there are grammatical errors, please forgive me
