### ISSUE TITLE
/res TAB

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#539]
Autofill doesn't work on my server (for example / res creTAB). I don't know when it doesn't work. Tested yesterday on version 4.9.1.6 paperspigot and today on 4.9.1.7 tuinity. (both paper and tunity are the latest versions, ie 1.16.1)

**Comment by Zrips** [comment]
Works perfectly fine on a test server. Test it without any other plugin to rule out possible interference from one of them.

**Comment by 100petr** [comment]
Ok, I'll try. Thank you for your time.

**Comment by 100petr** [comment]
And it still doesn't work
![Screenshot_1](https://user-images.githubusercontent.com/29830635/90215202-42795880-ddfb-11ea-9991-9620914b8047.png)
