### ISSUE TITLE
Nether option broken residence selecting

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Residence#542]
Hi, in the newest version, when you try to select residence, using normally selecting tool and selecting two rows / using res select vert / using res select auto, none of these works. It says that your selection is so high (Y 256), that allowed is just 255... but this message prints even when you try to make normal selection and there's just 5 Y difference between first and second point. Still same message will appear.

**Comment by Zrips** [comment]
9254fd19ff2a2fd254dda593201683e026ead684
