### ISSUE TITLE
[Feature request] Res auto - % from max size / per group max

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#547]
Hi, I wanna ask for feature that will limit res auto. Imagine, if I have VIP rank with 400*400 and people are a little bit lazy, they will do /res auto instead of selecting normal residence size. Then it maybe will be good to make res auto size per group, or limiting it by %, for ex. just 50% could be used in /res auto, so for this example via res auto they can make just 200*200 area. I think it's useful when people wanna make residence, do /res auto, but don't need whole area on what they have permission to create.

**Comment by 100petr** [comment]
Up

**Comment by Zrips** [comment]
fbb7af05d52472dbf481c8f0e07e3af6ee99c70b

**Comment by 100petr** [comment]
will it be configurable or optional in the command?
