### ISSUE TITLE
[Bug] ./res unstuck not working

### ISSUE THREAD

**Issue by blek-id** [Zrips/Residence#557]
As an OP, I can't use /res unstuck, and it says that I don't have the permission for this. I even used /resadmin unstuck and it's still the same result.

I'm using version 4.9.1.9
with Paperspigot 1.15.2

**Comment by Zrips** [comment]
05ace77e99f2bfd2f66a8149f16045674ebcfa54
Tho mainly issue was from your residence group not having unstuck access. But with next version we will check for resadmin just avoid this confusion in future
