### ISSUE TITLE
Action bar message

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#558]
I have a ProtocolSupport plugin on the server that allows you to connect with other versions. The server is running version 1.16.2 and if the player has version 1.15.2 or lower in the action bar, he sees the entry / exit messages in white, but they are set to yellow. 
It was written on their github that this is due to the old use of imaging. Can you look at it, please? 
https://github.com/ProtocolSupport/ProtocolSupport/issues/1273

**Comment by Zrips** [comment]
In general this should not happen, action bar handling was updated with 1.16 minecraft version to use JSON format instead of old plane text. So hard to say whats going on here exactly. By any chance you are using hex colors for those messages?

**Comment by 100petr** [comment]
No, I have this in groups.yml
```    Messaging:
      CanChange: true
      DefaultEnter: Vitej v residenci %residence, vlastnene hracem %owner.
      DefaultLeave: Odesel jsi z residence %residence.```
Maybe try to put &e before the message?

**Comment by Zrips** [comment]
Should be working correctly with latest build
