### ISSUE TITLE
A BUG， When hold an item not in blacklist then left click chest.

### ISSUE THREAD

**Issue by MikuSnow** [Zrips/Residence#559]
It tell me "You are blacklisted from using this item here."
And the flags.yml:
`
ItemList:
  DefaultList:
    Type: blacklist
    Items:
    - BEDROCK
    - LAVA
    - WATER
    - STATIONARY_LAVA
    - STATIONARY_WATER
    - MOB_SPAWNER
`
The type is blacklist .
But when I set the type to whitelist.
Then hold an item like GRASS, then click the chest it wont tell me anymore.

**Comment by MikuSnow** [comment]
Even I am not in a residence.

**Comment by Zrips** [comment]
Should be fixed
