### ISSUE TITLE
/Res pset [Player] trusted true or /res padd [Player]

### ISSUE THREAD

**Issue by Barbarx** [Zrips/Residence#56]
Residence version: 4.6.3.0
Paperspigot: 1.11.2
Language: Czech

Hello. all works but is one bad message after this command
"Invalid flag"
Images:
http://imgur.com/a/GilF2

**Comment by Zrips** [comment]
Bucket flag is still in trusted grouped flag section. Will remove from default file and you can do same to avoid that message in future.

**Comment by shikendon** [comment]
Make a reference here  ea04fef23eea1e96e18aa836682133f188bceae9
