### ISSUE TITLE
Hoglins Spawn in the Residence

### ISSUE THREAD

**Issue by IwasConfused** [Zrips/Residence#561]
The hoglins still spawn in my residence even when I turn off all the flags like c/n/s/monsters or c/n/s/animals，so that I have to summon iron golems to kill them.
What should I do? Is it a bug？

Version: 4.9.1.9
Server version: 1.16.2

**Comment by Shadowhackercz** [comment]
I can confirm this, happens to me too with the same version and server version of Paper 204 for 1.16.3

**Comment by Zrips** [comment]
Some what a bug, dint included Hoglin into animal list.
ed92ff20f7ee087e61a3f7381b09f06031ada253
