### ISSUE TITLE
Players are griefing inside residences (new bypass?)

### ISSUE THREAD

**Issue by Baterka** [Zrips/Residence#562]
I have occasionally some player on my 1.16.2 PaperMC server with the latest Residence griefing residences without permission to build/destroy.

Seems like they are able to destroy blocks in protected areas and maybe also place blocks.

Any ideas on how? :D

**Comment by Baterka** [comment]
Anyone having same problem??

**Comment by Zrips** [comment]
Without a way to reproduce issue we cant really test it out and figure out why player had this access. In general player could have access to bypass permissions like residence.bypass.destroy residence.bypass.build or he has resadmin enabled on him or you have enabled materials in flags.yml file under ItemList section
