### ISSUE TITLE
Latest version of Residence doesn't work with 1.12.2 Slimefun

### ISSUE THREAD

**Issue by Leyji** [Zrips/Residence#566]
Plugin refuses to startup because of Slimefun (and CSCoreLib) being outdated (latest version for 1.12.2). There is no way of using Residence + Slimefun on 1.12.2. Of course I don't want you to add support for old Slimefun, just make the plugin at least working without the hook, thanks.

Error: https://pastebin.com/VPsrYrkK

**Comment by Zrips** [comment]
f93780c45783fc686a9c8056b9761df111002426
