### ISSUE TITLE
Residence fly bug

### ISSUE THREAD

**Issue by 28451553** [Zrips/Residence#567]
https://sendvid.com/898ajjh7

**Comment by Zrips** [comment]
I need more information on this one and did you used latest version of residence? Server version?

**Comment by 28451553** [comment]
yes it's new  Residence
it's 1.16.3


Zrips <notifications@github.com> 於 2020年10月1日 週四 下午6:14寫道：

**Comment by Zrips** [comment]
4fa22a52f71392e7aab64403c1c08b90904f62eb
