### ISSUE TITLE
Subzones can't be created

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Residence#568]
Hi, subzones can't be created neither via selecting with tool neither via command. Same issue prob. as with https://github.com/Zrips/Residence/issues/542, I just didn't notice it before, just one month ago, but you didn't respond on Discord last time.

**Comment by Zrips** [comment]
I need more information on this one. Could you provide config file for testing and some basic walk throw how to create this issue exactly? As currently after some testing everything seams to be working correctly and there are no issues while creating subzones in normal or nether worlds

**Comment by Volgeop** [comment]
Oh wtf, it now works for me too.... I'm closing it for now, really weird that it didn't work very long time and now it started working.
