### ISSUE TITLE
[FEATURE REQUEST] HONEY / HONEYCOMB COLLECTION FLAG.

### ISSUE THREAD

**Issue by EkonC** [Zrips/Residence#569]
Hi, I think residence plugin needs a flag that would prevent honey and honeycomb from being collected. It would be really great addition because currently when an unwanted player comes to your residence, he can collect the honey which will anger the bees that sting him and eventually die because of that.

**Comment by Zrips** [comment]
92aab56945f33c103fb3f72adc8276e52f2929a9
