### ISSUE TITLE
Can't create a residence.

### ISSUE THREAD

**Issue by iistutter** [Zrips/Residence#571]
Everytime I try to create a residence it doesnt say anything in game but crashes the server and spams the console with permissions errors even though I'm OP, and have the "*" permission, it also says "THIS IS NOT AN ERROR DO NOT REPORT THIS TO BUKKIT/SPIGOT" in the console with the errors.

**Comment by Zrips** [comment]
Without actual error logs i cant determine what caused it to happen.
