### ISSUE TITLE
When newcomer remove free residence, he'll get money

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#572]
Hi, this probably shouldn't happen. When newcomer get residence for free when he place chest, and then remove this residence, he get money from it. He probably shouldn't. Do you think it could be changed somehow? For ex. if residence is marked as newcomer's one, then won't give money on removing?

**Comment by Zrips** [comment]
Issue would be with that same residence being expanded later on, which quite likely action by the player, but then, if he does that when he tries to remove it he will not receive any money as residence will be market as newbie one. In general you could simply set first rank player will have when they place first chest to not return any money on residence removal, for example lets say you have "newbie" residence group which is default one player gets, set its SellCost to 0, then player will not receive any money when he removes it even if he rises his rank, as sell cost is recorded when residence is created by players current rank. This isint best solution but in general that would get you same result as you want.
