### ISSUE TITLE
Player's can't create subzone in residence

### ISSUE THREAD

**Issue by MrWakeCZ** [Zrips/Residence#574]
Hi, 
I found some interesting bug. When a player tries to create a subzone, the plugin stops the action with the response that `Your X selection length (6) is too big. Allowed 0 and less.`. And in /res info residence have height 254 blocks, but in config is 256. I tried to use `/res expand 1` and look up but did not help. 

I did not change anything in the residence limits config for months and I use the latest version `4.9.1.9`.

- config.yml: https://pastebin.com/q69nEky6
- groups.yml: https://pastebin.com/W1d0qh58

**Comment by 100petr** [comment]
You don't have subzone sizes in groups.yml
See https://github.com/Zrips/Residence/blob/master/src/groups.yml

**Comment by WolverStones** [comment]
> You don't have subzone sizes in groups.yml
> See https://github.com/Zrips/Residence/blob/master/src/groups.yml

it's also happening on the server and I think that everything in the group is set up correctly, I didn't change anything and so far it worked until the last updates

**Comment by 100petr** [comment]
Did you open the link I was sending?

**Comment by WolverStones** [comment]
> Did you open the link I was sending? You would see the differences.

yeah i can see it now 👍 sorry

**Comment by MrWakeCZ** [comment]
Yeah, fixed by adding `MaxSubzonesInArea` and other subzone properties. Thanks for your help. 😄
