### ISSUE TITLE
destroy spam

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#575]
Players report to me that when they right-click, it tells them that they are not allowed to destroy here. I think it will be a slimefun or some of its addons.
Residence 4.9.1.9, paper 1.16.3 #216
https://youtu.be/OmEoSrYuH2g

**Comment by 100petr** [comment]
I forgot about this. I was trying to figure out exactly which addon caused it. But it will probably be connected with other addons.
I had these add-ons on the server at the time and it was spamming. 
![image](https://user-images.githubusercontent.com/29830635/95461868-0552c200-0977-11eb-9b0a-1c489703d753.png)

**Comment by Volgeop** [comment]
I can confirm it... It's happening when you click on almost everything... on ender chests, on armor stands, ... @Zrips

**Comment by 100petr** [comment]
By the way, the player has already sent me this problem on 4.8.

**Comment by Volgeop** [comment]
Yeah, it occurs the long time.

**Comment by Zrips** [comment]
issue is with slime fun firing bunch of events when player interacts with some specific effects. Looking into it.

**Comment by bobhenl** [comment]
Btw spams too after clicking on CMI interactive blocks with right click (heads, armor stands...), almost everytime after interacting with right click

**Comment by bobhenl** [comment]
Zrips please mainly fix this issue

**Comment by 100petr** [comment]
@Zrips

**Comment by 100petr** [comment]
EG issue.
