### ISSUE TITLE
Fly flag disable normal flying when teleporting from residence

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#580]
Hi, when you allow fly:true in your residence and then teleport to area where isn't this flag... but you have FLY flag by CMI and you may have it also enabled via /fly normally, then your fly is still disabled. People are annoyed from it, when they're in residences, teleport somewhere and they'll loose their fly, when they should normally use it outside residence too, but it got disabled.

**Comment by Zrips** [comment]
e650cc603067b999faac2f1b10ccd110b4cbfd97
