### ISSUE TITLE
How do I Define the Cost Per Block for Different User Groups

### ISSUE THREAD

**Issue by caesar-oculus** [Zrips/Residence#584]
Looking to have the cost per block for residence creation and expansion different for different user groups.

I would like to use Luckperms to set this, but I can't find where the cost per block is defined in the Residence config file, so I'm not sure what permission to set.

Please help?

**Comment by Zrips** [comment]
Cost per block is defined if groups.yml file under BuyCost section which will determine one block cost. Players ingeriting different groups will have different costs of it.
