### ISSUE TITLE
Unable to transfer money

### ISSUE THREAD

**Issue by Str00pwafel** [Zrips/Residence#586]
I get an error 'sorry, unable to transfer money'. when trying to rent. havent tried buying, since i have nothing build to set on sell yet.

There is enough money. Using Xconomy and Vault.

Specific permissions needed?

**Comment by Zrips** [comment]
tested out with your economy plugin, renting seams to work properly. Do you get message on startup which looks something like this 
`[13:44:26 INFO]: [Residence] Found Vault using economy system: XConomy`

**Comment by A1yshia** [comment]
hey, I am also having this issue. I use vault and essentialsx

[config (1).yml](https://github.com/user-attachments/files/27091033/config.1.yml) = residence config

[config (2).yml](https://github.com/user-attachments/files/27091034/config.2.yml) = essentialsx config

Im really struggling to figure it out. is there any specific perms or anything i need to change in the config files?

**Comment by A1yshia** [comment]
### Console upon startup:

25.04 22:55:09 [Server] INFO [Residence] Found WorldEdit 7.4.0+7381-3decaf0
25.04 22:55:09 [Server] INFO [Residence] Pl3xMap residence activated!
25.04 22:55:09 [Server] INFO [Residence] Enabled! Version 6.0.1.6 by Zrips
25.04 22:55:09 [Server] INFO [EssentialsGeoIP] Enabling EssentialsGeoIP v2.22.0-dev+104-87bde72
25.04 22:55:09 [Server] INFO [EssentialsGeoIP] This product includes GeoLite2 data created by MaxMind, available from http://www.maxmind.com/.
25.04 22:55:09 [Server] INFO [EssentialsGeoIP] Starting Metrics. Opt-out using the global bStats config.
25.04 22:55:09 [Server] INFO [EssentialsChat] Enabling EssentialsChat v2.22.0-dev+104-87bde72
25.04 22:55:09 [Server] INFO [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
25.04 22:55:09 [Server] INFO [packetevents] Enabling packetevents v2.11.2
25.04 22:55:09 [Server] INFO [packetevents] Checking for updates, please wait...
25.04 22:55:09 [Server] INFO [TAB] Enabling TAB v5.5.0
25.04 22:55:09 [Server] INFO [TAB] [WARN] [groups.yml] Unknown property "header" defined for group "example_group". Valid properties: [tagprefix, tagsuffix, tabprefix, customtabname, tabsuffix]
25.04 22:55:09 [Server] INFO [TAB] [WARN] [groups.yml] Unknown property "footer" defined for group "example_group". Valid properties: [tagprefix, tagsuffix, tabprefix, customtabname, tabsuffix]
25.04 22:55:09 [Server] INFO [TAB] [WARN] [groups.yml] Unknown property "customtagname" defined for group "_DEFAULT_". Valid properties: [tagprefix, tagsuffix, tabprefix, customtabname, tabsuffix]
25.04 22:55:09 [Server] INFO [TAB] [WARN] Found a total of 3 issues.
25.04 22:55:09 [Server] INFO [TAB] Enabled in 112ms
25.04 22:55:09 [Server] INFO [SuperVanish] Enabling SuperVanish v6.2.21
25.04 22:55:10 [Server] INFO [SuperVanish] Hooked into PaperSpigot for server list ping support
25.04 22:55:10 [Server] INFO [SuperVanish] Hooked into Essentials
25.04 22:55:10 [Server] INFO [EssentialsSpawn] Enabling EssentialsSpawn v2.22.0-dev+104-87bde72
25.04 22:55:10 [Server] INFO [EssentialsSpawn] Starting Metrics. Opt-out using the global bStats config.
25.04 22:55:10 [Server] INFO [CoreProtect] Enabling CoreProtect v23.4
25.04 22:55:10 [Server] INFO [packetevents] There is an update available for PacketEvents! Your build: (2.11.2) | Latest release: (2.12.1)
25.04 22:55:10 [Server] INFO [CoreProtect] CoreProtect has been successfully enabled! 
25.04 22:55:10 [Server] INFO [CoreProtect] Using SQLite for data storage.
25.04 22:55:10 [Server] INFO --------------------
25.04 22:55:10 [Server] INFO [CoreProtect] Enjoy CoreProtect? Join our Discord!
25.04 22:55:10 [Server] INFO [CoreProtect] Discord: www.coreprotect.net/discord/
25.04 22:55:10 [Server] INFO --------------------
25.04 22:55:10 [Server] INFO [EssentialsDiscord] Enabling EssentialsDiscord v2.22.0-dev+104-87bde72
25.04 22:55:10 [Server] INFO [EssentialsDiscord] Starting Metrics. Opt-out using the global bStats config.
25.04 22:55:10 [Server] INFO [EssentialsDiscord] Attempting to login to Discord...
25.04 22:55:11 [Server] INFO [net.essentialsx.dep.net.dv8tion.jda.api.JDA] Login Successful!
25.04 22:55:11 [Server] INFO [net.essentialsx.dep.net.dv8tion.jda.internal.requests.WebSocketClient] Connected to WebSocket
25.04 22:55:12 [Server] INFO [net.essentialsx.dep.net.dv8tion.jda.api.JDA] Finished Loading!
25.04 22:55:12 [Server] INFO [EssentialsDiscord] Successfully logged in as ConcordCore#5692
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Enabling QuickShop-Hikari v6.2.0.11
25.04 22:55:17 [Server] INFO [QuickShop-Hikari/Bootstrap] QuickShop-Hikari - Bootstrap -> Execute the enable sequence
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] QuickShop Hikari
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Registering Bukkit Service: com.ghostchu.quickshop.api.QuickShopProvider
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Starting plugin self-test, please wait...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] Spigot Based Server Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] Old QuickShop Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] ModdedServer Based Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] ModdedServer Database Driver Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] CoreSupport Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] Virtual DisplayItem Support Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] ProtocolLib Incorrect Locate Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] GameVersion supporting Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] Permission Manager Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] PacketListenerAPI Conflict Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] Reremake Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] EcoEnchants V11 Check
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] End of life Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Reading the configuration...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Contributors: Ghost_chu, PotatoCraft Studio, Netherfoam, Timtower, KaiNoMood (KaiKikuchi), sandtechnology, jho5245, cakoyo, Andre601, Ectabro, Chris6ix, portlek, log4b0at, deadman96385, tiararinne, DoctaEnkoda, CarmJos, YuanYuanOwO, Mgazul, mart-r, Tim269, raphtaliapt, creatorfromhell, LoneDev6, Steven-OS, confuxeon, ibmibmibm, judgetread, mfnalex, Warriorrrr, PyvesB, yannicklamprecht, ORelio, RMSCA, Starmism, yiwenwang2090, PaulBGD, Nlkomaru, harry0198, Draesia, Localized community members on Crowdin
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Original author: Netherfoam, Timtower, KaiNoMood, sandtechnology
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Let's start loading the plugin
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Setting up ItemExpressionRegistry...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Using Virtual Displays. Attempting to initialize packet factory...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Setting up database...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Create database backup...
25.04 22:55:17 [Server] INFO [com.ghostchu.quickshop.shade.carm.easysql.hikari.HikariDataSource] HikariPool-1 - Starting...
25.04 22:55:17 [Server] INFO [com.ghostchu.quickshop.shade.carm.easysql.hikari.HikariDataSource] HikariPool-1 - Start completed.
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Checking and updating database columns, it may take a while...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Database upgrade script running... Current Database Version: 19
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Finished!
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Selected permission provider: Bukkit
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Registering commands...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Loaded 1 rules for listener blacklist.
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] EventManager selected: QSEventManager
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Loading shops from database...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Used 58ms to fetch 1198 shops from database.
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Loading shops into memory...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Used 323ms to load 0 shops into memory (1198 shops will be loaded after chunks/world loaded).
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Registering listeners...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Cleaning MsgUtils...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Cleaning purchase messages from the database that are over a week old...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Log actions is enabled. Actions will be logged in the qs.log file!
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [Shop Purger] Purge not enabled!
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] [OK] Virtual DisplayItem Support Test
25.04 22:55:17 [Server] INFO [QuickShop-Hikari] Initializing built-in hooks...
25.04 22:55:17 [Server] INFO [QuickShop-Hikari/Bootstrap] QuickShop-Hikari - Bootstrap -> All Complete. (680ms)
25.04 22:55:17 [Server] INFO [VotingPlugin] Enabling VotingPlugin v7.0
25.04 22:55:17 [Server] INFO [VotingPlugin] Loaded LuckPerms hook!
25.04 22:55:17 [Server] INFO [VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
25.04 22:55:18 [Server] WARN [VotingPlugin] VoteStreaks is missing or not a section; no streaks loaded.
25.04 22:55:18 [Server] INFO [VotingPlugin] Enabled VotingPlugin 7.0
25.04 22:55:18 [Server] INFO [Vulcan] Enabling Vulcan v2.9.7.16
25.04 22:55:18 [Server] INFO [Vulcan] Starting Vulcan... Server Version: 1.21.11 detected!
25.04 22:55:18 [Server] INFO [Vulcan] Registering NMS TickEnd fallback...
25.04 22:55:18 [Server] INFO [Vulcan] Floodgate 2.0 found. Enabling hook!
25.04 22:55:18 [Server] INFO [Vulcan] BStats enabled!
25.04 22:55:18 [Server] INFO [net.essentialsx.discordlink.EssentialsDiscordLink] Enabling EssentialsDiscordLink v2.22.0-dev+104-87bde72
25.04 22:55:18 [Server] INFO [net.essentialsx.discordlink.EssentialsDiscordLink] Starting Metrics. Opt-out using the global bStats config.
25.04 22:55:18 [Server] INFO [spark] Starting background profiler...
25.04 22:55:18 [Server] INFO [Geyser-Spigot] ******************************************
25.04 22:55:18 [Server] INFO [Geyser-Spigot] 
25.04 22:55:18 [Server] INFO [Geyser-Spigot] Loading Geyser version 2.9.5-b1108 (git-master-6c38dc7)
25.04 22:55:18 [Server] INFO [Geyser-Spigot] 
25.04 22:55:18 [Server] INFO [Geyser-Spigot] ******************************************
25.04 22:55:19 [Server] INFO [Geyser-Spigot] Started Geyser on 88.211.228.244:25672
25.04 22:55:19 [Server] INFO [Geyser-Spigot] Done (1.243s)! Run /geyser help for help!
25.04 22:55:20 [Server] INFO Running delayed init tasks
25.04 22:55:20 [Server] INFO [InventoryRollbackPlus] Checking for updates...
25.04 22:55:20 [Server] INFO [Essentials] Fetching version information...
25.04 22:55:20 [Server] INFO [QuickShop-Hikari] Start to caching usernames (async)...
25.04 22:55:20 [Server] INFO [ViaVersion] Finished mapping loading, shutting down loader executor.
25.04 22:55:20 [Server] INFO [DecentHolograms] Loading holograms... 
25.04 22:55:20 [Server] INFO [Vault] Checking for Updates ... 
25.04 22:55:20 [Server] INFO [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
25.04 22:55:20 [Server] INFO [Vault] No new version available
25.04 22:55:20 [Server] INFO ===============================================================================
25.04 22:55:20 [Server] INFO A feature update to InventoryRollbackPlus is available!
25.04 22:55:20 [Server] INFO Download at https://www.spigotmc.org/resources/inventoryrollbackplus-1-8-1-16-x.85811/
25.04 22:55:20 [Server] INFO (current: 1.7.9, latest: 1.8.2)
25.04 22:55:20 [Server] INFO ===============================================================================
25.04 22:55:20 [Server] INFO [QuickShop-Hikari] A new version of QuickShop has been released! [6.3.0.0-SNAPSHOT-5]
25.04 22:55:20 [Server] INFO [QuickShop-Hikari] Update here: https://modrinth.com/plugin/quickshop-hikari
25.04 22:55:20 [Server] INFO [DecentHolograms] Loaded 125 holograms!
25.04 22:55:20 [Server] INFO Skulls » Loaded 117241 skulls in 11,274.790ms
25.04 22:55:20 [Server] INFO [CoreProtect] WorldEdit logging successfully initialized.
25.04 22:55:20 [Server] INFO [QuickShop-Hikari] Using economy system: EssentialsX Economy
25.04 22:55:20 [Server] INFO [QuickShop-Hikari] Selected economy bridge: BuiltIn-Vault
25.04 22:55:20 [Server] WARN [ViaVersion] There is a newer plugin version available: 5.9.0, you're on: 5.8.1
25.04 22:55:20 [Server] Startup Done (28.240s)! For help, type "help"
25.04 22:55:20 [Server] INFO Skulls » Running database check :)
25.04 22:55:20 [Server] INFO [Not Secure] [Server] [EchoSupport] Datapack loaded.
25.04 22:55:20 [Server] INFO *** Currently you are 3 build(s) behind ***
25.04 22:55:20 [Server] INFO *** It is highly recommended to download the latest build from https://papermc.io/downloads/paper ***
25.04 22:55:21 [Server] INFO Skulls » Everything looks up-to-date, no issues found. Enjoy!
25.04 22:55:25 [Server] INFO [VotingPlugin] Successfully hooked into vault economy!
25.04 22:55:25 [Server] INFO [VotingPlugin] Hooked into vault permissions
25.04 22:55:30 [Server] INFO [VotingPlugin] VotingPlugin is up to date! Version: 7.0
