### ISSUE TITLE
Water isn´t flowing on version 1.15.2

### ISSUE THREAD

**Issue by ondrejberan** [Zrips/Residence#587]

**Comment by s7an1slaw** [comment]
Hey i can help you, 1st open config.yml in Residence folder and search Flow, this is what you need to find:

    Flow:
      # Level from which one to start lava and water flow blocking
      # This dont have effect in residence area
      Level: 63
      # With this set to true, lava flow outside residence is blocked
      NoLavaFlow: false
      # With this set to true, water flow outside residence is blocked
      NoWaterFlow: false
      Worlds:
      - world

Make NoLavaFlow - false and NoWaterFlow - false write as if it happened.

**Comment by Zrips** [comment]
@ondrejberan 
One sentence issue description is not much to go on. But as @s7an1slaw pointed out, you can check grief protection section which could be blocking water flow after certain altitude outside residences. Then you might want to check global flags set for each world in flags.yml which might contain waterflow: false
