### ISSUE TITLE
Problem with Flag-permissions

### ISSUE THREAD

**Issue by insanehase** [Zrips/Residence#589]
I set permissions for flags by ranks
But the first rank can use the flags from the last rank..

what can I do?

**Comment by Zrips** [comment]
I need groups.yml of yours to test things or atleast actual example of your setup

**Comment by insanehase** [comment]
I named  it with ".txt" for the upload

[groups.txt](https://github.com/Zrips/Residence/files/5561410/groups.txt)

**Comment by Zrips** [comment]
Your groups file doesn't have any specific flag setup, so my guess would be that you have them enabled globally in flags.yml file for everyone and thats why every rank can use same flags
