### ISSUE TITLE
players are needing to allow building for themselves in there own res

### ISSUE THREAD

**Issue by chillerkraft** [Zrips/Residence#59]
players eventually end up needing to do /res pset therename to re allow building for themselves in there residence. they never disallowed building. it happened to me too

**Comment by Zrips** [comment]
Any way to reproduce this issue? Or its random?

**Comment by chillerkraft** [comment]
it's random
could this issue have anything to do with me using the wrong versions of worldguard and or residence? i'm using latest dev build of worldguard which i was told i shouldn't by wizjany yesterday.. so i still need to downgrade my worldguard.. and residence, im using the latest version on 1.11.2
