### ISSUE TITLE
Smelting Furnace bug

### ISSUE THREAD

**Issue by klaidoshka** [Zrips/Residence#590]
Hello,

We're kinda behind with the versions and are still using using **1.8.8 Paper**, Residence version : **4.8.5.0**. 😕 

So, the bug is from wayyyy lower versions and still in upper versions (the upper ones don't work anymore in 1.8.8 Paper atm, but whatever about that...)

**A block** - **Smelting_Furnace ID:62**(?) (when it's smelting something inside itself) is unprotected for interact/use, people can open it no matter the flags. I saw nothing in the configs/files about fixing it, so it's probably a problem in the code which I can't fix myself sadly... 😢 

Can something be done about it? Maybe a little rewrite for 4.8.5.0 or any simple tips for me to fix it? 😞

**Comment by Zrips** [comment]
What is the issue with newest version in your server? Errors or something doesn't work in general? I did some testing and burning furnace is protected under container flag. This could be caused by another plugin allowing interaction with furnace, but residence does protect blocks inside residence independent from its state

**Comment by klaidoshka** [comment]
> What is the issue with newest version in your server?

Copy of my message in the Residence discussions from spigotmc.org 😅 :

```
We're in 1.8.8 Paper, using residences, everything works fine, except these two things: Random TP just points out that there is a cooldown (nothing happens); teleportation to any residence leads into automatic-kick to spawnpoint (because of unsafe location).

The main problem is about the teleportation to residences... Whenever player/admin creates residence, the "tp position" becomes not the spot the player was, but y<0 (below bedrock) and then you can't tp to it anymore... How can I fix it? Nothing in configs about that... :(

** Nevermind, fixed it by going to lower version. Seems it's like that (the "errors") since around 4.8.5.X version. I guess only upper versions are fine with those things, not 1.7.10-1.8.X 
```

Another plugin could cause the bug for burning-furnace? I see, no idea what is causing the bug then :'/, we got Residence & WorldGuard for protection, so maybe it could be WorldGuard, don't know, will check out the settings/configs, but I don't think so, it mostly works like blocking certain use for all players as far as I remember, so... 😞 But I will check it out! Thanks for the answer =]

**Comment by Zrips** [comment]
Simplest way to test this bug would be to remove every plugin except residence and then check if issue persists or not, if its gone then we will know that another plugin causes this issue, if its still there, then its issue with Residence. But at this point you will need to do some testing as it does work correctly on my test server.
