### ISSUE TITLE
IgnoreLimits not ignoring residence count limits?

### ISSUE THREAD

**Issue by EkonC** [Zrips/Residence#592]
Hi, when players can't buy a residence over their max residence count limit from other players.

Groups.yml
`MaxResidences: 3`

```
# Whether or not to ignore the Residence size/count limits when buying a residence.
IgnoreLimits: true
```
In the IgnoreLimits it says that it ignores residence size and count limit. Ignoring size limits works perfectly but when players want to trade the residence (when the buyer already has the max residence count), it sends a message:
a) When using TryMe to trade residences - seller gets message: "You cant offer more residences, as (player) has reached max allowed limit.
b) When using /res market sell and /res market buy - buyer gets message: You already own the max number of residences your allowed to.

I'm not sure whether this is a bug or I just misunderstood the meaning of this configuration but I'd like to allow players to have their business with residences even without allowing them to create as many residences as they want.

**Comment by Zrips** [comment]
2c3fa17f584426025373d916e5e3d64d629d5cb9
