### ISSUE TITLE
Suggestion: Safe residence teleport

### ISSUE THREAD

**Issue by EkonC** [Zrips/Residence#594]
Hello, I would like to recommend a new, very appreciated feature to Residence plugin - safe residence teleport.
Many times in the End, it happened that players set Residence teleport location above the void and they simply kill them
The same problem is with teleport location in lava.

So basically - when teleporting to residence, the plugin would check if the set teleport location is safe (not in or above lava), not above void, on a solid block, ... simply like it is done in random teleport when finding a safe location. If it's not safe, it wouldn't let them teleport there or it would ask them for confirmation.

It could also check if the location is safe when setting it.

**Comment by Zrips** [comment]
e3c91c2184ab4b1e320fe73ac176a88fe2783fd1
