### ISSUE TITLE
Residence - Count of Subzones are not shown when using /res limits

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Residence#6]
I'm going to start compiling some of the outstanding issues and get them posted here for you so you have a running record of them in one easy location.  Thanks again by the way, for adding this option here. :-)

**/res limits** returns the following:
![image](https://cloud.githubusercontent.com/assets/10309346/22234377/bb7bb010-e1c5-11e6-9b5d-5ebfb5d51862.png)
what is missing is the following:
**Number of Subzones Owned:**
**Number of Residences Owned with Subzones:** 
**Conditional display**
When player is inside a residence, display how many subzones are in current residence.
**Number of Subzones in <Residence>:** 

Spigot 1.11.2 latest build
Residence 4.5.13.4

**Comment by Zrips** [comment]
Subzone count is not really useful information as it don't show any limitations you could have because of that. Same for count of residences with subzones, as subzones is more like flag system, its just allow to have better control over area and don't give any useful information about that. 
We could tho show subzone count when we are checking target residence information.

**Comment by smmmadden** [comment]
Thanks - the problem is when a large residence is created with many subzones, we can't tell how many subzones there are for that residence or whether the limit has been reached.  I'm okay with a user being in a residence with subzones and being able to get a total of subzones in the current residence.

**Comment by Zrips** [comment]
It will show something like "**Subzones in residence: 3 (6)**" when 3 is subzones in current residence and 6 is total number of subzones counting in subzones of subzones of subzones and so on.

**Comment by smmmadden** [comment]
that would be okay for those who have subzones in subzones to display when there are some.  By default, having "Subzones in residence: 3" (when there are no additional subzones) and "Subzones in residence: 3 (2) (1)"  Which would mean 3 subzones for ResidenceABC and within it there are 2 subzones in the primary subzone and one subzone in the secondary subzone.  This could get very ugly.  Perhaps simplifying it down to "Subzones in residence: 3" and if there are any embedded ones, just return "Residence has subzones in subzones: true".  Would that work better?
