### ISSUE TITLE
i cant create Subzones

### ISSUE THREAD

**Issue by RafaelPerea** [Zrips/Residence#601]
Hi, i bought the plugin now but y hace a problem, i can't create a subzone for my friends the plugin say:

"Your X selection length (5) is too big, Allowed 0 and less.
Area size is not within your allowed limits.
Unable to create subzone test1.

The subzone are inside in the residence region

**Comment by EkonC** [comment]
You have to configure this in groups.yml

**Comment by RafaelPerea** [comment]
where, i see all the configs, groups,yml too but nothing

**Comment by EkonC** [comment]
Have you tried clicking on group.yml and configuring the maximal size of a subzone for the group you are currently in?

**Comment by RafaelPerea** [comment]
Yes, but only work for me in 4.9.1.8 the subzones, anothers versions dont work the subzones or crash my server

**Comment by Leyji** [comment]
I have the same issue.

**Comment by RafaelPerea** [comment]
> I have the same issue.

I have you temporal solution, get the version 4.9.1.8, its work this version

**Comment by EkonC** [comment]
Okay after testing out this issue and trying to understand what you had written, I can say that you probably aren't in the group you want to be in. Use /res limits to show which group you are in

**Comment by 100petr** [comment]
https://github.com/Zrips/Residence/issues/574 probably the same problem

**Comment by RafaelPerea** [comment]
The problem is that even being the owner of the server, with OP and permission '*', that in /res limit I have infinite I also can not

**Comment by 100petr** [comment]
And what /resadmin? Send groups.yml ...

**Comment by RafaelPerea** [comment]
Right now I have version 4.9.1.8, still the problem even if it is the admins that can not, even modifying the user and the permission do not leave in4.9.2.2

**Comment by EkonC** [comment]
I asked you to send us a screenshot of /res limits and your groups.yml. We won't be able to help you if you are ignoring us trying to help you.

**Comment by Zrips** [comment]
dd20afffa849e875f21df04a29014888a113244f
