### ISSUE TITLE
Lectern can’t remove the book even if it has contauner permission, it cannot remove the book

### ISSUE THREAD

**Issue by gary81013** [Zrips/Residence#604]
Lectern can’t remove the book even if it has contauner permission, it cannot remove the book

**Comment by EkonC** [comment]
Players who own a res can't take books from lecterns. It says that they don't have container permissions.

Yes I can confirm this issue. It has been here for a while but I forgot to report it. A temporary solution for this is breaking the lectern.

**Comment by Zrips** [comment]
d9957fb5e4ef0c667efc7bfe7285f3d02d8494bf
