### ISSUE TITLE
Cannot Create Nether Portal in Residence

### ISSUE THREAD

**Issue by dragontekgaming** [Zrips/Residence#609]
I have looked through all the flags. I can set obsidian on fire, but the portal won't open. Is there a way to fix this?

**Comment by Zrips** [comment]
Residence doesn't limit portal creation, atleast i'm not aware of any code which would do that. Make sure that this actually originates from Residence and not another plugin or atleast try placing portal outside residence area. If you can confirm that this is residence issue, let me know, for time being closing this ticket.
