### ISSUE TITLE
permission plugin

### ISSUE THREAD

**Issue by loadka95** [Zrips/Residence#61]
im using groupmanager for permission plugin, but it doesn't recognize it and  everything is so messed up (player able to change every flags etc..), because of that...
[Before /res reload groups - ](http://imgur.com/a/HhCyX)
[After /res reload groups -](http://imgur.com/a/7QdlS)
PeX,luckyPerms doesn't work either
> 

> [16:44:24 INFO]: load issued server command: /res set
> >res reload groups
> [16:44:36 INFO]: [Residence] Permissions plugin NOT FOUND!
> [16:44:36 INFO]: [Residence] Reloaded groups file.

**Comment by smmmadden** [comment]
Did you just set this server up for the first time and it's not working right or did something change and now its not working?  All I saw was two screen shots of an Inventory which has nothing to do with permissions.  What version of the GroupManager plugin are you using and what Server are you running and version?  Don't assume everyone knows how your server is setup - provide more detail and we'll be able to help. :-)  For what it's worth,
GroupManager is no longer being supported by the developer and not recommended for use.  You can use [PermissionsEx](https://dev.bukkit.org/projects/permissionsex) or a newly revived [GroupManagerX](https://www.spigotmc.org/resources/groupmanagerx.32280/) if you don't want to go through the hassle of converting.

**Comment by Zrips** [comment]
Is this issue still an issue? Because everything seems to be loading properly with PEX
