### ISSUE TITLE
Command /res limits causes huge lag

### ISSUE THREAD

**Issue by TheLaoming** [Zrips/Residence#610]
Hello,
I don't know if anyone know about it, but command /res limits causes lag, and server lose over 10 tps. In latest version of Res.
It looks like basic /res limits command does it, and also /res limits nick. Sometimes loading so slowly data, sometimes normally. Only in 1.16.4, when I tried it with same files on 1.15.2, it worked fine. 
**Screenshots:**
[https://i.imgur.com/c8C7PwQ.png](url)
[https://i.imgur.com/lg9Z3i0.png](url)
**Using**
Yatopia 1.16.4
Build 1606925304738, 4
Tried also Paper

**Comment by Zrips** [comment]
What permission plugin are you using? As this seam to be relating to permission check which for some reason causes increased load in your situation.

**Comment by Zrips** [comment]
3cd3f98a9cfefb11ce8649b2a0fa6f02d33dafd4
