### ISSUE TITLE
/res rc setcolor DARK_PURPLE doesn't work? -> what are color codes?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#612]
Hi, I've tried this command /res rc setcolor DARK_PURPLE but it tells me unknown color code... even when in config is set DARK_PURPLE, so why it's unknown? What are right color codes then? Maybe it could tab complete them, or you could list them too in config.

**Comment by Zrips** [comment]
Yea, that part was some what unclear and well, limited, upgraded it to support color names like that in addition to all possible hex color codes, so you can even use 6600cc color code to define them or use name as cancan, full list can be found here https://www.zrips.net/cmi/hex-colors/
450ac42e89bb752498f24f663ca4014b9443a9a5
