### ISSUE TITLE
Bucket flag doesn't work

### ISSUE THREAD

**Issue by Eredrim** [Zrips/Residence#62]
Hello,

When I want to set or remove the bucket flag either in genreal or for a specific player, I get the error "invalid flag". I  use the lastest Spigot 11.2 version with the 4.6.3.0 residence version.

Regards,

**Comment by Zrips** [comment]
Bucket flag was removed dome time ago and now actions like bucketfill or bucketempty were assigned to build/destroy flags, next build will not have this flag in the config, to avoid confusion.
