### ISSUE TITLE
Disabing teleports to residence not owned by the player

### ISSUE THREAD

**Issue by DJIronic** [Zrips/Residence#620]
Hello,

I players are commonly misusing the feature of being able to port to another player's Residence. What we want is to have an option dissable teleport to other's Residences (ideally with permissions so we can enable it for mods and etc).

PS: I purchased Residence. (account DJ_Ironic)

Is that possible? Thanks!

**Comment by DJIronic** [comment]
Hello, Any ideas? It's sad to see that the support is nto active on a paid plugin 👎

**Comment by DJIronic** [comment]
Still nothing. I am sad.

**Comment by Zrips** [comment]
Checking groups.yml file you can see CanTeleport section which can prevent teleportation of player with this group to residences. Additionally you can set default flags for residences which would include tp: false flag and then you can use residence.bypass.tp permission node to bypass things like that. If you decide to disable teleportation from groups file you might check Global.Optimizations.CanTeleportIncludeOwner in config file which can allow owners of residence to teleport to their own residence while not being allowed to teleport to some one elses.
