### ISSUE TITLE
[bug] Residence enter/leave TitleBar message's placeholder %subtitle% not work.

### ISSUE THREAD

**Issue by momoservertw** [Zrips/Residence#623]
![image](https://user-images.githubusercontent.com/38014059/102952328-df66a380-4509-11eb-9e71-e2a6ce1fd4a7.png)

![image](https://user-images.githubusercontent.com/38014059/102952218-a3cbd980-4509-11eb-8123-f2cad3348e27.png)

Residence version: 4.9.2.2
Paper version git-Paper-333 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
2cfdf9ae1cf1a08f711f06df0ec09f922b3fa22c
