### ISSUE TITLE
Chunk strong loading of Residence

### ISSUE THREAD

**Issue by Karounac58** [Zrips/Residence#624]
Hello,I am a user of your product.I want to ask a question,
how to close the chunk strong loading of residence?
This effect is like a player hanging up on the territory forever,And crops grow when there is no one.
The brush tower in my server also can't work because of this problem.
I'm sorry to disturb you,I'd appreciate it if you could help me with this question  )

**Comment by Zrips** [comment]
Chunk onloading is controlled by server itself or by another plugin. Residence plugin doesn't have effect on that.
