### ISSUE TITLE
Subzone /setowner resets all permissions within it

### ISSUE THREAD

**Issue by Robertovaquerici** [Zrips/Residence#626]
Title is pretty self-descripting. More details:
When changing the owner of a subzone, every flag (both player and general) gets removed and reset to default.

This is admin hell right now for me.

**Comment by Zrips** [comment]
True that. Will add extra variable as -keepflags when setting new owner to keep old flags without resetting them to default ones
710cdfdf082e7f47ab93d406d6dc1e672a81bc9f
