### ISSUE TITLE
[Bug] can't protect chest for residence

### ISSUE THREAD

**Issue by nicklly** [Zrips/Residence#630]
![PR%DOX_EJ7VZWF(O6Y} ZZQ](https://user-images.githubusercontent.com/17716585/103354535-c7cd8300-4ae6-11eb-83fb-12f443200eba.jpg)
![SN7VW![PR%DOX_EJ7VZWF(O6Y} ZZQ](https://user-images.githubusercontent.com/17716585/103354535-c7cd8300-4ae6-11eb-83fb-12f443200eba.jpg)
CL(X}GDK4FOSB}P9](https://user-images.githubusercontent.com/17716585/103354540-cbf9a080-4ae6-11eb-99a3-e57285e149c9.jpg)
![QYEX83ALA363CB4X 5@GL4W](https://user-images.githubusercontent.com/17716585/103354545-ce5bfa80-4ae6-11eb-93ad-11a8269014d6.jpg)

As the picture shows.... I stood outside the residence, holding the boat in my right hand, and from outside the territory, I can directly open the box on the edge of the residence

I using plugin version is 4.9.1.9
but try update to 4.9.2.2 the bug is still exist

**Comment by Zrips** [comment]
98018e13af40aa1ae1e00961d647b7d1268da58a

**Comment by Baikele** [comment]
@Zrips   I use it in 5.1.1.1, and there is still this BUG
