### ISSUE TITLE
Tpset underground.

### ISSUE THREAD

**Issue by DaugKulku** [Zrips/Residence#633]
Players create a residence with / res create when they create residence, tpset appears in underground, then if you have set / res kick, the teleportation location, the script / res tp, and the name of the residence are teleported to the location where is / res kick location is set.
Please fix or help

**Comment by Zrips** [comment]
How does residence itself look like? I mean, is entire residence area underground or above ground? /res kick will try to find empty space outside residence to place player in while /res tp will try to send player to the center of residence and to top block. Some extra information would be nice to have about this particular situation.

**Comment by DaugKulku** [comment]
Residence area is above ground.

**Comment by DaugKulku** [comment]
But when they set /res tpset on they on it's working perfectly but then they do /res auto or res create whit res select, the tpset appear in underground

**Comment by Zrips** [comment]
Which minecraft version are you running?

**Comment by DaugKulku** [comment]
1.8.8

**Comment by Zrips** [comment]
e0c956201d6b36035f184cc0934fc23fb6f784e8
