### ISSUE TITLE
Multiple SelectionToolId

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#636]
Hi, could you please add way to add more tools to SelectionToolId? So we can use for ex.:
`SelectionToolId: BONE, WOODEN_HOE`

Would be useful cause it's different on specific servers and this way we can make it easier for players.

**Comment by Zrips** [comment]
It is different on different servers and some times it interferes with another plugin using same item for selections. But having multiple items for selection will not resolve issue, you have to define one tool for selection and go with it, players will get more confused when multiple tools start performing same tasks.
