### ISSUE TITLE
res listall on console showing only 20 out of xxxxx

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Residence#64]
Just installed the 4.7.0.0 version and **res listall** in the console used to display all the residences with no pagination but I know there was the other bug that needed addressing.  

However, now the console is showing the first 20 and server admins will need to follow up with **res listall 2** to get the next, **3** for the next, and so on.  Was this intentional?  

Perhaps a **res listall -p** to print to a text file or something like that for worlds like you test with 40k plus, especially since the console in windows is limited to 9,999 buffered lines.  Thanks!

**Comment by Zrips** [comment]
There was bug which prevented to output full list with -a variable, will fix that and will add option to print residence list into a separate file.
