### ISSUE TITLE
The big problem with nametag and Armor Stand Editor 4.9.2.3

### ISSUE THREAD

**Issue by chung12322** [Zrips/Residence#640]
![image](https://user-images.githubusercontent.com/77892565/105607650-ed466780-5dda-11eb-9fa2-ebe063c4180c.png)

I cant use Armor Stand Editor plugin after update the nametag, it keep display dont have perm of nametag.
When I dont at res, it still happen.

**Comment by Teleriann** [comment]
Yes, we have same problem, we had to switch version to older one.

**Comment by Zrips** [comment]
4731bb5e558eaf0de90ca24ff9c95f402350f791
