### ISSUE TITLE
Exclude default flags for dynmap section too

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#642]
Hi, could you please add way to exclude default flags for dynmap section too? Cause now it's really weird.
![image](https://user-images.githubusercontent.com/18662086/105731637-e54c0c00-5f2f-11eb-869f-c78c3ee5e039.png)
Look at this big list... when you click on something this big window appears...

Try yourselves: https://survival.trinitymc.eu/

I think that good solution could be      
```
 # When set to true default residence flags set in flags.yml file will get excluded from info command output and will not be shown
      # If flag gets different state then it will be shown
      ExcludeDefaultFlags: true
```
like in info command section, or make pagination system.

**Comment by Zrips** [comment]
d17e69a2f06e912d79de48e93007cf4229bb32f6
