### ISSUE TITLE
command flag?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#643]
Hi, how exactly does command flag work please? Where could we specify which commands will be disallowed? Cause I've set /resadmin command false and players can do every commands... I didn't find any option in config, so?

**Comment by bobhenl** [comment]
And even when I've added it via /resadmin command pvp block feed etc... players still can use these commands in residence.

**Comment by Zrips** [comment]
You still need to add command flag as false into residence itself. So basic **/resadmin set command false** will trigger command protection in the residence
