### ISSUE TITLE
fly out of residence

### ISSUE THREAD

**Issue by LtSam** [Zrips/Residence#645]
My players are able to fly when they leave the protections that have the fly flag activated.

I'm using 4.9.2.1, after update fix fly

Observe the VnyPlay player

https://youtu.be/liVrEfzKDcA

**Comment by LtSam** [comment]
I'm using 4.9.2.1

**Comment by Zrips** [comment]
5bc81cbd560954da626004e79899b79a2e5e24f5

**Comment by LtSam** [comment]
Hi, 

The bug still keeps happening

I'm using the latest version 4.9.2.4

When the player logs out of a home with a fly flag, and enters the server again, he is pulled into the spawn, then he contuned with fly
