### ISSUE TITLE
/res auto <radius>

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#646]
Hi, when we allow players so big residences for ex 400*400, then would be nice if you add radius section after res auto that will respect their max residence size and allow them create less residences than their max limit. So if players has limit 400*400, he would create residence 0<400*0<400.

**Comment by Zrips** [comment]
It should already take into consideration players residence limits and if player provided bigger number then allowed it will be maxed out, at same time if player dint provided radius then it will get as big as possible by default.

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/106639809-a77d6200-6585-11eb-9613-36c859c12558.png)
ANd it's ok when I use /res auto 15, then the 15 is from up to down instead from east to the west and from south to the north?

Shouldn't be 15 also x z coordinates? How can then players define that they wanna smaller residence than their max limit?

**Comment by Zrips** [comment]
Good point here. Added small change to take into consideration provided residence size in case you want smaller one
6d4250316df8fcaa572f0080da3747f1c556b2ff
