### ISSUE TITLE
Movement flag enabled EVEN when in TotalFlagDisabled

### ISSUE THREAD

**Issue by MrRazamataz** [Zrips/Residence#649]
I have movement and container flags disabled, however, when someone creates a res, their res either gets created with movement flags on, or get told they don't have permission to make the res.
They get this message when trying to enter any res made.
https://cdn.discordapp.com/attachments/805003008974913546/805003944630812682/unknown.png

I have movement flags FULLY disabled so this shouldnt be happening
https://cdn.discordapp.com/attachments/805003008974913546/805005854537547806/unknown.png

I also have this https://cdn.discordapp.com/attachments/805003008974913546/805004131331866654/unknown.png

I have made sure players dont have the permission to enable movement flags and they are in the TotalFlagDisabling so how is this even happening?

My config files are here: https://mrrazamataz.ga/archive/mcserver/Residence/

Please get this fixed ASAP as Residence is not useable for me with movement flags not being disabled (I paid for this plugin).

**Comment by Zrips** [comment]
5c3d20236500e274bbc60666af468454fa7c3fb3
