### ISSUE TITLE
fly out of residence

### ISSUE THREAD

**Issue by LtSam** [Zrips/Residence#652]
My players are able to fly when they leave the protections that have the fly flag activated.

Observe the VnyPlay player

https://youtu.be/liVrEfzKDcA

The bug still keeps happening

I'm using the latest version 4.9.2.4

When the player logs out of a home with a fly flag, and enters the server again, he is pulled into the spawn, then he contuned with fly

**Comment by Zrips** [comment]
ee35022a740a8023143c8b472b8fb41cea7413a9
