### ISSUE TITLE
Player cannot kick another player in res with admin flag

### ISSUE THREAD

**Issue by Baterka** [Zrips/Residence#655]
- **PlayerA** owns **ResidenceA**
- **PlayerB** have `admin` flag in **ResidenceA**
- **PlayerC** does not have any permissions set in **ResidenceA**

**PlayerB** is unable to `/res kick` **PlayerC** from this residence. Plugin saying that given player is not in residence.

**Comment by Zrips** [comment]
fe9558d2739b9951804ea674a9a89c61d9971ff9
