### ISSUE TITLE
/res list tab completion is broken?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#660]
Hi, res list isn't showing in tab completion all players, don't know why...
![image](https://user-images.githubusercontent.com/18662086/107586148-b0160e00-6bff-11eb-8af8-6588ada2445a.png)
![image](https://user-images.githubusercontent.com/18662086/107586152-b1473b00-6bff-11eb-9ce9-097393031f18.png)

And btw, they have residences, just /res list isn't tab completing them
![image](https://user-images.githubusercontent.com/18662086/107586226-ccb24600-6bff-11eb-92b2-b9870b3de76a.png)

**Comment by Zrips** [comment]
fdbfc9e5751ce6e21d3acb785a963b57d50b7b43
