### ISSUE TITLE
LWC protections being able to be made inside of residences

### ISSUE THREAD

**Issue by USBCharger** [Zrips/Residence#663]
Hey so there was an issue that was opened and you didn't have the API to be able to solve the issue. https://github.com/Zrips/Residence/issues/402 I got in contact with the LWC developer and they sent me this link to the LWC API https://github.com/pop4959/LWCX/blob/master/src/main/java/com/griefcraft/scripting/event/LWCProtectionRegisterEvent.java
https://imgur.com/a/uzlZySv If you could fix this in residence that'd be amazing :)
~Rocket

**Comment by Zrips** [comment]
9f9ab6cb6d0c5cca5350d0e9bba66024429ac57e
