### ISSUE TITLE
Crash report - /res tp

### ISSUE THREAD

**Issue by QuakyCZ** [Zrips/Residence#665]
Hello,
Our server broke down because of some error in Residence plugin. We're using version 4.9.2.6. Here is the log. I don't know if it is related, but when someone ports to residence, the chunk the player is in, won't load for a long time.
[log](https://pastebin.com/Yrj1Nbg2)

**Comment by Zrips** [comment]
2f3354b85ae76ec5ac32888715fdda29e8eafd55
