### ISSUE TITLE
Hello, there are some bugs in the plug-in

### ISSUE THREAD

**Issue by wangjiacheng-wang** [Zrips/Residence#666]
Hello, author, I found some Bugs when using the Residence plug-in. If the territory does not have Move permission, but some people have Move permission, then when this person TP another person to this territory, the Move permission will be invalid. I hope to fix this bug. Thank you. Im Chinese.
![QQ截图20210219101125](https://user-images.githubusercontent.com/79293344/108447582-1a335080-729b-11eb-92f4-fa8e9e44e27d.png)
![QQ截图20210219101158](https://user-images.githubusercontent.com/79293344/108447609-25867c00-729b-11eb-9cc8-01016914d41f.png)
![QQ截图20210219101236](https://user-images.githubusercontent.com/79293344/108447691-4a7aef00-729b-11eb-8166-f129e458dd83.png)

**Comment by Zrips** [comment]
Cant really help out with so little information. You need to check players move flag access who can move inside residence. Residence itself should have move false flag set, if there isint one then player can move by default. If player has set move true on him then he can bypass main residence flag. Other than this you need to explain how exactly you teleport player to residence as any player without permission to move inside residence gets kicked out automatically. Closing ticket for now.
