### ISSUE TITLE
Slimefun in residence

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#669]
#480 The problem still works. We tried it in the worldguard region and it doesn't work there, so the problem is in the residence. 
![image](https://user-images.githubusercontent.com/29830635/108681410-68409200-74ef-11eb-9c5c-78fa35a0d44e.png)
![image](https://user-images.githubusercontent.com/29830635/108681431-6d9ddc80-74ef-11eb-98c4-3a011fe4b541.png)

https://user-images.githubusercontent.com/29830635/108685053-f4ed4f00-74f3-11eb-8464-129c4f3a2e38.mp4

**Comment by TheDevTec** [comment]
I think this is slimefun bug

**Comment by 100petr** [comment]
slimefun bug when it doesn't do it in the worldguard region? When you think.

**Comment by Zrips** [comment]
Issue with updated SlimeFun API which no longer requires CS-CoreLib plugin which disabled SlimeFun support in general. 
c2b7dc13eb1edc734b07e58282ab03b9604f4c70
