### ISSUE TITLE
"IgnoreY: true" Config don't work

### ISSUE THREAD

**Issue by NATroutter** [Zrips/Residence#67]
"IgnoreY: true" Config is not working
Nothing happens if i turn IgnoreY to true
can some one help please :)

[http://imgur.com/a/hySaC](http://imgur.com/a/hySaC)

**Comment by smmmadden** [comment]
IgnoreY does work for me in Spigot 1.12/BungeeCord Server 1.12 and Residence 4.7.0.0
What evidence do you have that shows it isn't working for you?  Did it ever work, or is this your first time setting up the plugin?  Need a bit more detail please describing "what is not working".

**Comment by NATroutter** [comment]
i just but that plugin on my server and change IgnoreY: false to true and then restart my server and it does not do anything

**Comment by smmmadden** [comment]
You just what?  What are you expecting it to do and how are you verifying it?  All you've stated twice, is that you changed IgnoreY:false to IgnoreY:true but haven't shown what the player is doing or seeing when creating a residence, area or subzone. Provide a screen shot of what happens when the player is doing and seeing in the game.

**Comment by smmmadden** [comment]
This is confirmed with the NoCostForYBlocks:true or false and the IgnoreY:true
I also issued a /res remove mytest and /res confirm
The residence was removed, the the enter/leave messages still show it being there.
![image](https://user-images.githubusercontent.com/10309346/27508646-ca6cbbfa-58b7-11e7-9f30-38b8dc2e25ef.png)
![image](https://user-images.githubusercontent.com/10309346/27508648-d34753e8-58b7-11e7-8ad1-5b909db179a0.png)
![image](https://user-images.githubusercontent.com/10309346/27508653-ddee030a-58b7-11e7-9eb0-9d7d36d5a64e.png)
![image](https://user-images.githubusercontent.com/10309346/27508655-e5ea818c-58b7-11e7-94e8-25f9431f41af.png)

**Comment by Profeer** [comment]
IgnoreY is true, and it does not work, when i claim area it wont ignore height.
When i go above it its not in that region.
 https://vgy.me/sJwjNI.png
and when i go inside it it works
https://vgy.me/Ntr9NP.png
IgnoreY is true but it does not ignore it

**Comment by NATroutter** [comment]
Can someone help pls
i want to use that plugin on my server 
but i can't because that config don't work

**Comment by smmmadden** [comment]
Patience NATroutter - the issue has been confirmed not to work, now we have to give @Zrips time to find out why and then provide a fix.  Contrary to belief, this is not our only job and not everyone works over the weekend either. :-)  There are workarounds to ignore the Y simply by using the **/res select vert** - expand selection from sky to bedrock.  This is on the wiki page, so it shouldn't prevent you from setting it up.

**Comment by Zrips** [comment]
Can't really reproduce issue with IgnoreY: true and NoCostForYBlocks: true/false on 1.12 server
Residence is being created from bedrock to sky. Try out the latest version and if possible any instructions to reproduce this issue would be awesome.

**Comment by smmmadden** [comment]
are  you creating the residence using /res auto or /res create?  It's the latter that I've confirmed with.  I can check the latest build later today and see if it is reproducible or not.

**Comment by Someone-NEW** [comment]
Hi i have question i have the same problem nothing was changed during a couple of updated im just replaced jar file oter stay the same but i see this not so fast now. I realy dont know why my residence IgnoreY not working? i will use Y to be free like before but now not work even this featue is true. ??

[CODE]  Selection:
    # By setting this to true, all selections will be made from bedrock to sky ignoring Y coordinates
    IgnoreY: true
    # By setting this to true, player will only pay for x*z blocks ignoring height
    # This will lower residence price by up to 256 times, so adjust block price BEFORE enabling this
    NoCostForYBlocks: true
  # This determins which tool you can use to see info on residences, default is String.
  # Simply equip this tool and hit a location inside the residence and it will display the info for it.[/CODE]

**Comment by smmmadden** [comment]
perhaps a craftbukkit issue or using it with GP?  I've been using Spigot and now on 1.12.1 with and without BungeeCord Server and don't have any problems with it registering the Y to be free.  All my servers I don't charge for Y (0-255), so selecting the two locations ignores it fine.

**Comment by Someone-NEW** [comment]
smmmadden omg dude. what is say? im not english but read again Im not using GP. But when this cant be fixed i will replace with GP that can be better than so bug with Y still exist better do test on fresh test created server with all you plugins like me and not work.

**Comment by smmmadden** [comment]
glad you figured it out.  BTW, I am not the developer of this plugin - only posted as helping to show that it isn't reproducible using what I have setup and that it is working as designed.  That it may be an issue with CraftBukkit since Spigot did work.  I should have also mentioned permissions but was assuming by your previous post nothing changed and only put in newer version.  So it now sounds like it was not working before upgrading to the newest version and that it was your permissions that was blocking it, not the plugin. :-)

**Comment by Someone-NEW** [comment]
Cool i forgot to check again this permissions i see this problem before i change anything but now i make server from beginning and i solve this all problems step by step ;)

**Comment by AdleyMD** [comment]
I don't understand the solution he's saying. Help ?

**Comment by Someone-NEW** [comment]
For ignorin Y you need add this permission   -residence.bypass.ignorey   without negating ;)

**Comment by AdleyMD** [comment]
Ok thank you
