### ISSUE TITLE
/res contract  Abnormal behavior 

### ISSUE THREAD

**Issue by JinOuYongGu** [Zrips/Residence#670]
I'm using PaperSpigot 1.12.2 and residence 4.9.2.6

When I use the command _/res contract_ and face up or down
the residence is shrinking in the opposite(which is wrong) direction.

For example, when I facing **down** and input: /res contract 10
The residence will contract 10 blocks from the bottom to sky.
I don't think it is a correct contract direction. The right direction should from the sky to the bottom.

In my server, I set **IgnoreY: true** in config.

**Comment by Zrips** [comment]
35a9a6d22d10f3378b05d9590eb00d6de4dbc5f9

**Comment by Vlader97** [comment]
Paper 1.21.1
Residence 5.1.6.5

It's still happening.
When I shrink in the **north** (for example), it tells me that it shrank in the **north**, but it actually shrank in the **south!**
