### ISSUE TITLE
Residences are deleted if world isn't loaded

### ISSUE THREAD

**Issue by bobhenl** [Zrips/Residence#673]
Hi, I have problem. When i'm using playerworldspro plugin https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-the-nether-and-the-end-support-expiration-1-8-1-16-4.72113/updates, and when someone creates residence in the world and I have set:
```
  # All player worlds load on startup.
  Load-On-Startup: false (due to https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/packet/Login.java#L56)
```
then players loosing their residences on server restart.... Do you think that you could somehow fix removing residences from unloaded world if we won't personally remove them? Or some option in config to prevent it at least?

Edit: so I discovered this is enough for fix:
```
    # If false, chunks of the world will not be kept in memory. They are resulting in less memory used by your server when players aren't logged in.
    Keep-Spawn-In-Memory: true
```
But I still think that may there could be made something on residence side too, cause when worlds aren't in memory, they're deleted completely

**Comment by Zrips** [comment]
324353922a8cec0d6542a9c4748ada3dbabe14b0
