### ISSUE TITLE
Drained Water

### ISSUE THREAD

**Issue by MineShark** [Zrips/Residence#678]
Hello, I do not know if it is an error or I have to change something in the configuration so that the water does not remain static (everywhere on the server and I already provided it from another host only the plugin)

**Comment by Zrips** [comment]
make sure that you dont have flow flag set to false in global flag section in flags.yml file. And check config file under AntiGreef section, there is option to block water flow above certain level which allows us to block any water greefing in wilderness while still allowing it to flow in residences
