### ISSUE TITLE
Version match fail

### ISSUE THREAD

**Issue by WyRe** [Zrips/Residence#68]
I think you did something wrong, because I've download `Residence4.7.0.2.jar` from Spigot website, but I still getting an incongruous message about a strange upgrade to `4.0.7.2` version and it says I'm running `4.0.7.1` version (despite of I've installed `4.7.0.2` version)

![captura de pantalla de 2017-06-24 09-10-43](https://user-images.githubusercontent.com/4059108/27506657-5ae7cf94-58bd-11e7-818d-a6bb03f98236.png)

**Comment by Zrips** [comment]
Incorrect plugin version in plugin.yml, just ignore this for time being, you have the newest version but its being recognized as older one.
