### ISSUE TITLE
[REQUEST] Pl3xmap support

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#685]
Wouldn't it be possible to support the display of residences on pl3xmap? https://github.com/pl3xgaming/Pl3xMap/

**Comment by DoctaEnkoda** [comment]
+1

**Comment by DoctaEnkoda** [comment]
https://github.com/systeme-cardinal/Pl3xMap-Residence/tree/dev/1.0

**Comment by 100petr** [comment]
Thanks! I'll try it tomorrow.
