### ISSUE TITLE
move false piston

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#689]
You can go to the residence with move to false using a piston.  
Video: https://youtu.be/wck3zySjjbo
This server is running Paper version git-Paper-553 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version. Residence version 4.9.3.2

**Comment by Zrips** [comment]
6e6a8fddf61f0c85d402f9bbcbaf97db3b06e0b6
