### ISSUE TITLE
Console Spam on Teleporting into a Residence

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#691]
Getting some console spam when players teleport into a Residence. Doesn't seem to affect server-owned residences, but I haven't pinpointed any specific conditions yet (will edit this if I'm able to find out more). Doesn't seem to be affecting anything in game, or at least nothing we've noticed yet.

Error: https://gist.github.com/mercurialmusic/521525162200b51eef4316461db3e799
Residence 4.9.3.3 on git-Paper-553 (MC: 1.16.5)

**Comment by 100petr** [comment]
Same issue git-Purpur-1022 (MC: 1.16.5)

**Comment by Zrips** [comment]
Fixed in v4.9.3.4
