### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by krfcm** [Zrips/Residence#694]
Hey, i try to use placeholders but they doesn't work.
I can't find that i I have to enable it or do somethink?
I have instaled Residence(4.9.2.11) and PlaceHolderAPI (2.10.9)

**Comment by Zrips** [comment]
You simply need Residence and PAPI and then you can test placeholders with something like **/papi parse Zrips %residence_user_amount%** which should return amount of residences provided player owns.
