### ISSUE TITLE
Res auto

### ISSUE THREAD

**Issue by LtSam** [Zrips/Residence#695]
return the res auto as it was before,

when protecting near another residence, it would automatically expand to the opposite side ...

It is happening to collide with other residences ..

**Comment by LtSam** [comment]
@Zrips 

And then, as it turned out
may have an option to disable the new function of the auto res?

**Comment by Zrips** [comment]
Its actually a bug. Will try to issue a fix for it to make it work as before.

**Comment by Zrips** [comment]
0163ee0d850ba2aecf66638f886fd3728877fdfe
