### ISSUE TITLE
Name contained unallowed characters

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Residence#7]
If a user types in: **/res subzone Spawn.BogotaSteves**, an error appears in the chat window stating "**Name contained unallowed characters**".  "Spawn" is a valid Residence and a residence I'm standing in.  Subzone creation should allow both residence qualified or unqualified prefixed when inside the residence.

Spigot 1.11.2 latest build
Residence 4.5.13.4

**Comment by Zrips** [comment]
You need to use space when providing target residence, in this example it would be **/res subzone Spawn BogotaSteves** because dot is not allowed in residence/subzone name as dot is used to separate subzones
