### ISSUE TITLE
Res auto problem

### ISSUE THREAD

**Issue by naikyy** [Zrips/Residence#700]
Hello, in the newest version you can't create /res auto with your highest limits, it is creating just 100x100 instead of 250x250 as someone have.

**Comment by naikyy** [comment]
Thanks for answer...

**Comment by Zrips** [comment]
As it was indicated in update notes, res auto is limited to 50% and/or 100 as a max value. This can be changed inside config file to your own desired values.

**Comment by LtSam** [comment]
Esta opção do res auto era confusa

Eu tenho um grupo de 100 x 100

Mesmo colocando Mín e Máx de 80 e 100 na configuração respectivamente, ao criar uma residência diz que está fora dos limites, e não estou conseguindo configurar corretamente, qualquer valor que coloquei que esteja fora dos limites, poderia ter algum tipo de tutorial para configurar esta parte. e, se possível, rápido.
