### ISSUE TITLE
res listall world

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#703]
If you write /res listall world_the_end then click on the next 
![image](https://user-images.githubusercontent.com/29830635/112802220-384a5880-9072-11eb-899a-0fc0937b3437.png)
All residences will be displayed, not only in the world that I want
![image](https://user-images.githubusercontent.com/29830635/112802482-87908900-9072-11eb-8e74-6efff6f089ad.png)
![image](https://user-images.githubusercontent.com/29830635/112802755-da6a4080-9072-11eb-9871-3a4b1839a70b.png)

**Comment by Zrips** [comment]
a1c03329a3f9cb30bf8d7fbd29c25ab81f935839
