### ISSUE TITLE
Raids not working as intended

### ISSUE THREAD

**Issue by EkonC** [Zrips/Residence#706]
Hello, I've been trying out the Residence raid system, but it doesn't quite work.

When a player uses /res attack (resName), it starts the pre-raid cooldown and then the raid itself - this works.

When other player uses /res attack (resName) again - to join the raid - it says "Residence owner is immune to raids! Wait (time)". So basically other players can't join the raids as attackers.

When someone who wants to defend uses /res defend (resName), it says "Invalid residence..." even though the residence name is 100% correct. I even tried using /res defend (resName) (owner) and then it says "Usage: /res defend [resName] (playerName]". The only command that worked was /res defend when the player was in the residence that was about to be raided, but when the player who was attacked clicked the "Accept raid defend from (player)" request, it wrote "Can't join this rais, you are in another one already (resName)", so basically the player couldn't join the defense.

I would be really happy if you could fix this :)

**Comment by Zrips** [comment]
88cf8c53333517fc67ed3051a7611fbeec092e15
