### ISSUE TITLE
[BUG] Fly everywhere

### ISSUE THREAD

**Issue by samukatb** [Zrips/Residence#709]
Watch this video to better understand: https://youtu.be/MeKXhXRGtTw

The residence where the player is in the beggining of the video has fly enabled.
The res he try to enter, has fly, but has move flag = deny
So the player gets teleported to another area where there is not res and if he type /spawn /home etc... he can fly everywhere

Residence Version: 4.9.3.3
Paper 1.16.5

**Comment by Zrips** [comment]
8008d2c62d961cac86ff1fe734432ef632563651
