### ISSUE TITLE
/res auto 

### ISSUE THREAD

**Issue by dejwiix** [Zrips/Residence#715]
Hello in groups yml i hawe graoup owner residence 500x500 and command /res auto create residence 150X150 in my support hosting write me it's because of the lag plase contactme on discord dejwiix#8017

**Comment by Zrips** [comment]
Well who said that its due to lag, they are partially correct. Due to huge amount of checks we need to perform when creating residence like this by default we are limiting its size. You can change this limit in your config file under AutomaticResidenceCreation section.
