### ISSUE TITLE
Res auto

### ISSUE THREAD

**Issue by LtSam** [Zrips/Residence#716]
@Zrips 

This option of the res auto was confusing

I have a group of 100 x 100

Even putting Min and Max of 80 and 100 in the configuration respectively, when creating a residence it says that it is outside the limits, and I am not able to configure correctly, any value that I put that is outside the limits, could have some kind of tutorial configure this part. and if possible, fast.

**Comment by LtSam** [comment]
@Zrips

Help me,
I can't update to the latest version because the res auto doesn't work..

**Comment by XC012** [comment]
use 4.9.3.4 not lastest, can confirm this issue

**Comment by Teleriann** [comment]
Yes, same problem

**Comment by Zrips** [comment]
7e201f517716563b2d40dedd752f19d461d960b5
