### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by LivingDarkness** [Zrips/Residence#719]
put that the messages to go forward or backward in the flag gui are translatable differently, that is, put that these messages can be set in a different way and not as in the photo.
![Screenshot_10](https://user-images.githubusercontent.com/83078827/116887724-e5446200-ac2a-11eb-9f80-1a3913b0a878.png)

**Comment by Zrips** [comment]
1d65f60136d39bafa767f71a4454ef9e587ea681
