### ISSUE TITLE
Disable building outside of a residence

### ISSUE THREAD

**Issue by DSnow64** [Zrips/Residence#720]
Hello,
I would like players to be able to build ONLY in residences where they are allowed to. Not even in any part of a world where there's no residence present, something like plots. I would like to create a system where players can choose any part of a world as their plot using just /res auto, but not build anywhere else.
Maybe it could be added under antigreef section in config.yml
Hope you will see it as a good idea and add it.

**Comment by Zrips** [comment]
This can be enabled by simply setting global build flag to false, in this case players will not be able to build in wilderness but only in their residence. Check flags.yml file
