### ISSUE TITLE
Residence v4.9.3.6 Fails to Load

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#723]
This is probably more to do with my ancient setup rather than a Residence bug, but would appreciate some assistance in nailing down the problem all the same.

Getting these errors on startup, which puts me into a shutdown loop:
https://gist.github.com/mercurialmusic/5c269ecaf467618b5b42a4b9f2ca43d6

I do have the cleanup enabled (always have) so my guess is something in there? No errors when going back to 4.9.3.5. 

Running git-Paper-742 and currently still on Java 11 if that matters.

Thanks!

**Comment by mercurialmusic** [comment]
Different error now on 4.9.3.7, still won't load. 
https://gist.github.com/mercurialmusic/71219a919d17f38b588a6202b2940c84

**Comment by ZappySK** [comment]
I have the same error @mercurialmusic, the plugin won't load and the server can't start.. @Zrips

**Comment by Zrips** [comment]
82007de8cfc179524efa7f49fde1e4e94734c9e7
