### ISSUE TITLE
Res Auto || Issue isn't gone yet.

### ISSUE THREAD

**Issue by klaidoshka** [Zrips/Residence#728]
Hello.

I have encountered a problem with `/res auto` command, regarding the size of residence being too big than the set limit.
The configs are done fine, the problem shouldn't be somewhere between configurations.

**Before writing the issue I searched if people had encountered it too, and seems they did:**
https://github.com/Zrips/Residence/issues/721 , https://github.com/Zrips/Residence/issues/716
However the fix https://github.com/Zrips/Residence/commit/7e201f517716563b2d40dedd752f19d461d960b5 didn't work, it is still happening in the latest version.

**Minimal photo of the issue:**
https://i.imgur.com/cyGSGde.png

**Used commands:**
```
/res limits
/res auto
/res auto meow 3
```

**Res version:** 4.9.3.10

**Comment by Gumpah** [comment]
I have the same problem.

**Comment by Zrips** [comment]
Lets hope this is the fix which fixes it once and for all
9ccc8f2208642703809a0a535d75de4c4bf607b6
