### ISSUE TITLE
Not working on Spigot 1.17

### ISSUE THREAD

**Issue by RanWhite** [Zrips/Residence#732]
Error on the console

**Comment by Baterka** [comment]
@Zrips needs to make an update or at least make project a Maven project (or provide missing dependencies as jars) so we can help him out.

**Comment by Zrips** [comment]
New version should be coming out today with some initial support for new things introduced in 1.17. Any suggestions for new behaviors are welcomed.

**Comment by Zrips** [comment]
@Baterka 
And yea, I need to make it maven compatible at some point... Its some what complex when it uses quite few different dependencies.
