### ISSUE TITLE
Residence 4.9.3.10 is crashing my server.

### ISSUE THREAD

**Issue by flurbudurbur** [Zrips/Residence#734]
I've temporarily had to remove Residence from my server because it's the cause of my server crashing when attempting to start up.
this is the error:
https://mcpaste.io/6f5207e1e98987e9

Using Paper 775 and Java 16 and Minecraft 1.16.5

It's unclear what more information is needed/would be useful, please reach out if necessary.

Thank you.

**Comment by XC012** [comment]
same problem

**Comment by Zrips** [comment]
Did residence properly created save files for existing residences? As of error log it looks more like its failing to load saved files for one or another reason. If you could provide save files from Save\Worlds folder for testing would be appreciated.

**Comment by flurbudurbur** [comment]
of course, here's the `worlds` folder:
https://mega.nz/file/9w1inJpY#8ckRmAW-2cprguv0wC2LGCQ8-qZ9BpH2V0Hi4uiVu_8

Hope it helps!

**Comment by Zrips** [comment]
Thanks, helped out. You seem to have invalid save files, simplest solution would be to delete those files and let it regenerate with correct information in them. But will add some fix to prevent this issue from appearing in future for others. 
12ea949ad00813ee8c9592cccac4660ac57dee78
