### ISSUE TITLE
Error while loading plugin on 1.17

### ISSUE THREAD

**Issue by CloneXmmT** [Zrips/Residence#740]
![image](https://user-images.githubusercontent.com/66385420/122647966-36e77400-d127-11eb-9b66-6262f636b7d7.png)

**Comment by yoder303** [comment]
Do you have the required extra library file for Res5?

**Comment by CloneXmmT** [comment]
Yes

**Comment by yoder303** [comment]
Missing CMI was the only issue I had when upgrading to 5, but I don't have plugman.

**Comment by CloneXmmT** [comment]
I will try restart server

**Comment by CloneXmmT** [comment]
Oh, its works ![image](https://user-images.githubusercontent.com/66385420/122648478-c3933180-d129-11eb-9763-ed5ada70fcf1.png)
