### ISSUE TITLE
Impropper Y Level set in 1.17 (Only goes to y = 0 and y = 255 | should allow y < 0 with 1.17)

### ISSUE THREAD

**Issue by xNitrate** [Zrips/Residence#754]
It only goes down to y = 0. Where in 1.17, you can go basically any y depth or height. I have this on my 1.17 server and player's bases at y = -23 (anything below y = 0) are able to be accessed by others. PLEASE fix this. Thanks!

**Comment by Zrips** [comment]
Officially 1.17 doesn't support extra height, so it is set properly to 0 as minimum height. That said, will make some changes to start supporting more dynamic map heights. 
1488450f13547ac6c851da6bab5dc7e4eda8c8f8
