### ISSUE TITLE
Residence owner name is changed to lowercase [BUG]

### ISSUE THREAD

**Issue by Pirito10** [Zrips/Residence#755]
It seems that randomly, the owner name of some residences is changed to lowercase. This causes that the real owner no longer has permission to do things to that residence.

For example, someone named "Player" has a residence. Then, the residence owner changes to "player", and "Player" no longer has permissions.

**Residence version:** 5.0.0.0
**CMILib version:** 1.0.2.9
**Server version:** Purpur 1.17 build 1255

**Comment by Tumilai** [comment]
So I didn't notice the nickname change, but I have the same problem.
Sometimes there is a player who cannot set flags after creating a residence.
It is from version 5.0.0.0

**Comment by Zrips** [comment]
In general you should switch to UUID format and avoid issues like this, but will make some adjustments to recognize owner even if its in lower case

**Comment by Zrips** [comment]
7c01da13ae21757285d55a416374ce1089f92694
