### ISSUE TITLE
Selete crash problem

### ISSUE THREAD

**Issue by plumegod** [Zrips/Residence#76]
Using Baidu translation
本文使用 百度 翻译 (fanyi.baidu.com)
When choosing a territory, you can move the territorial constituency to infinity (even beyond the map boundaries) using the /res select shift command, and then create a territory that can cause the server to crash instantly.
选择领地区域时，利用/res select shift指令，可将领地选区移动到无限远的地方（甚至超越地图边界），然后创建领地，严重可导致服务器瞬间崩溃。

When using instructions (/res selete shift),the size of the selection can become infinite,residence will crash the server

**Comment by Zrips** [comment]
a0eecb5deeeeb06021583fbacb6033eaa0787a8d
