### ISSUE TITLE
Pl3xmap support

### ISSUE THREAD

**Issue by ElFrod0** [Zrips/Residence#761]
Hello,
will you add support for Pl3xmap plugin in the future? It is great alternative for Dynmap plugin.

Link for plugin here: https://github.com/pl3xgaming/Pl3xMap

Thanks in advance for your answer.
Cheers,
Michal

**Comment by 100petr** [comment]
#685

**Comment by FuryMeDEV** [comment]
If you have it, please send it to me. I would be insanely happy and my player base as well.

**Comment by Zrips** [comment]
7ceef87e90215cd74e3d453af90206e35ae23d8f
