### ISSUE TITLE
Provide pom.xml pls and support for 1.17.1 new world height

### ISSUE THREAD

**Issue by MossCG** [Zrips/Residence#766]
some suggestions:
1.provide pom.xml pls, so that we can build or make some pull request include bug fixes for this plugin(because i want to change the height limit for support 1.17.1 384block height with datapack,but found so many libraries i should download :< )
2.support 1.17 384 blocks height pls

**Comment by Zrips** [comment]
pom.xml support is some what complicated due to some jar file usages, will try to simplify it
For world height, can you be more specific which place exactly still isint supporting extended heights?

**Comment by Zrips** [comment]
WIP
