### ISSUE TITLE
residence will not be saved

### ISSUE THREAD

**Issue by CrazyJky** [Zrips/Residence#771]
My server is based on uranium core (1.7.10), it has been working fine until now, but every time I restart the server recently, the player's residence will be reloaded, I found the last save was on July 26, I don't know why he won't save, I have tried to adjust the relevant options in the config, but it doesn't work, I need help, My plugin version is 4.7.8.2

**Comment by Zrips** [comment]
Saving is done automatically and there isint any actual option to prevent that. Single thing which effects saving is SaveInterval in config file, but even then on normal server stop residences should be saved.
Without any information or error logs i cant help out here. It could be issue with your internal file system not allowing file modifications or something else.
