### ISSUE TITLE
Residence on bungee

### ISSUE THREAD

**Issue by TheDoctrWho** [Zrips/Residence#778]
Hi, I have a request for functionality on bungee servers, I want to be able to set global limits of how many residences could one person have on bungee server across multiple servers i.e. I have 4 servers on bungee and if user can have 10 residences he could create 10across these servers and not 10 on every server.

**Comment by Zrips** [comment]
This is not likely to happen any time soon do to its complex nature.

**Comment by HaiXi2912** [comment]
Hope to be compatible with Bunge as soon as possible
