### ISSUE TITLE
Selection height too big

### ISSUE THREAD

**Issue by Adventure2098** [Zrips/Residence#78]
I recently added the residence plugin to my server. The first config option I like to change is ignoreY to true.  That works initially, but after creating one residence, it starts to tell me that the max height is 20 or less, even though I checked the config and it's 256. I am using spigot 1.8.8 and residence 4.7.0.2

**Comment by Zrips** [comment]
Selection size depends on your group. Check your /res limits. To bypass this limitation use /resadmin.
