### ISSUE TITLE
I need support on discord 

### ISSUE THREAD

**Issue by eRko1337** [Zrips/Residence#797]
I am running 1.17.1, and i cant figure out how to give different users, different groups using my LuckPerms. I want my VIPs to have 10 residence limit and default 2 for example. But it doesnt work

My discord: eRko16#4074

I bought the plugin, so please help me.

**Comment by Zrips** [comment]
You have groups.yml file where groups name should match what is provided by your luck perms permission plugin, alternatively you can give players permission node as residence.group.[groupName] where replace [groupName] with provided name in groups.yml. Alternatively, you can simply use residence.max.res.[amount] like residence.max.res.10

**Comment by eRko1337** [comment]
Yeah but that doesnt work for me for some reason.

This is my /res limits https://imgur.com/a/bg6kzL4
I am in group Immortal, and group Immortal has these perms https://imgur.com/a/YwjgQkT , 
![image](https://user-images.githubusercontent.com/75496278/138151044-e3ed9042-6e6b-4da4-88b8-ff00c3a371ed.png)

**Comment by eRko1337** [comment]
# These groups correspond to the Permissions groups defined in your '<worldname>.yml'
Groups:
    Default:
       #Mirror:
         #- 'group1'
         #- 'group2'
       Residence:
           CanCreate: true
           MaxResidences: 2
           MaxAreasPerResidence: 2
           MaxEastWest: 100
           MinEastWest: 3
           MaxNorthSouth: 100
           MinNorthSouth: 3
           MaxUpDown: 256
           MinUpDown: 3
           MinHeight: 0
           MaxHeight: 255
           MaxSubzonesInArea: 3
           SubzoneDepth: 3
           SubzoneMaxEastWest: 16
           SubzoneMinEastWest: 3
           SubzoneMaxNorthSouth: 16
           SubzoneMinNorthSouth: 3
           SubzoneMaxUpDown: 256
           SubzoneMinUpDown: 3
           CanTeleport: true
           Unstuck: true
           Kick: False
           SelectCommandAccess: true
           ItemListAccess: true
       Messaging:
           CanChange: true
           DefaultEnter: Residence: %residence, Majitel: %owner.
           DefaultLeave: Odešel jsi z %residence.
       Lease:
          MaxDays: 16
          RenewIncrement: 14
       Rent:
           MaxRents: 2
           MaxRentables: 2
           MaxRentDays: 31
       Economy:
          CanBuy: true
          CanSell: false
          IgnoreLimits: false
          BuyCost: 0.0
          SellCost: 0.0
          RenewCost: 0.0
       Flags:
          Permission:
               #build: true
          Default:
              #build:
          CreatorDefault:
              #build: true
          GroupDefault:
               #default:
                   #build: false
          World:
                Global:
                     #build: false
                WorldNameHere:
                     #build: false
    Premium:
       Residence:
           CanCreate: true
           MaxResidences: 5
           MaxAreasPerResidence: 2
           MaxEastWest: 150
           MaxNorthSouth: 150
           MaxUpDown: 20
           MinHeight: 0
           MaxHeight: 255
           SubzoneDepth: 5
           CanTeleport: true
           Unstuck: true
           Kick: true
           SelectCommandAccess: true
           ItemListAccess: true
       Messaging:
           CanChange: true
           DefaultEnter: Residence: %residence, Majitel: %owner.
           DefaultLeave: Odešel jsi z %residence.
       Lease:
          MaxDays: 16
          RenewIncrement: 14
       Rent:
           MaxRents: 5
           MaxRentables: 5
           MaxRentDays: 31
       Economy:
          CanBuy: true
          CanSell: false
          IgnoreLimits: false
          BuyCost: 0.0
          SellCost: 0.0
          RenewCost: 0.0
    PremiumPlus:
       Residence:
           CanCreate: true
           MaxResidences: 8
           MaxAreasPerResidence: 2
           MaxEastWest: 200
           MaxNorthSouth: 200
           MaxUpDown: 20
           MinHeight: 0
           MaxHeight: 255
           SubzoneDepth: 8
           CanTeleport: true
           Unstuck: true
           Kick: true
           SelectCommandAccess: true
           ItemListAccess: true
       Messaging:
           CanChange: true
           DefaultEnter: Residence: %residence, Majitel: %owner.
           DefaultLeave: Odešel jsi z %residence.
       Lease:
          MaxDays: 16
          RenewIncrement: 14
       Rent:
           MaxRents: 8
           MaxRentables: 8
           MaxRentDays: 31
       Economy:
          CanBuy: true
          CanSell: false
          IgnoreLimits: false
          BuyCost: 0.0
          SellCost: 0.0
          RenewCost: 0.0
    Mystic:
       Residence:
           CanCreate: true
           MaxResidences: 8
           MaxAreasPerResidence: 2
           MaxEastWest: 300
           MaxNorthSouth: 300
           MaxUpDown: 20
           MinHeight: 0
           MaxHeight: 255
           SubzoneDepth: 8
           CanTeleport: true
           Unstuck: true
           Kick: true
           SelectCommandAccess: true
           ItemListAccess: true
       Messaging:
           CanChange: true
           DefaultEnter: Residence: %residence, Majitel: %owner.
           DefaultLeave: Odešel jsi z %residence.
       Lease:
          MaxDays: 16
          RenewIncrement: 14
       Rent:
           MaxRents: 8
           MaxRentables: 8
           MaxRentDays: 31
       Economy:
          CanBuy: true
          CanSell: false
          IgnoreLimits: false
          BuyCost: 0.0
          SellCost: 0.0
          RenewCost: 0.0   
    Immortal:
       Residence:
           CanCreate: true
           MaxResidences: 10
           MaxAreasPerResidence: 2
           MaxEastWest: 400
           MaxNorthSouth: 400
           MaxUpDown: 20
           MinHeight: 0
           MaxHeight: 255
           SubzoneDepth: 10
           CanTeleport: true
           Unstuck: true
           Kick: true
           SelectCommandAccess: true
           ItemListAccess: true
       Messaging:
           CanChange: true
           DefaultEnter: Residence: %residence, Majitel: %owner.
           DefaultLeave: Odešel jsi z %residence.
       Lease:
          MaxDays: 16
          RenewIncrement: 14
       Rent:
           MaxRents: 10
           MaxRentables: 10
           MaxRentDays: 31
       Economy:
          CanBuy: true
          CanSell: false
          IgnoreLimits: false
          BuyCost: 0.0
          SellCost: 0.0
          RenewCost: 0.0           
GroupAssignments:
     bekvon: default
     player: default

**Comment by eRko1337** [comment]
I feel like when i do /res reload groups it does nothing

**Comment by eRko1337** [comment]
Allright, i pass the format check https://pastebin.com/rtTgpzwf
My groups are setup correctly in LuckPerms: 
![image](https://user-images.githubusercontent.com/75496278/138157208-1f3174d5-4c01-45be-aaaf-4dfd2987d219.png)

This is ingame: 
![image](https://user-images.githubusercontent.com/75496278/138157270-5d94cf78-ddc0-4dd4-b3b6-45274a0bbe30.png)

**Comment by eRko1337** [comment]
Okay i created new groups.yml. But your /res reload groups doesnt work.

**Comment by Zrips** [comment]
Is it recognized after normal server restart?
