### ISSUE TITLE
slimefun ancient altar

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#804]
Hi, my players can't use ancient altar in someone else's residence (I tried to enable container, use) from slimefun. It tells them that "You can't use this here". The player tries to fix the spawner. res 5.0.0.4, but the problem has been going on for some time

https://user-images.githubusercontent.com/29830635/138583771-0adb6b53-b028-45f0-b18e-136791e1e8a2.mp4

When I deleted the residence plugin, everything worked

**Comment by 100petr** [comment]
https://github.com/Zrips/Residence/issues/859#issuecomment-1033612023

**Comment by Zrips** [comment]
As of test, issue originates from having MOB_SPAWNER set as blacklisted item in flags.yml file. Will adjust default flags.yml file to avoid issues like that in future.
