### ISSUE TITLE
Residence owner nick still randomly changes to lowercase letters

### ISSUE THREAD

**Issue by empp4** [Zrips/Residence#808]
- **Plugin version:** 5.0.0.4
- **CMILib version:** 1.0.4.1
- **Server version:** Purpur 1.17.1

I've been issuing an occurance, in which the residence owner nick randomly changes to lowercase letters. (Issue described furthermore in #755 ) As far as I can tell, the 7c01da1 commit didn't fix anything and I've been dealing with this issue just as before.

**Comment by Zrips** [comment]
Dont know if this will resolve your issue fully but made some extra adjustments to utilize UUID more properly while creating new residences 
725e93d0e6afe86d38315f83c82a8578a22841ee
