### ISSUE TITLE
Pistons abusing @QuiteNeedsAFix

### ISSUE THREAD

**Issue by klaidosHka** [Zrips/Residence#812]
Hello.

Could it be possible to somehow check for pistons-pushed blocks into the residence and block it? Probably similar to portals, which made some errors for this https://github.com/Zrips/Residence/issues/807 guy (not for me yet, but maybe could happen too 😅)

Also, maybe add flag to toggle such pistons checking, just to remove some possible casualties in the future if used between two residences by their owner or if the residence owner wants to enable it. Well, no clue, **it is** up to you.

**What's happening right now**
You are able to push blocks into anyone's residence with pistons, easy griefing...

And maybe https://github.com/Zrips/Residence/issues/689 is not fixed yet, someone writed it, I found it somewhat needed to fix too 😉

**Comment by Zrips** [comment]
Block movement into residence is checked and blocked by default, so you should not be able to move blocks from outside into residence.
Other 2 tickets got closed as those got a fix.
If you can still move blocks into residence, would suggest testing this with default config files to make sure its not related to your custom settings, if issue persists with defaults then we can look into it, but we need to know that its actually an issue and as of some testing it doesn't seam to be at this moment, but who knows.

**Comment by klaidosHka** [comment]
Yep, sorry for wasting your time to check this out. Seems was a problem on my end, not sure how the hell I didn't even see it. All along there existed flag such as `pistonprotection`, for some reason I didn't see it in tab-completing before `(literally was looking for such option, with words that associate with piston/redstone/... before writing a ticket)`. Looking at default configurations I can see that the flag in my setup was removed from default residences' flags, which lead into this ticket. Now everything works as intended. Sorry once again, thank you for scheduled updates. 👍
