### ISSUE TITLE
Flag "tp" not working correctly

### ISSUE THREAD

**Issue by sakulmore** [Zrips/Residence#814]
Hello, i have set in file "/plugins/Residence/flags.yml" in part "ResidenceDefault:" flag "tp: false". So in cmd "/res(admin) set" must be automatically on false. But doesn't. Is still on true (in game).

**Comment by Zrips** [comment]
Make sure that its set to false and perform full server restart in case it dint took appropriate effect on file modification while server was running. As of testing it looks to be working correctly
