### ISSUE TITLE
Residence height limit capped at 256 blocks | 1.18

### ISSUE THREAD

**Issue by MaHl111** [Zrips/Residence#817]
![obrázok](https://user-images.githubusercontent.com/48538049/144706198-e9d6c689-1a59-42f0-946a-254a1a786374.png)

As show on picture, any value that's bigger than 256 writes an error for selection height being too big. Even if I just try to use values above 256. Section of config is part of default residence group.

Server: **Paper-1.18-R0.1-SNAPSHOT (Build 32)**
Residence: **5.0.0.4**
CMILib: **1.1.0.0**

![obrázok](https://user-images.githubusercontent.com/48538049/144706923-5957a0e3-db8a-42de-802e-ced73203f1e2.png)
![obrázok](https://user-images.githubusercontent.com/48538049/144706930-c0f9d805-b674-4357-91c6-783e97c14ff9.png)
_Let me know what additional info you need, if any_

**Comment by Zrips** [comment]
0243039a115a7779bd0be85f11170333743dd0e9

**Comment by herfavesenpai** [comment]
This isn't working still when MinHeight is set to -64, which is the new lowest elevation.

![image](https://user-images.githubusercontent.com/10445573/146658866-a2088de7-ad18-4cbe-bd6f-a1b9f252c60f.png)

**Comment by tianji1993** [comment]
@Zrips same problem here, can you please check this? many thanks!
