### ISSUE TITLE
bug Broken area removal message

### ISSUE THREAD

**Issue by Bartek200219** [Zrips/Residence#821]
**Describe the bug**
When deleting area message look like this "Removed area %1..."
**To Reproduce**
1. Create residence
2. Create area
3. Delete area

**Expected behavior**
Message should look like "Removed area NameOfArea..."
**Screenshots**
![image](https://user-images.githubusercontent.com/37016424/145717283-52282ffc-c41c-496e-af7f-9c4050a9550f.png)

**Environment (Issues without enough info will be closed!):**
 - Java version: jdk-17.0.1
 - Minecraft Version 1.18
 - Spigot/paper build:  paper-22
 - Vault: 1.7.1-131
 - Residence: 5.0.1.0

**Additional context**
Language config is default but here is the line
`    Remove: '&eRemoved area &6%1...'
`

**Comment by Zrips** [comment]
bd94df9cd648ec252eed4421c5ecb64e44606a2b
