### ISSUE TITLE
Heights not work properly

### ISSUE THREAD

**Issue by Baterka** [Zrips/Residence#826]
On 1.18 and Residence 5.0.1.0 I have this in groups:
```
           # The maximum number of blocks a Residence can be, High to Low (Y).
           MaxUpDown: 384
           # (Optional) The minimum number of blocks a Residence can be, High to Low (Y).
           MinUpDown: 3
           # The lowest altitude this group is allowed to protect.
           MinHeight: -64
           # The highest altitude this group is allowed to protect.
           MaxHeight: 384
```

But still, `/res limits` telling me that:
- UpDown = -64-320 _(incorrect)_
- Height = -64 to 384 _(correct)_

**Comment by Zrips** [comment]
It defaults to worlds max height, in this case its from -64 to 320 by Y axis which adds up to total of 384 blocks of height.

**Comment by Baterka** [comment]
Yes I found out how to fix this for residences itself, but subzones are broken...
