### ISSUE TITLE
/res padd not working

### ISSUE THREAD

**Issue by HrajMen** [Zrips/Residence#828]
the / res padd command does not work in the residence plugin
Every time I do this it shows me this ![Snímek obrazovky 2021-12-20 150351](https://user-images.githubusercontent.com/66079078/146779385-377e4482-86c0-4610-9b03-4e74a238b65a.png)
but when I try to build / destroy something in another account it doesn't work
can you help me please

**Comment by Bartek200219** [comment]
Have you tried `/res pset <otherAccountName> trusted true`?

**Comment by Zrips** [comment]
@HrajMen 
You will need to check players access to specific residence and/or residence subzone/area. This message appears when you have successfully added main flags for player to be added to residence and gives access to main functions. If you still cant perform appropriate actions then there might be issue somewhere else.
