### ISSUE TITLE
flags not working?

### ISSUE THREAD

**Issue by NotProniss** [Zrips/Residence#831]
the flags don't seem to be working, I got a player to claim a res, they set build and doors to false, when i deop myself and make me the default permission group I can both open doors and place blocks in the res.  There are no console messages.

I have not edited the flags.yml and the default group only has these permissions:

residence.buy true
residence.chatcolor false
residence.compass true
residence.contract true
residence.create true
residence.delete true
residence.expand true
residence.max.rents.0 true
residence.max.res.1 true
residence.max.subzonedepth.0 true
residence.max.subzones.0 true
residence.rename true
residence.resize true
residence.select true
residence.sell true

not sure what to do here any help would be appreciated :)

**Comment by Zrips** [comment]
I would recommend to test it with actually regular player as you might inherit bypass permissions from another permission group.
