### ISSUE TITLE
Comments in flags.yml are duplicated when server restarts

### ISSUE THREAD

**Issue by emkirsh** [Zrips/Residence#833]
Hi! I'm experiencing an issue on Residence 5.0.1.0 with CMILib 1.1.0.4:
each time the plugin loads (so each time i restart the plugin) the comments in flags.yml are regenerated on top of what's already there. [This is what my flags.yml now looks like.](https://gist.github.com/emkirsh/3865757ca3d7ff38237c1bb4d67df095)
Not only is it extremely annoying but it also wastes disk space. 

If you would please consider patching this in the next update (and migrating values to a new flags.yml with only one comment per entry would be appreciated but not as important as keeping it from recurring).

Thanks in advance!

P.S. this only seems to be an issue with flags.yml.

**Comment by Zrips** [comment]
Fixed with latest CMILib. This was issue with Spigot updating how yaml files are handled and introduced bug which caused this to happen. Effected only 1.18.1 servers.
