### ISSUE TITLE
Players can smash turtle eggs at any residence

### ISSUE THREAD

**Issue by stefankielbasa** [Zrips/Residence#837]
I have flag:
Destroy: false

but players can still break turtle eggs

**Comment by Zrips** [comment]
If residence contains destroy: false flag then player should not be able to destroy eggs. If player cant destroy any other block then he should not be able to destroy turtle eggs ether as those get protected by same mechanic

**Comment by stefankielbasa** [comment]
https://youtu.be/kksN6w-Zp0o

I have "destroy: false" set on my residence and my friend the same. He can't break sand, which is good, but when he jumps over the eggs, he destroys them

**Comment by Zrips** [comment]
ba20612f1e00a45f7c33a97043d7a67b5af8bc28
