### ISSUE TITLE
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(org.bukkit.Server, java.lang.String, java.util.function.Function)

### ISSUE THREAD

**Issue by DexterSK** [Zrips/Residence#841]
[00:52:33 WARN]: [Residence] Task #2405 for Residence v5.0.1.1 generated an exception
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(org.bukkit.Server, java.lang.String, java.util.function.Function)'
        at com.bekvon.bukkit.residence.slimeFun.SlimefunManager.lambda$0(SlimefunManager.java:23) ~[Residence5.0.1.1.jar

**Comment by misuda12** [comment]
https://github.com/Zrips/Residence/commit/177366d487f47c10a0ed131a3c4f56c557dbb6d1
It has already been resolved. Just wait for final release

**Comment by misuda12** [comment]
Duplicate of #845

**Comment by 100petr** [comment]
this is 17 days old, 845 16 days. so the duplicate is 845

**Comment by Zrips** [comment]
177366d487f47c10a0ed131a3c4f56c557dbb6d1
