### ISSUE TITLE
[Bug] Dispensers not working with lava or water buckets

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/Residence#842]
Dispensers are now bugged within residences after the recent 5.0.1.1 update.

Steps to reproduce:

- Create a residence
- Place down a Dispenser and fill it with a water or lava bucket
- Activate the dispenser
- Poof nothing comes out (Should be flowing lava or water)

**Comment by John-Eye** [comment]
I have 5.0.1.1 installed and am also having this same problem with dispensers and buckets of lava or water.

**Comment by WolverStones** [comment]
@Zrips

**Comment by Zrips** [comment]
1896066c3961f46fee9fa277de7507eb217bfcc8
