### ISSUE TITLE
Create new residence show height error

### ISSUE THREAD

**Issue by DongShaoNB** [Zrips/Residence#843]
Create new residence show deep error

image url:
https://s2.loli.net/2022/01/19/pMBikc84yN6ju13.png
https://s2.loli.net/2022/01/19/gZ3QiqPyHDrYvpL.png

**Comment by ZappySK** [comment]
I have the same problem

**Comment by ZappySK** [comment]
@Zrips

**Comment by DongShaoNB** [comment]
> I have the same problem

Hello，i know how to fix this bug,delete your groups.yml and update residence to 5.0.1.2 , let it create new groups.yml
