### ISSUE TITLE
Dispensers not working with lava or water buckets

### ISSUE THREAD

**Issue by Lemonray114** [Zrips/Residence#846]
I'm using ver.5.0.1.1 and dispenser can't work with both lava and water buckets

**Comment by siulung201314** [comment]
I have the same issue.

**Comment by WolverStones** [comment]
#842

**Comment by John-Eye** [comment]
I'm having this issue too. I have Residence 5.0.1.1 installed.

**Comment by Zrips** [comment]
1896066c3961f46fee9fa277de7507eb217bfcc8
