### ISSUE TITLE
Problem when using /res auto in nether

### ISSUE THREAD

**Issue by Seallos** [Zrips/Residence#847]
**Hello Everyone,**  When i upgrade residence plugin at a new version , i have this issue,, If players want to make residence in nether with command  **/res auto** They will make residence only 1x1 block. 

There is nothing in groups or config for change

Pleas help with this issue :)

@Zrips

Thanks Seall.

**Comment by EkonC** [comment]
I can confirm this issue, same on my server.

**Comment by Seallos** [comment]
@EkonC  ,, Im just find the bad things in settings ,,,  you must go into config file at line 24. NetherHeight must be 254,, just change this save your config restart your server and everything is fine :)) ,, working for me

**Comment by EkonC** [comment]
Yes, this worked. So Zrips should now fix the default value in the config in the upcoming version :)

**Comment by Zrips** [comment]
Should be resolved with latest builds
