### ISSUE TITLE
Players can take the llama carpet

### ISSUE THREAD

**Issue by stefankielbasa** [Zrips/Residence#851]
I have flag:
Container: false
riding: false
use: false

but players still can steal carpets from llama and ride the llama

**Comment by Zrips** [comment]
You need to actually check players access in that residence where he interacts with Llama. Having container: false flag will not allow you to open llama backpack to pick carpet. Same thing in case player has riding false, it wont allow player to ride llamas in that residence.
As of testing everything looks to be working as it should.
