### ISSUE TITLE
Animalkilling flag does not prevent axolotl stealing with bucket

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#852]
Player can steal axolotl with bucket in other players' residence.
I think that axolotl should be protected in residence.

**Comment by Pan1sT** [comment]
fixed by PlayerBucketEntityEvent [ DCTCraft 1.18 ]

**Comment by Zrips** [comment]
d6d3bf4a1df32fe360c11163e382eee9bf1ab536
