### ISSUE TITLE
Unable to load the plugin

### ISSUE THREAD

**Issue by AndrewKopera** [Zrips/Residence#854]
![veci](https://user-images.githubusercontent.com/98646193/151660825-3064e68f-b6ef-48e1-a340-289bcfe6b976.png)
I wanted to install Residence on my server (1.18.1 paper). At first I tried by restarting the server, and it didn't do anything. Then I got PluginManager plugin and I tried ```/pm load Residence5.0.1.1``` and it said ```Could not load the plugin Residence5.0.1.1 (Missing Dependency)``` I do have CMILib. This same thing is also happening with Jobs Reborn.

Thanks for help.

**Comment by Zrips** [comment]
As it states, you need to download CMILib plugin, its a free one and you can get it by checking any plugins top part of description which includes link or simply search for one in spigotmc web page. Its a mandatory plugin as of 1.17+ servers update and used in multiple plugins at this point.

**Comment by AndrewKopera** [comment]
> As it states, you need to download CMILib plugin, its a free one and you can get it by checking any plugins top part of description which includes link or simply search for one in spigotmc web page. Its a mandatory plugin as of 1.17+ servers update and used in multiple plugins at this point.

I said:
>I do have CMILib.

**Comment by Zrips** [comment]
There is only single hard dependency for those plugins, which is CMILib, double check if you actually have it and its loaded in properly, you can use basic /plugins command and check if CMILib is in green color

**Comment by AndrewKopera** [comment]
It is green

**Comment by Zrips** [comment]
Show startup logs

**Comment by AndrewKopera** [comment]
for some reason my server only saves logs when the server shuts down so I cant

**Comment by Zrips** [comment]
Thats more than strange, would start by testing everything with clean setup, logs are saved in real time, if even logs are not saved properly then you might have bigger issues here which can be a cause of all those previous ones

**Comment by AndrewKopera** [comment]
What do you mean by 
>clean setup

**Comment by AndrewKopera** [comment]
What do you mean by 
>clean setup

**Comment by Zrips** [comment]
Create new server setup with default configuration to make sure that its not an issue with some custom config's

**Comment by AndrewKopera** [comment]
Man, I cant just make a new server :D or do you mean something else?

**Comment by Zrips** [comment]
You can make server on your local PC for testing purposes and yea this is exactly what i mean. You need to test it out with clean setup to know that everything works as it should. Not having logs recorded is a big red flag currently as those get recorded all the time and in real time, any change in console will be reflected in file being updated with appropriate information

**Comment by AndrewKopera** [comment]
I cant make it on my pc cuz it would probably explode. Also do we mean the same logs? the ones in the `/logs`? like the latest.log file?

**Comment by Zrips** [comment]
Yes, its in logs folder and latest one named as latest.log which gets filled up constantly while server is running

**Comment by AndrewKopera** [comment]
Well it wasnt filling itself even w/o plugins.

**Comment by Zrips** [comment]
Then you have bigger issues at hand to deal with before going into plugins. Log file needs to be filled up while server is running. Other than this your original message indicated that required plugin is missing, which cant really be the case if plugin actually loaded in. This can be checked in logs file, which i still need to see to know whats going on with your setup exactly
