### ISSUE TITLE
[Bug] Droppers not working with water/lava buckets

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/Residence#858]
When using a redstone dropper within a residence, lava and water buckets cannot be dropped.
If there is a way to fix this without also breaking dispensers it would be much appreciated.
It was working on version 5.0.1.1, now it is bugged again on 5.0.1.2  (Fix for dispensers breaks droppers)

Steps to reproduce:

Create a residence
Place down a dropper and fill it with water/lava buckets
Activate the dropper
Poof nothing comes out

**Comment by Zrips** [comment]
9987c8d6b1b82ed28352bed9f20ae642ee7e8e50
