### ISSUE TITLE
itemframe spawner

### ISSUE THREAD

**Issue by 100petr** [Zrips/Residence#859]
The player cannot insert the spawner into the itemframe. It doesn't matter if the player has a trusted residence or owns it. I tried it on a server where is only a residence, no other plugin. Also tested with default config. It writes to the chat "You are blacklisted from using this item here". Or is it some configurable feature? Maybe it's the same thing as here https://github.com/Zrips/Residence/issues/804
![image](https://user-images.githubusercontent.com/29830635/153176950-5d519436-69ac-4079-9f16-122da70369ff.png)
![image](https://user-images.githubusercontent.com/29830635/153177036-d44c3f09-ff18-4277-9c95-048f95f7f7e7.png)

**Comment by Zrips** [comment]
Go into flags.yml -> ItemList -> DefaultList -> Items and remove `MOB_SPAWNER`, after that simple `/res reload flags` will do the trick and you should be able to add spawners into frames. Will remove it from default black list, cant say why it got included by default in the first place.

**Comment by 100petr** [comment]
ty
