### ISSUE TITLE
How to remove already deleted worlds from config?

### ISSUE THREAD

**Issue by PetyXbron** [Zrips/Residence#865]
Hello,
I recently deleted some Minecraft worlds, and the Residence plugin still thinks that they are existing. But they're not.
How can I remove worlds from Residence save? I tried cleaning `/Residence/Save/Worlds/` (the deleted worlds are not even there) but that didn't help.
![image](https://user-images.githubusercontent.com/35902119/156874886-73ba6791-43f9-4020-892b-621601a64a27.png)

**Comment by Zrips** [comment]
This comes from random teleportation option in your config file, simply remove world records which no longer exist.
