### ISSUE TITLE
WorldGuard AMD luckperms context  support

### ISSUE THREAD

**Issue by BearLeonLight** [Zrips/Residence#868]
The context is
res=owner
res=range (within a domain of RES)
Support for overriding WG __global__ settings
I have to use WG for wild and other related protections, and there are multiple blocks.
Then __global__ I allow them to create their own territory and edit it, but other places are not allowed to create or edit it. Use RES to manage the player's territory, and use WG to manage the map, because WG supports more on other plugins.
If you can support it, the function is very perfect

**Comment by Zrips** [comment]
having multiple area protection plugins will brake things, stick with one of them. Having direct compatibility can make it more complicated as we should know which plugin should take priority over another in specific area or world. No real solution at the moment for something like this.
