### ISSUE TITLE
Permission already registered

### ISSUE THREAD

**Issue by vojtiisek** [Zrips/Residence#869]
Hello. Recently, out of nowhere, Residence has started crashing the server while it is starting due to already registered residence.xxx permissions. Log:
https://pastebin.com/gfcTfGam

Any solutions?

**Comment by Zrips** [comment]
Changing permission plugin could resolve this issue. Try using something more robust like luckPerms. other than this there isint much to know what happening here exactly as Residence simply provides default permissions in plugin.yml file which is common way to define default permissions and its being loaded only once.
