### ISSUE TITLE
Subzones and Random Teleportation [2 issues]

### ISSUE THREAD

**Issue by Niko302** [Zrips/Residence#870]
/res subzone (subzones unlike normal residences can no longer go under 0 Y meaning changing configs to SubzoneMaxUpDown: 400 for subzones does nothing therefore making subzones that ignore Y level is not possible) 
/res rt **(no longer works -> could not find correct teleport location**)

**Comment by Zrips** [comment]
b27b7bae62d840a32725bc429b857de6d7f69577

**Comment by Zrips** [comment]
c7c562278927a677ff7a8cd8905a3fd0cf52d0b3
