### ISSUE TITLE
extremly long loading times

### ISSUE THREAD

**Issue by dan28000** [Zrips/Residence#877]
Setup: latest residences, vault, luckperms connected to MYSQL DB with ton of permissions
when having on server +18k
it takes 600s to load them when vault and luckperms are enabled and connected to DB
log from server https://pastebin.com/nE6jZEDK
when I disable vault then residences load in 20s
or when I disconnect luckperms from database with vault enabled then it also takes 20s to load

Also tested it with old version of 4.9.2.2 with different save
7s for 9k res and with latest verion of residences 40s with vault and LP enabled and connected without vault 7s

cpu usage with and without vault is around 5x more without vault when loading

edit: the fast loading ocourse till version 4.9.3.5 
4.9.3.6 wont load residence save and 4.9.3.7 loads with 40s and spams the hell out of console when turning off
i would guess these commits are the issue 
https://github.com/Zrips/Residence/commit/bae7078f68861b9592b32a16c921cb9168233320
https://github.com/Zrips/Residence/commit/ce0a4610b8c0761acc135e4ec13b453cab406769
https://github.com/Zrips/Residence/commit/7649d85e0b66533ecead1190b4f714e416027f61

**Comment by Zrips** [comment]
Under investigation

**Comment by Zrips** [comment]
Ok, made few changes which should improve loading speeds
2284a5c2837972b145800e6bd17703ff9d35e21c
