### ISSUE TITLE
Group.yml Can't Change.

### ISSUE THREAD

**Issue by Jyun5978** [Zrips/Residence#879]
group.yml Messenger can't Customize Language and Format
I try to modify the language and format of these two strings of instructions,reload and restart server still don't work.

       Messaging:
           CanChange: true
           DefaultEnter: "Welcome %player to %residence, owneAd by %owner."
           DefaultLeave: "Now leaving %residence."
    NextGroup:
       Messaging:
           CanChange: true
           DefaultEnter: "Welcome %player to %residence, owned by %owner."
           DefaultLeave: "Now leaving %residence."
![image](https://user-images.githubusercontent.com/22559124/163721000-9c57ee54-8457-4ac3-b3ba-566e539dc465.png)

**Comment by Zrips** [comment]
Default message gets recorded at the time residence is created, so changing default message would only effect newly created residences and not old ones. If you want to modify that then you will need to modify save files. With optimized save mechanic you should have enter and leave messages listed at the top of file, find default message you want to change and update it there.
