### ISSUE TITLE
follow up - extremly long loading times

### ISSUE THREAD

**Issue by dan28000** [Zrips/Residence#880]
https://github.com/Zrips/Residence/issues/877
Figured it out it's the latency of luckperms DB so there's some interaction betwen vault and luckperms and residences when vault is present then residences or vault forces to search in LP DB then including I assume round trip of the req + latency of the DB it self

when debuging i saw moderate troughput around 2-4mbps combined over the network with local MYSQL DB for luckperms with permissions (the pictures are from the local MYSQL DB)
without vault that doesn't happen
with remote LP DB then the troughput is pretty much nonexistent resulting into residence loading like 10mins

before and after req for the DB with vault present and amount of data in LP DB it self
![image](https://user-images.githubusercontent.com/84990628/164046351-7c7fd137-db48-4f2d-bc91-86766390bba7.png)
![image](https://user-images.githubusercontent.com/84990628/164046404-ff46ae6e-e783-4bbb-bf75-1c20bf894ed4.png)
![image](https://user-images.githubusercontent.com/84990628/164046509-797b329e-0a6c-4916-a2d8-788b45169d05.png)
it sums up pretty nice 24.7k for each select, stmt execute and stmt reset

considering that when testing last time it was loading fine till version 4.9.3.5 something had to change after that version 

My conclusion is to add option to force residences to use it's internal LP hook or try to figure out what is causing it

**Comment by Zrips** [comment]
By any chance you could try it out with latest version?

**Comment by dan28000** [comment]
This is the testing with latest version

**Comment by dan28000** [comment]
the last testing 4.9.3.5 was the last version when it was loading fine
then rest of the last issue was on version 5.0.1.3

in here the testing was done on 5.0.1.5 - latest version

**Comment by Zrips** [comment]
Ok, will check what i can optimize more

**Comment by dan28000** [comment]
I Sent more info to discord

**Comment by dan28000** [comment]
this commit https://github.com/Zrips/Residence/commit/7649d85e0b66533ecead1190b4f714e416027f61

Claimresidence class
![image](https://user-images.githubusercontent.com/84990628/166108362-bdfaecc5-2c87-4d37-a0a6-ae2cf9fd9b7e.png)

playermanager class
this is it causing it when vault is present
![image](https://user-images.githubusercontent.com/84990628/166108257-a4aab5a0-6aa0-4418-82a3-49106f3ef17a.png)
