### ISSUE TITLE
[Question] /res set GUI cannot display icons

### ISSUE THREAD

**Issue by Yurinann** [Zrips/Residence#881]
![image](https://user-images.githubusercontent.com/75569395/165679801-ccfa215c-9df2-4080-b2e2-14aff33cdad3.png)

Click is normal

Server version: 1.18.2 Mirai
Java version: 17.0.3

**Comment by Zrips** [comment]
an you give actual example what you used for those slots?

**Comment by Zrips** [comment]
446584db5e440a65b3329435ab1d45f514c6864a
