### ISSUE TITLE
[Suggestion] Add res bank limit 

### ISSUE THREAD

**Issue by menkisa** [Zrips/Residence#882]
I think it would be nice to have a bank deposit limit to the configuration added. Such as the economy limit, it would be nice to be able to set a certain amount of limit for deposits in the res bank function.
Greetings!

**Comment by Zrips** [comment]
are we talking about one time transfers or general limitation how much money res bank could hold?

**Comment by Zrips** [comment]
ef704e7b44cde43236259fd762f8658a21773ea9
