### ISSUE TITLE
nomobs flag does not work

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#884]
When nomobs flag sets to be true and set AutoMobRemoval to true in config,
mobs can be still inside the residence and cannot be removed.

**Comment by SickProdigy** [comment]
Which kind of mobs?
The phantom are seperate
phantomspawn flag to false for them. Not seeming to have an issue with it with 1.18.2 spigot.

**Comment by Zrips** [comment]
Without knowing actual example of monster which remains in residence its hard to say. 
Other than this, noticed small posible issue here. Generally we are only checking residences where we have atleast one player in it, as it would be to heavy on server side to check every single residence out there for any entities in them. 
Made few changes to improve performance and make it consistent 
f7546225bf1b57674fc7bd829bd50909be484bb2
