### ISSUE TITLE
【bug】grow节点不能有效阻止垂泪藤生长

### ISSUE THREAD

**Issue by JiangQiYan713** [Zrips/Residence#890]
【复现步骤】
1.创建一个领地
2.用/resadmin set将节点grow设置为false
3.在领地内放置藤蔓（对照组）和垂泪藤（实验组）
4.设置/gamerule randomTickSpeed为3000
5.可以观察到藤蔓无变化，但垂泪藤正在疯狂地生长
【预期行为】
在grow节点为false的情况下，垂泪藤无法生长
【服务端版本】
- Paper1.18.2(git349)
- Residence 5.0.1.6
- 不包含其他可能影响生长事件的插件和领地插件
【控制台输出】
无

————————翻译(translation)————————
可能翻译不准确，请见谅、、、、
The translation may not be accurate, please forgive me....

[recurrence steps]
1. create a residence
2. set node growth to false with /resadmin set
3. place vines (control group) and weeping vines (experimental group) in the residence
4. set /gamerule randomtickspeed to 3000
5. it can be observed that there is no change in the vine, but the weeping vine is growing crazily
[expected behavior]
When the growth node is false, the weeping vine cannot grow.
[server version]
- Paper1.18.2(git349)
- Residence 5.0.1.6
-It does not contain other plug-ins and domain plug-ins that may affect growth events
[console output]
nothing

**Comment by Zrips** [comment]
caf455b061a9ab8fc5d4ea40c53dd544c9fedda8
