### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Paragonas** [Zrips/Residence#891]
Hello, is there any way to disable tab complete for commands that player don't have permission to use?

**Comment by JiangQiYan713** [comment]
用类似GroupManager的插件去除全局组对应的权限节点

**Comment by Paragonas** [comment]
> 用类似GroupManager的插件去除全局组对应的权限节点

that's not what I'm asking

**Comment by JiangQiYan713** [comment]
可以尝试一下这款插件https://www.mcbbs.net/thread-964406-1-1.html

>

**Comment by Paragonas** [comment]
anyone?

**Comment by Zrips** [comment]
66058f24f7c110cd21b634082bae8d2085d35dd7
