### ISSUE TITLE
Pay

### ISSUE THREAD

**Issue by RalphBohnerMWV** [Zrips/Residence#895]
Hi! Sorry to bother yall, but I can't figure out how to change the pay per block. Thanks.

**Comment by SickProdigy** [comment]
minecraft/spigot/plugins/Residence/groups.yml

Economy:
            # Whether or not players in this group can buy other Residences that are for sale.
            CanBuy: true
            # Whether or not players in this group can sell their Residences.
            CanSell: true
            # Whether or not to ignore the Residence size/count limits when buying a residence.
            IgnoreLimits: true
            # The cost, per block, of making a new Residence or adding a area to it.
            BuyCost: 0.5
            # The cost, per block, player will be getting back when removing residence. 
            # ATTENTION ResMoneyBack needs to be enabled in config file for this to work
            SellCost: 0.3
            # The cost, per block, of renewing a Residence lease (if the lease system is enabled).
            RenewCost: 0.2
            # Flags are checked in the order:
            # 1: Player
            # 2: Group
            # 3: Owner
            # 4: If all others are undefined, reverts to default value (usually true).
            # Flag permissions default to false.
            # These flags settings override the globals.

There's like 3 config files that actually contain anything. Did you you look or honest mistake?

**Comment by RalphBohnerMWV** [comment]
I looked, but I guess that I overlooked. I even asked a friend and she was confused as well.

**Comment by RalphBohnerMWV** [comment]
@SickProdigy Ok, I just looked at pay and tried it. Apparently, its doing the full area and not the diameter. It is literally giving me a 150000 house, which it should not be doing.

**Comment by SickProdigy** [comment]
> @SickProdigy Ok, I just looked at pay and tried it. Apparently, its doing the full area and not the diameter. It is literally giving me a 150000 house, which it should not be doing.

So now there is another setti by to use y axis or not in the same file. Change from true to false and it should only do surface area

**Comment by RalphBohnerMWV** [comment]
@SickProdigy Thanks. I will try that now. The reason why I call it pay was because I am the one who sets up the residences and I am the government. Therefore, people pay me to get houses. So, its a pay issue.

**Comment by RalphBohnerMWV** [comment]
@SickProdigy It worked. Thanks.
