### ISSUE TITLE
Questions about fire damage

### ISSUE THREAD

**Issue by ShintoKosei** [Zrips/Residence#899]
I used residence5.0.1.6 in paper1.19
Then I created a territory
I set the creatures in the territory on fire (including but not limited to flame attachment, fire arrow and magma)
At first, the player found that the magma in the machine he operated could not cause damage to creatures. I tried weapon attachment and flint, but they could not cause damage to creatures
Outside the territory, they can normally take fire damage
What do I need to do? I didn't find the option to disable fire damage in the territory settings (including the plug-in settings)

**Comment by Zrips** [comment]
Flag you are looking for is animalkilling which is disabled by default when it comes to fire damage. Simply use **/res set animalkilling true**
