### ISSUE TITLE
door flag not registering saving to res_world.yml

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Residence#9]
Using the 4.5.13.3 build, I had a user try to open a door in a residence that has "door" true set on it but the door couldn't open.  I checked the /res info and can see door true on it and it is enabled in flags.yml.
However, when I looked at the res_world.yml, the same residence that shows true for doors doesn't have doors: true or doors: false in it.  So it appears like we can set it, but it will never work.

Looking closer at the image below you'll notice that commandblock, command & door are all missing.
![flagissue](https://cloud.githubusercontent.com/assets/10309346/22270209/8b4082bc-e25c-11e6-9b45-b90163f49c96.png)

**Comment by Zrips** [comment]
Hmmm, tested out and all seams to be working, did you waited for auto save to save new updated flags into file? As they are not saved straight away into files. And do you have similar issues with other flags or only those ones?

**Comment by smmmadden** [comment]
yes, I even stopped the server, watched the saves take place and restarted.  Those three flags are not getting added to the residence. \save\res_survival.yml file.

**Comment by Zrips** [comment]
Thats really strange as flags are not filtered by anything when they are saved, its direct save, so there should not be any reason for door flag not to be saved when others are. Try out on clean server with clean config files.

**Comment by smmmadden** [comment]
I could try that, but just for the record, all 5 of my servers save\res_*.yml files do NOT include the three flags set in any of the residences and they are shown in the chat window.   I'll backup the config, flags, groups, shopsigns, shopvotes and uuids.yml files and let them get recreated.  Then I'll verify if the flags get set on the residences.

**Comment by smmmadden** [comment]
just tried it and I only see door: true on one of the residences under AreaFlags but not for the one I'm looking at.  All I did was rename the yml files under \residence\ folder and started the server (twice) to see if it would make any difference but it did not.  Could it be that the residence name of "Spawn" is causing the problem?  That is the common piece to each that I'm seeing issues with.   If I do /res info while in spawn, the flags show properly, but looking at the res_survival.yml they are not there.

**Comment by Zrips** [comment]
Hmmm, double check your save for for duplicated spawn entries, as it looks like you have 2 residence's one with "Spawn" name and another most likely with "spawn" or similar and plugin get's confused for which residence we need to save flags but its gets correct flags when trying to find one by location. Just double check, then i will have better idea how to try solving this to avoid issues in future.

**Comment by smmmadden** [comment]
Interesting you mention that.  When I checked the file for "spawn" there are two entries in one world.  The residence name and the CapitalizedName properties.  Not sure what CapitalizedName is used for as the value is not shown as capitalized - it is identical to what the user put in for the residence name.  One world has more occurances of "Spawn" listed, so I'll need to massage the file a bit to clean it up.  Probably happened when I had to remove and recreate the Spawn residence a few times to get the right size to fit the subzones in it.

When I created a new residence, I added the door flag, and it shows under the AreaFlags section for that residence, not under PlayerFlags which appears to be correct.  The flags.yml did not have a default of "true" for door (it wasn't listed at all).  So I guess the default value for door is false?

Give the information above, I'll make the flag changes in each server and then see if it occurs again.  For now, go ahead and close this issue.    Thanks!

**Comment by smmmadden** [comment]
**Update:**  in one world, I have checked the res_survival.yml file and Spawn exists once for the residence name.  It does also however occur as a subzone under Trap.spawn.  This also means that there is a duplicate (aside from the upper case S) name listed for CapitalizedName.  The residence has Spawn and the subzone has: spawn.  Arguably I would expect the CapitalizedName value to be all upper cased and the CapitalizedName property being different for a subzone?

**Comment by Zrips** [comment]
Can you send me world save file so i could test it out if it works properly on my settup and if not to simplify debuging?

**Comment by smmmadden** [comment]
Thanks!  The SAWorld is the world I found that the door flag wasn't getting added.  The SIWorld is the world where multiple occurrences of "Spawn" are showing up and the same world which I've had the most issues with doors (like having to click on the top half of a door in spawn) to open/close it. :-)
[res_survival.yml._SAWorld.txt](https://github.com/Zrips/Residence/files/738915/res_survival.yml._SAWorld.txt)
[res_survival.yml_SIWorld.txt](https://github.com/Zrips/Residence/files/738917/res_survival.yml_SIWorld.txt)

If you need anything else let me know.  Feel free to IM me as well if you use Yahoo (pegamadds) or Trillian (smmmadden).  :-)

**Comment by smmmadden** [comment]
How did it go?  I see someone else reported that Destroy flag is missing.

**Comment by Zrips** [comment]
Cant really reproduce you issue and cant determine where issue could be as there is no filtering for flag save, so there is no reason for it not to be saved. Did you tested with clean server?
For that another issue i did mention that is simply missing from defaultflag group in flags.yml, so its not related.

**Comment by smmmadden** [comment]
Hey there - go ahead and close this ticket.  Since I've recently moved to PEX and re-wrote the permissions completely (for a third time), I believe all these door/flag issues were the result of conflicting perms and a possibly an issue with the res on that world.  Everything appears to be working good now. :-)

**Comment by Zrips** [comment]
Nice to hear that
