### ISSUE TITLE
When using a crossbow in a dwelling, arrows are not consumed, and more arrows are produced that can be used.

### ISSUE THREAD

**Issue by RICE0707** [Zrips/Residence#900]
[https://youtu.be/Cwn1pWThdr0](https://youtu.be/Cwn1pWThdr0)

**Comment by Zrips** [comment]
Not much to go on, what flags have you set in this particular residence? What type of enchants you have on this crossbow?  Server version?

**Comment by RICE0707** [comment]
> 

I just found out when I was trying to find the cause of the problem
 This error occurs only when the permission nodurability is set to true

The crossbow used does not have any enchants, the server version is 1.19

**Comment by rDruTNT** [comment]
#903

**Comment by Zrips** [comment]
0194107f0a78be39b69a141428696016f9287b52
