### ISSUE TITLE
Command on show the residence info error and then the player lost his connection.

### ISSUE THREAD

**Issue by Yingz520** [Zrips/Residence#905]
[15:58:29 INFO]: xxxissued server command: /res info
[15:58:29 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 50224 bytes encoded, max 44767)
[15:58:29 INFO]: xxx lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
[15:58:29 INFO]: [-] xxx

When the player issued the commands "/res info" that it makes some error and the player will lose his connection. It maybe the information too long. So I want to know how to solve this problem. Thx.

**Comment by Zrips** [comment]
Can you show me your locale file? As it looks to be issue with to long message, most likely for listing all of the players and their flags

**Comment by Yingz520** [comment]
It is indeed caused by too many player flags set by players. Is there a solution?

**Comment by Yingz520** [comment]
https://airportal.cn/48341/qMAfRxjHIx

**Comment by Yingz520** [comment]
You can get the example through this link

**Comment by Zrips** [comment]
Can you give actual record from save file? And you can use https://pastebin.com/ for simpler text uploads

**Comment by Yingz520** [comment]
Fine! https://pastebin.com/xqLzYVjh

**Comment by Yingz520** [comment]
It will be burned after reading the paste

**Comment by Zrips** [comment]
Well link doesn't work anymore, so thats that. Will do some testing and try to rework that part of output as I wanted to improve on it anyways.

**Comment by Yingz520** [comment]
So,should I upload the text again?

**Comment by Yingz520** [comment]
My English is not so good. I wonder if you have received it.

**Comment by Zrips** [comment]
f0155ee3b943f5fbabfc71de1ac40c4ae1a792a9
New version should come out tomorrow or you can compile your own currently if you know how. But would suggest to wait.
This will introduce some rework when it comes to residence information show while having bunch of players with some other small additions.
