### ISSUE TITLE
Flag issue / No Mobs at Nether

### ISSUE THREAD

**Issue by e-MT-y** [Zrips/Residence#908]
Flags for NoMobs and no Mobspawning doesn't work at nether worlds. 
Mobs continue to spawn in the protected area. If they spawn outside the area, then enter the area anyway. 
![Residence issue](https://user-images.githubusercontent.com/106277868/180047308-b4bfcf8f-0600-465d-b2b3-19a510a5df5d.jpg)

**Comment by RetamrCZ** [comment]
Same for me, if i spawn skeleton near residence and he see player, he just rush to him. It seems for him like, there isnt any residence.

**Comment by RetamrCZ** [comment]
But, do you have AutoMobRemoval enbled?

**Comment by Zrips** [comment]
b7625a2084dcd89a7f82ce998f2c8cdd2479c8d2
