### ISSUE TITLE
Fire-spread doesn't override worldguard

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/Residence#909]
Hi not sure if this is unintended or not but when fire-spread is disabled by worldguard
and turned to true within a residence it does not work.

**Comment by Zrips** [comment]
Having multiple area protection plugins in one place will cause issues like this. Its not like we know which plugin should have higher priority over each event so there is no way to know if it should take flag setup from residence or world guard as main one while ignore other one. Try to stay with one protection plugin or atleast use one as minimally as possible. 
And you can disable fire globally with residence plugin if needed in flags file.
