### ISSUE TITLE
Not enough money to pay 0$

### ISSUE THREAD

**Issue by Luna-devv** [Zrips/Residence#910]
I have the issue that it gives me a not enough money warning when it only costs 0$ (aka for free)
![image](https://user-images.githubusercontent.com/71079641/180574512-5b6f4d52-40e5-437b-b6d1-0ee43326f692.png)

![image](https://user-images.githubusercontent.com/71079641/180574537-bbef5b87-194f-4eb2-9e26-bcb85e609af2.png)

**Comment by Zrips** [comment]
e9eb9e8a65ce9e99820f9553a66b861e95e94255
