### ISSUE TITLE
Non-full blocks allow players to place blocks/liquids inside residences they don't have access to

### ISSUE THREAD

**Issue by DogeTennant** [Zrips/Residence#914]
Hello, I won't explain the issue with words too much so it's not a long post, and I have video that'll explain it better than I can

But basically, a player that doesn't have access to a residence, can place a non-full block next to the residence (glass pane, fence, iron bar, any block like that) and then step into the residence and place a liquid from inside the residence on the side of that glass pane and spill the liquid inside the residence even if we have liquids flowing from outside the residence to inside the residence disabled.

https://www.youtube.com/watch?v=1Nq3FyjSUhQ

Any fix for this would be much appreciated! I can try to assist you with more info but I think this is everything I can give you

**Comment by Zrips** [comment]
849fe8969bab5176f39508d8f866e7f29e521093
