### ISSUE TITLE
break,place,build bypass bug

### ISSUE THREAD

**Issue by RetamrCZ** [Zrips/Residence#915]
Hi, everyone can place and break block in residence (1.19 server version, latest residence).
Even if i have build,place,destroy set to false. It sends error message with saying, i can't break/place block here but i can break/place block as default.

Server version: 1.19-R0.1-SNAPSHOT (Git: 41238a4) git-Paper-56
Residence version: 5.0.1.7

**Comment by RetamrCZ** [comment]
https://youtu.be/OnbPJmjxq7s

**Comment by RetamrCZ** [comment]
And i am sorry, i sending flags, config, groups
Config.yml: https://pastebin.com/wBfXiPwh
Flags.yml: https://pastebin.com/asRHikgt
Groups.yml: https://pastebin.com/dMLTzLKg

**Comment by Zrips** [comment]
Can you send me record of that particular residence from save file too? Something weird is going on here.

**Comment by RetamrCZ** [comment]
If you mean Residence/Save/Worlds/res_world.yml
Then there is file
https://pastebin.com/6hu9HdSh
(This residence is in world but, player can break/place block in every residence)

**Comment by Zrips** [comment]
Could be issue with permission access. Could you try testing your residence setup on a clean server without any preset permission and just having simple player with default permission access trying to place/break worlds in residences?

**Comment by RetamrCZ** [comment]
Ok gimme 2-3 minutes

**Comment by Zrips** [comment]
And do it without any other plugin besides residence, in case there is issue with another plugin interfering. 
In general having error message that you cant brake blocks in residence is fired when brake event is canceled, so it should not really be possible to brake block while still getting that error message.

**Comment by RetamrCZ** [comment]
I have worldguard too.

**Comment by Zrips** [comment]
Just test out without any other plugin, if issue is resolved we will know that there is issue with another plugin and we can get to the cause and come up with a solution

**Comment by RetamrCZ** [comment]
Now it works.

**Comment by RetamrCZ** [comment]
I dont think, permission issue it will be. Because in luckperms, default group has residence.* false and all bypasses to false too.

**Comment by Zrips** [comment]
Then try to re-add most obvious plugins which could interfere here until issue comes back

**Comment by RetamrCZ** [comment]
![image](https://user-images.githubusercontent.com/59335201/183619728-9f43015b-f147-4e71-bf0d-07c5bf72b5da.png)
Advancements, ServerTutorial, Mining are custom.

**Comment by RetamrCZ** [comment]
Okey.

**Comment by Zrips** [comment]
You start with Mining plugin. If it does anything with block break, it could be the cause

**Comment by RetamrCZ** [comment]
Nope, with mining plugin it works.

**Comment by Zrips** [comment]
Have you figured out which plugin causing this issue?

**Comment by RetamrCZ** [comment]
Still finding.

**Comment by Zrips** [comment]
Quickest method is to do it in halfs, add back half of the plugins, if issue returns, you have one of those at blame, if not, then its in another half, more times doing this and you will quickly figure out which one in particular causes this.

**Comment by RetamrCZ** [comment]
okey, i uploading whole backup (only plugins) to another server and i will remove one by one. I uploaded 90%

**Comment by Zrips** [comment]
Doing it one by one will take allot of time, doing it by half will be really quick test, it would like max 5 restarts before you get to the correct plugin

**Comment by RetamrCZ** [comment]
Found problem!

**Comment by RetamrCZ** [comment]
The plugin, cancels event is my own.

**Comment by RetamrCZ** [comment]
`package retamrovec.finesoftware.servertutorial.servertutorial.Listeners;

import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import retamrovec.finesoftware.servertutorial.servertutorial.Arraylist.Status;

public class BlockBreakListener implements Listener {

    private final Status status;
    public BlockBreakListener(Status status) {
        this.status = status;
    }

    @EventHandler (priority = EventPriority.HIGHEST)
    public void onBreak(BlockBreakEvent e) {
        e.setCancelled(status.getStatus().contains(e.getPlayer().getName()));
    }

}
`
BlockBreak class,
blockplace is same.

**Comment by RetamrCZ** [comment]
So, i have to add residence api and check if player is in residence right?

**Comment by RetamrCZ** [comment]
Where can i find maven?

**Comment by Zrips** [comment]
Residence cancels event if you cant brake/build in area, so by simply checking if event is already canceled you can avoid all this issue without having any direct compatibility and actual universal code.

**Comment by Zrips** [comment]
```
    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onBlockBreak(BlockBreakEvent event) {
    }
```
Would do the trick. If even is canceled you should not even bother running this part of the code

**Comment by RetamrCZ** [comment]
But, if priority is lowest, why i checking if is event cancelled? Highest will be runned first

**Comment by Zrips** [comment]
Ether way, if event is canceled then you should NEVER reenable it independent which plugin done this, Residence or worldguard
And it was just example code, adjust priority to your own needs.

**Comment by RetamrCZ** [comment]
Okey

**Comment by RetamrCZ** [comment]
Ok. And where i can find maven for residence api?

**Comment by Zrips** [comment]
There isint one at the moment, need to properly set it up at some point, but you dont really need it for your personal needs.

**Comment by RetamrCZ** [comment]
okey. thanks i try to change it.

**Comment by RetamrCZ** [comment]
works, only BlockBreakEvent does nothing even if is event cancelled. idk why but it should not be problem because locations where i should be teleported, are in residence.

**Comment by RetamrCZ** [comment]
But thanks for your time and i am sorry for my stupidity.
