### ISSUE TITLE
%residence_user_current_flag_[FlagName]%

### ISSUE THREAD

**Issue by Tazler89** [Zrips/Residence#918]
%residence_user_current_flag_[FlagName]% is not working returning the placeholder its self, is not returning any result tested with both /res and /papi
![image](https://user-images.githubusercontent.com/51469267/183647977-60a1e93a-bf0d-4f8e-b8d6-c9af02bcec9a.png)

**Comment by Zrips** [comment]
563e25f62be2f9c6b1cc4a64a55d6a1c8170197e
