### ISSUE TITLE
Is the plugin able to prevent mod monster from entering the residence? And how to check which group a player belongs to?

### ISSUE THREAD

**Issue by abaabaaba-cpu** [Zrips/Residence#919]
My server is 1.12.2, and there are monsters from mods, and it seems that residence can only prevent minecraft's monsters like zombies and creeper.

**Comment by Zrips** [comment]
it really depends how custom mob was defined. Generally we are using this check https://github.com/Zrips/Residence/blob/b7625a2084dcd89a7f82ce998f2c8cdd2479c8d2/src/com/bekvon/bukkit/residence/listeners/ResidenceEntityListener.java#L130 for determining if entity should be counted as one which needs to be removed. Keep in mind that monsters in residences with nomobs flag gets removed on specific intervals as we cant check on each mob move event as that would be overkill. But if mob gets into this category it should be removed. 
Amd for group check
`ResidencePlayer.get(@player).getGroup()`
