### ISSUE TITLE
Cannot remove others Residences

### ISSUE THREAD

**Issue by krmmer** [Zrips/Residence#93]
I cannot remove others residences with /res remove [residencename] although i am op and have all permissions

**Comment by krmmer** [comment]
If i do so there comes no info for "type res confirm....." there comes nothing. if i try it on the console the info shows up but i cant confirm on the console..

**Comment by Oruss7** [comment]
Are you using console or in-game as op ?
I'm op and not have problem to remove players residence. I confirm with /res confirm.

**Comment by Zrips** [comment]
./resadmin remove [residenceName] will bypass restrictions pretty much in any situation including in removing residences.
