### ISSUE TITLE
residence.cleanbypass

### ISSUE THREAD

**Issue by Niko302** [Zrips/Residence#936]
residence.cleanbypass does not work when given the permission.
The residence still gets unclaimed even if the user has the permission for the residence to not be looked at upon being inactive for a certain amount of time.

**Comment by Zrips** [comment]
Which permission plugin are you running?

**Comment by Zrips** [comment]
500f11f1151c6c6ceb2b51260dff3b8415e17c27
Tho it will only work if you have LuckPerms permission plugin as it can check players permission access when they are offline.
