### ISSUE TITLE
"com.bekvon.bukkit.residence.persistance.YMLSaveHelper.getRoot()" is null

### ISSUE THREAD

**Issue by TiaTheFairy** [Zrips/Residence#937]
While I starting the server, these error shows and then, it stops my server.
I have also tried the latest build (5.0.2.0) and the same issue persists. 
And if I uninstall Residence then the server can start so I locate the issue here.
Server is on 1.16.5, paper spigot.

Edit: It is not totally 'stops the server', it broke the starting process, and stuck the minecraft thread and I can't do anything except restarting my device.

> [16:29:59] [Server thread/INFO]: [Residence] Enabling Residence v5.0.1.6
> [16:29:59] [Server thread/INFO]: [Residence] Can't find world with (fb1) name
> [16:29:59] [Server thread/INFO]: [Residence] Can't find world with (fb2) name
> [16:29:59] [Server thread/INFO]: [Residence] Loaded (4) groups
> [16:29:59] [Server thread/INFO]: [Residence] Found Vault using permissions plugin:LuckPerms
> [16:29:59] [Server thread/INFO]: [Residence] Scanning for economy systems...
> [16:29:59] [Server thread/INFO]: [Residence] Found Vault using economy system: EssentialsX Economy
> [16:29:59] [Server thread/INFO]: [Residence] Loaded sc data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded tear2 data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded world data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded world_the_end data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded spawn data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded world_nether data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded dungeon2 data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded dungeon1 data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded tear1 data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/INFO]: [Residence] Loaded zy data into memory. (0 ms) -> 0 residences
> [16:29:59] [Server thread/ERROR]: [com.bekvon.bukkit.residence.Residence] null
> java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "com.bekvon.bukkit.residence.persistance.YMLSaveHelper.getRoot()" is null
> 	at com.bekvon.bukkit.residence.Residence.loadYml(Residence.java:1450) ~[?:?]
> 	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:671) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
> 	at java.lang.Thread.run(Thread.java:831) [?:?]
> [16:29:59] [Server thread/ERROR]: [Residence] Unable to load save file
> java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "com.bekvon.bukkit.residence.persistance.YMLSaveHelper.getRoot()" is null
> 	at com.bekvon.bukkit.residence.Residence.loadYml(Residence.java:1450) ~[?:?]
> 	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:671) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
> 	at java.lang.Thread.run(Thread.java:831) [?:?]
> [16:29:59] [Server thread/INFO]: [Residence] Disabling Residence v5.0.1.6
> [16:29:59] [Server thread/INFO]: [Residence] Found WorldEdit 7.2.12+6240-87f4ae1
> [16:29:59] [Server thread/INFO]: [Residence] - FAILED INITIALIZATION! DISABLED! ERROR:
> [16:29:59] [Server thread/ERROR]: [com.bekvon.bukkit.residence.Residence] null
> java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "com.bekvon.bukkit.residence.persistance.YMLSaveHelper.getRoot()" is null
> 	at com.bekvon.bukkit.residence.Residence.loadYml(Residence.java:1450) ~[?:?]
> 	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:671) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
> 	at java.lang.Thread.run(Thread.java:831) [?:?]
> [16:29:59] [Server thread/ERROR]: Error occurred while enabling Residence v5.0.1.6 (Is it up to date?)
> java.lang.IllegalStateException: zip file closed
> 	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
> 	at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
> 	at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
> 	at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Paper-794]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
> 	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:840) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
> 	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Zrips** [comment]
5a7bbfe6672060cfc5d08601371170ffa92617b2
Tho you seamingly have issue with your forsale.yml file which most likely got modified by hand and introduced some issue in it which caused this issue.
