### ISSUE TITLE
Maven/Gradle Support

### ISSUE THREAD

**Issue by Mishyy** [Zrips/Residence#94]
As this project uses Ant, an older "cousin" of Maven and Gradle, sites such as [jitpack](https://jitpack.io) are not able to be used with this project.

Due to this, using this project as a dependency in other plugins is much harder to do, as it requires actively sourcing and distributing jar files in order to keep everything up to date (which is also sometimes against projects' licensing).
All of this hassle could easily be avoided if the project could be moved to a build system such as Maven or Gradle, which those sites do support.

JitPack Docs: [jitpack.io/docs/](https://jitpack.io/docs/) 

A much simpler explanation, focusing more on maven can be seen in Issue #42

**Comment by Rukes** [comment]
👍
