### ISSUE TITLE
Residence not Work idk why

### ISSUE THREAD

**Issue by SkorkyEU** [Zrips/Residence#941]
![image](https://user-images.githubusercontent.com/113280185/189530960-425a0dde-fdcc-4fd7-a994-43163ca5fb85.png)
![image](https://user-images.githubusercontent.com/113280185/189530969-ea38bcd1-a143-4d08-b1a9-e33520cc2ef6.png)
![image](https://user-images.githubusercontent.com/113280185/189530977-78648a62-f3c5-4eff-9aef-ad5c05cede53.png)
![image](https://user-images.githubusercontent.com/113280185/189531011-3f7327cb-92e5-4e58-ab2a-0ff48fba2ef5.png)
or this 
![image](https://user-images.githubusercontent.com/113280185/189531021-30a839d9-3007-4b7d-925f-6ad5c4d4da3f.png)
 
 
 pls help

**Comment by Zrips** [comment]
As it says your selection area is too small of only 1 block in height while minimal size is 3 as its set in groups file. Residence by default works in cuboids, in exact cuboids you selected. If you want to have it from bedrock to the sky by default you will need to enable IgnoreY in config file. You can use /res auto command which will automatically create residence around player to max size it can.
