### ISSUE TITLE
Can i pay with PaySafeCard

### ISSUE THREAD

**Issue by Vianoce** [Zrips/Residence#942]
Can i pay with PaySafeCard Please ?

**Comment by Zrips** [comment]
Only paypal is accepted at the moment.

**Comment by Vianoce** [comment]
Or skrill ?
I dont have paypal sorry

**Comment by Vianoce** [comment]
I dont wanna free bc i dont will show the residence on the dynmap :/

**Comment by Vianoce** [comment]
What

**Comment by Vianoce** [comment]
Let me look

**Comment by Vianoce** [comment]
Thanks Petr

**Comment by Vianoce** [comment]
Have good day
