### ISSUE TITLE
[Feature] res auto name

### ISSUE THREAD

**Issue by Oruss7** [Zrips/Residence#95]
Hello,

Can you add an incrementation if residence name already exist please ?

Example:
- player "Oruss7" create a first res: /res auto. residence name = player's name = "Oruss7".
- player create second res: /res auto. actually: error, res already exist. with increment: residence name = player's name + "_1" = "Oruss7_1"
- player create third res: /res auto. actually: error, res already exist. with increment: residence name = player's name + "_2" = "Oruss7_2"

Thanks you

**Comment by Zrips** [comment]
Good point. Will add this one
