### ISSUE TITLE
/res auto

### ISSUE THREAD

**Issue by arijus1235** [Zrips/Residence#959]
![Desktop Screenshot 2022 11 10 - 12 53 08 58](https://user-images.githubusercontent.com/87641228/201133930-936d0f7e-042f-495a-9324-63a5337a6a2c.png)
when i do /res auto command, it should make maximum plot posibble. I made the cost 0 per block
the plot in config max is 50x50, when i do the /res auto command it says both selection points need to be in your residence idk why

**Comment by Zrips** [comment]
This message would appear if you tried to make subzone while standing inside residence.
