### ISSUE TITLE
How to let other players add new players to a residence they aren't admin of?

### ISSUE THREAD

**Issue by pixel-cabin** [Zrips/Residence#962]
Having trouble with getting players that are already in the main spawn residence to add others to it using /res padd though they aren't the admin so they can't use it unless the residence owner or admin is on, is there a permission node that can be used? I tried residence.command.padd but that didn't work. Thanks

**Comment by Zrips** [comment]
Players need to have admin flag in that residence if they should have ability to change residence flags, which padd does.
