### ISSUE TITLE
YAML Limit - Custom SnakeYAML usage

### ISSUE THREAD

**Issue by MrApik** [Zrips/Residence#965]
Maybe the solution for new 3MB file limit can be custom usage of SnakeYAML instead of using the built-in API.

SnakeYAML supports custom limit option. See WorldEdit's solution:
https://github.com/EngineHub/WorldEdit/commit/0ef38b529231283ceaeb00b0eaaeb670fb3f0a44

**Comment by Zrips** [comment]
a3cd3c9d0f4c920e4a4388395aa25cc7ed0219b3
