### ISSUE TITLE
enter/leave message remove dont work when close and restart

### ISSUE THREAD

**Issue by Ticozheng** [Zrips/Residence#967]
I had used "res message <residence name> enter remove" to remove enter message for some residences with the latest version 5.1.0.0, it work immediately, but seems cant save to message files, when I stop the server and reboot it, the enter message come out again, and I had check the message file and it seems normal

**Comment by Zrips** [comment]
558ef50cd0a4f6dcbeec958ac65948ec00c929e6
Reverting back old save mechanic as we got option to increase file size.
