### ISSUE TITLE
Error in create a Residence with using op

### ISSUE THREAD

**Issue by Slime1207** [Zrips/Residence#968]
Hey! Which settings can let op create the Residence? And what permission can let admin didn't have maximum for creating a Residence?

**Comment by Slime1207** [comment]
Sorry. Is what permission can let admin didn't have maximum for expand a Residence

**Comment by Zrips** [comment]
/resadmin is the main command for admins to be used while performing any other sub command which will bypass most if not all limitations. Permission node for it residence.admin
