### ISSUE TITLE
newplayer creation is not free?

### ISSUE THREAD

**Issue by kretoz** [Zrips/Residence#969]
i have tried to create a new residence with several new accounts for testing the option 
  NewPlayer:
    Use: true
    # Setting this to true, residence will be created for free
    # By setting to false, money will be taken from player, if he has them
    Free: true

every attemp is chargin new player a money for creating residence....am i missing something or this feature is broken ?

**Comment by Zrips** [comment]
This only applies while placing chest on the ground as comment above this section indicates. Might not have been too clear or obvious when it applies.
