### ISSUE TITLE
API Method to see if chunk contains residence 

### ISSUE THREAD

**Issue by MarkehMe** [Zrips/Residence#97]
Hi! Thanks for providing a thorough API! 

The API at the moment seems to allow checking on a location basis and I have a few neat utility ideas.

1) CuboidArea builder-like methods

```java
	public static CuboidArea create (Location locationLow, Location locationHigh) {
		CuboidArea area = new CuboidArea();
		area.setHighLocation(highLocation);
		area.setLowLocation(lowLocation);
		
		return area;
	}

	public static CuboidArea create(Chunk chunk) {
		int x1 = chunk.getX() << 4,
			z1 = chunk.getZ() << 4,
			y1 = 0;
		
		int x2 = x1 + 15,
			z2 = z1 + 15,
			y2 = chunk.getWorld().getMaxHeight();
		
		Location lowLocation = chunk.getWorld().getBlockAt(x1, y1, z1).getLocation();
		Location highLocation = chunk.getWorld().getBlockAt(x2, y2, z2).getLocation();
		
		return create(locationLow, locationHigh);
	}
	
	// ... block
	// ... etc

```

2) Get all by ..

Maybe this already exists and I'm just too dumb to see it in the source, possible because I don't use/know the plugin - i'm just trying to add support 😝 

In Residence Manager:
```java
public List<ClaimedResidence> getResidencesIn(Chunk chunk);
public List<ClaimedResidence> getResidencesIn(Location loc1, Location loc2);
```

3) Expose x and z on `ChunkRef` 

Since we're limited to it, it would be helpful :) 

If you think these are good ideas I can go ahead and make a PR?

**Comment by MarkehMe** [comment]
This seems to be the only way to check for a chunk that I can see but maybe you could also give me a suggestion?

```java
	public Boolean isOwned(Chunk chunk) {
		int x1 = chunk.getX() << 4,
				z1 = chunk.getZ() << 4,
				y1 = 0;
			
			int x2 = x1 + 15,
				z2 = z1 + 15,
				y2 = chunk.getWorld().getMaxHeight();
			
		Location lowLocation = chunk.getWorld().getBlockAt(x1, y1, z1).getLocation();
		Location highLocation = chunk.getWorld().getBlockAt(x2, y2, z2).getLocation();
			
		CuboidArea area = new CuboidArea();
		area.setLowLocation(lowLocation);
		area.setHighLocation(highLocation);

		
		// TODO: is there a utility method that exists to do this already?
		return Residence.getInstance().getResidenceManager().getFromAllResidences(Config.get().residencesIncludeHidden, false, chunk.getWorld()).stream()
			.filter(claim -> 
				claim.checkCollision(area)
				
			/*
				claim.getAreaMap().values().stream()
					.filter(claimArea -> area.isAreaWithinArea(claimArea))
					.findFirst()
						.isPresent()
			 */
			)
			.findFirst()
				.isPresent();
	}
```

**Comment by Zrips** [comment]
Just create new CuboidArea by target chunk and check residence collision throw residenceManager with collidesWithResidence(CuboidArea newarea) this will return first residence colliding with that chunk.

**Comment by MarkehMe** [comment]
Cool, that will tidy up my last line a bit. 

Would you consider adding `CuboidArea` utilities or builders? 

Also, exposing `x` and `z` on `ChunkRef` - unless there is another way to get the `x` and `z` from `ChunkRef`?

**Comment by Zrips** [comment]
Can add ChunkRef x and z getter.
For CuboidArea utilities? You can create new one with
CuboidArea area = new CuboidArea(lowLoc, highLoc);
What else you would need?
