### ISSUE TITLE
Residence area selection affect WorldEdit

### ISSUE THREAD

**Issue by a1375625918** [Zrips/Residence#977]
My server is running CraftBukkit version 3610-Spigot-6198b5a-19df23a (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT).

I have Residence v5.1.0.1, CMILib v1.2.4.1 and WorldEdit v7.2.13 installed on my server, and WorldEditCUI v1.19+01 on my client.

When I select points with selection tool or do things like `/res expand` , my WorldEdit selection is set to the selected area or the resized residence. It's not what I expect.

Since no CUI event is sent to the client, WECUI didn't draw the new selection until I explicitly execute `/we cui` . This command is not necessary when selecting with wooden axe or `//pos1` `//pos2` commands, the selection will appear instantly instead. 

Some screenshots.

I selected two points with wooden hoe. Residence responded correctly.
![select points](https://user-images.githubusercontent.com/87858091/209944075-1711a2f0-6f0f-49cd-b684-a16a04bad725.png)

After executing `/we cui` , WECUI left following logs and drew the selection made by Residence.
```
[Render thread/INFO]: Debug - Received CUI event from server: s|cuboid
[Render thread/INFO]: Debug - CUI Event (s) - Params: cuboid
[Render thread/INFO]: Debug - Received selection event, initializing new region instance.
[Render thread/INFO]: Debug - Received CUI event from server: p|0|0|-59|-3|1
[Render thread/INFO]: Debug - CUI Event (p) - Params: 0, 0, -59, -3, 1
[Render thread/INFO]: Debug - Setting point #0
[Render thread/INFO]: Debug - Received CUI event from server: p|1|0|-59|-3|1
[Render thread/INFO]: Debug - CUI Event (p) - Params: 1, 0, -59, -3, 1
[Render thread/INFO]: Debug - Setting point #1
```
![update cui](https://user-images.githubusercontent.com/87858091/209944086-5c89452e-1b3c-4b66-a51c-e64e4784ec75.png)

After executing `//replace air` , these oak planks in the area were removed.
![remove blocks](https://user-images.githubusercontent.com/87858091/209944092-bf85f940-c4ac-4c2d-9f45-3be50ec1bac5.png)

Didn't notice anything relating to this behaviour. Still confused.

**Comment by Zrips** [comment]
da958556f3680c819f521b3a36a78146c66041d6

**Comment by a1375625918** [comment]
Hi Zrips,

I've updated the plugin to 5.1.1.0 and WECUI works fine. Thanks for the update.

However, I still don't know why Residence gives selection points to WorldEdit. Is that intended? Many of the players including me and the players/operators of a server I play in don't know that Residence wooden hoe can act as WorldEdit wooden axe, not to mention commands such as `/res expand` change WorldEdit selection. The selection is generally unnoticeable. But a client with WECUI will display it after rejoin/ `/we cui` with previous versions of Residence, or instantly now. Therefore here's this issue.

If so, please, consider providing a choice to disable sending Residence selection to WorldEdit. Or at least check one's selection permission before that. Updating WorldEdit selection of players without WE permissions only annoys WECUI users and `//sel` may be unaccessible too so they can't clear the selection. There is also potential risk for those with permissions to perform undesired operations in their resized residence instead of their previous selection. 

If not, please just stop it. Using WECUI to display selection area is a good feature, but it's not much necessary if it must change WE selection.

Much thanks.
