### ISSUE TITLE
server fly flag bug

### ISSUE THREAD

**Issue by ZZZXH** [Zrips/Residence#98]
I found a bug on my 1.12.1server for Residence 4.7.1.2 about fly flag. 
I give the players fly flag true on my server. 
The Residence A set fly true and Residence B set fly false. The Residence A is next to Residence B. 
Only when the player is flying on Residence A and get out of the Residence B. Then the player can fly in all world.(my english is not good, i wish you can understand it.)
So how to deal with the bug.

**Comment by Zrips** [comment]
Reproduced, will be fixed
