### ISSUE TITLE
[Feature request] Add RangeGap Option

### ISSUE THREAD

**Issue by cats-love** [Zrips/Residence#980]
Hello, we are using resistance to protect the property.

I'm using an option called RangeGap, and I'd like to suggest adding an option that can be done differently by coordinate or by world. Each server I use has a different size of rangegap that needs protection.

**Comment by cats-love** [comment]
ex)
RangeGap: 48
Worlds:
      - world
RangeGap: 16
Worlds:
      - flat

**Comment by Zrips** [comment]
1b41febfa6154958308591a9374eee379f1267ce
