### ISSUE TITLE
Using saveFileSplit but no additional files are created.

### ISSUE THREAD

**Issue by siulung201314** [Zrips/Residence#984]
I have enable NewSaveMechanic and saveFileSplit in config.yml.
However, residence save files are not split into multiple ones.
  
NewSaveMechanic: true
saveFileSplit: true
 
Purpur 1.19.2 
Residence version 5.1.0.1
CMILib verison 1.2.4.1

**Comment by Zrips** [comment]
This option will be removed, it was shortly introduced due to issues with yaml file size limitations introduced in recent yaml file handling libraries, this got patched and we no longer splitting files as that one was introducing unneeded complexity and some extra issues with it.
