### ISSUE TITLE
/res auto not making the right size of the residence

### ISSUE THREAD

**Issue by Skopii** [Zrips/Residence#985]
Without using:
 `      # Enabled this will switch to old method for calculating new residence area
      # Old method is allot less efficient, so its not recomended to be used when you have residence areas over 100
      OldMethod: true`
      
      Players are unable to make max size residences using /res auto. It will make their residence somehwere arround 180x180 when their limits are 250x250. (size in the config and percentages doesnt matter)
      
      Discussion about this topic on discord: https://discord.com/channels/452792793631555594/526403195476639744/1062371744637272136

**Comment by Zrips** [comment]
55d0bfb027bbac0e003952508bfd4120eaa93bd5
