### ISSUE TITLE
Owner changing after server restart

### ISSUE THREAD

**Issue by fortunatas1** [Zrips/Residence#986]
After server restart for some players can't use them residences, because residences owner changes nicknames. Like example: My nick is Questas and owner changing from Questas to questas. After server restart keeps chaning.

CMILIB version: 1.2.4.1
Version: git-Purpur-1848 (MC: 1.19.2)*
Residence version: 5.1.0.0

**Comment by Zrips** [comment]
Do you have OfflineMode set to true in config file?

**Comment by fortunatas1** [comment]
Yes.
