### ISSUE TITLE
/res kick

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [Zrips/Residence#993]
Hello,
 when a player wants to kick someone out of residence when using /res kick nick, it says he doesn't have permission.
I've looked on the site but haven't found much. The player also had permisse such as:

"residence.command.kick.others"
"residence.command.kick"

But unfortunately it says he still doesn't have permissions.
Thank you

**Comment by Zrips** [comment]
Most likely caused by player not having access to kick option over groups setup, there is special category to allow usage of this command and you might have it set to false.
