### ISSUE TITLE
Mangrove Signs Don't Work with Market Commands

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/Residence#994]
Heyo! Getting this error when attempting to set a mangrove sign as a Residence rental sign with the market commands. Had to spam it a few times to actually get the error, but in game it seemingly wasn't responding, just didn't do anything. No issues with other signs.

Error: https://gist.github.com/mercurialmusic/cff080278d30a7fef7c21617bd39fdb2

Residence version 5.1.1.0 with:
CMI plugin version: 9.3.1.0 BungeeCord CMIB  SqLite
CMILib: 1.2.4.3 
Server: Paper(383) 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 55 enabled 2 disabled: ranks, skin

Thanks!

**Comment by Zrips** [comment]
0385a57f9aea4da6058c7a6191c29a00d7ea86bf
