### ISSUE TITLE
More help needed for WorldEdit selection

### ISSUE THREAD

**Issue by a1375625918** [Zrips/Residence#997]
As https://github.com/Zrips/Residence/issues/977#issuecomment-1383150397 , I still have some unsolved problems about WorldEdit selection.

### Main Question:

Is it necessary to send Residence area selection and expand/contract result to WorldEdit?

If so, please don't send it when one don't have WorldEdit selection permission. A config option or command to control whether to send it is appreciated.

If not, please stop sending it. Nothing below will happen then.

### Case 1:

I don't have any WorldEdit permission, so I can't make a WorldEdit selection generally. But Residence will create one for me when using its selection tool (wooden hoe) or `/res expand` `/res contract` etc. WECUI will display the selection instantly now (or after `/we cui` in previous Residence version).

What's more, forks like ***FastAsync***WorldEdit have a permission check for `//sel` which the original WorldEdit don't have. Therefore, I can't clear the selection if the server is using these forks, which means the selection won't disappear unless I disable WECUI.

![sel](https://user-images.githubusercontent.com/87858091/215450525-15bfce5b-5744-483d-8f92-63b372cc5560.png)

### Case 2:

I have all of the permissions now. I built a structure as the one below and I'm going to copy and paste the selected part to extend its length.

![part](https://user-images.githubusercontent.com/87858091/215455759-5e890ea8-8f21-4bf5-8255-b05fb9665dd7.png)

If everything is right, the result will be the same as shown below.

![copy](https://user-images.githubusercontent.com/87858091/215457552-2be4c1b5-0e73-4f0a-a9a9-908a0504f476.png)

However, if I create or expand a claim before `//copy`, I won't notice that Residence changes my selection sliently without WECUI.

![claim](https://user-images.githubusercontent.com/87858091/215454108-94461eab-324c-450a-8704-c5a3023ae516.png)

![expand](https://user-images.githubusercontent.com/87858091/215458244-a08faa4d-03ee-40c0-9fe2-3bb87ecfe5a3.png)

Finally, the result may be this unexpected one.

![wrong](https://user-images.githubusercontent.com/87858091/215459233-52beae11-2f63-4136-a7a9-eb12d50a0413.png)

Please tell me if more information is needed.

**Comment by Zrips** [comment]
8fc40002d85914f16b70c46b57ebe6582a17ea4a
465a25e16e1d41b4b6db3c9ab45825c45eb22bde
